### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Telemakhos** [wekan/wekan#128] opened 2015-01-30 13:08 UTC
I think designing an API for integration with other apps would be an awesome addition.

http://meteorpedia.com/read/REST_API

**Comment by miurahr** [comment] 2015-03-29 08:45
Hubot integration may be a killer feature.

**Comment by fix** [comment] 2015-03-30 07:09
I think focusing on a DDP API shoukd be a better approach. There are plenty of DDP client around, and that yould leverage the true power of meteor, simplifying a lot the integration (API, WEBHOOK, AUTHENTICATION, etc..)

**Comment by cathalgarvey** [comment] 2015-05-25 12:16
Bump. I'd consider this a key feature; an easy-to-use API that lets people add functions to Libreboard would be a *huge* selling point for me. I would love if I could use Libreboard to implement a rich data-processing front-end: Imagine adding/changing data to lists and having other lists' cards dynamically change, spread-sheet style? A quick python robot with the right API could do that, and add a lot of value.

**Comment by kadishmal** [comment] 2015-07-31 18:07
I may find some time to design the REST API. I have extensive experience in designing and documentation an API. As a start, since Libreboard is an open source tool, I would suggest maintaining the docs at https://apiary.io. Free for an open source project. At our company we can't use any external cloud services, so we use the [API Blueprint](https://apiblueprint.org) syntax (a Markdown superset) and host it locally.

**Comment by Telemakhos** [comment] 2015-08-04 22:57
@kadishmal Do you think that would be better option than say swagger 2.0? From a swagger spec you can generate client/server boilerplates for many languages/frameworks... I think it'd be a better option. Check out the [swagger editor](http://editor.swagger.io/), the examples and specially the export options.

As for DDP, it'd be better to have it just in the mobile clients. With Uri's [angular-meteor](https://github.com/Urigo/angular-meteor) and [meteor-ionic](https://github.com/Urigo/meteor-ionic), it's quite easy to get some code up & running in no time.

**Comment by kadishmal** [comment] 2015-08-05 04:32
DDP in my country means Digital Design Plaza. Did you it?

Regarding swagger, I haven't seen it. If it's better, better to use swagger. Will check later and comment back. Apiary also generates code snippets for various languages and also provides a dummy API server to test you spec.

**Comment by dalerka** [comment] 2015-08-05 05:13
@kadishmal  [DDP == Distributed Data Protocol](https://www.meteor.com/ddp)  - one of the most exciting things about the Meteor framework.  
BTW, there's a lot of useful info on Meteor's website/blog, [Docs buried in the footer](https://docs.meteor.com/), and [forums](https://forums.meteor.com), welcome! :)

**Comment by rennhak** [comment] 2016-03-06 02:00
+1

**Comment by jibe-b** [comment] 2016-06-19 01:44
+1

**Comment by ArtemT** [comment] 2016-07-26 10:49
++

**Comment by ForNeVeR** [comment] 2016-10-10 05:01
That's a duplicate of more actively discussed #166.

**Comment by xet7** [comment] 2017-02-19 18:45
Moved to #166

**Closed by xet7** 2017-02-19 18:45 UTC
Labels: API, Discussion
