### ISSUE TITLE
Image Cover failing for jpg or .jpeg images

### ISSUE THREAD

**Issue by nata-goddanti** [wekan/wekan#139] opened 2015-02-15 06:43 UTC
It seems as though only .png images are being displayed as the cover on the card but not the .jpg and .jpeg image extensions

**Comment by mquandalle** [comment] 2015-08-28 09:08
I can’t reproduce this, could you confirm that this is fixed on `master` (or http://newui.libreboard.com)?

**Comment by nata-goddanti** [comment] 2015-08-28 20:40
@mquandalle  when I am testing this issue, the cover seems to be working but loadin the attachments seems to be slow, I did a test of attaching a 459kb image and it has taken 7.84 seconds (out of which 6.50 seconds is the wait time) to , below is the screenshot.

![image](https://cloud.githubusercontent.com/assets/203255/9555983/fe5841da-4d85-11e5-884b-79467fd4a6b7.png)

I added one more image 362 kb and it has taken 5.76 seconds. Below is the screenshot

![image](https://cloud.githubusercontent.com/assets/203255/9556373/21059fc2-4d89-11e5-8885-dbfd5c96d282.png)


To benchmark the time, I uploading an instance on meteor.com from my local repo (my instance is few weeks older) and below are the timings of the same images (1.58 seconds and 1.62 seconds)
![image](https://cloud.githubusercontent.com/assets/203255/9556475/c22835f4-4d89-11e5-938f-5a8af708db2f.png)

It seems in the latest instance loading the attachments seems to be slower compared to the previous instances.

**Comment by nata-goddanti** [comment] 2015-08-29 05:48
I tested one more time right now (around 10.45 pm PST) when the meteor.com is not at peak and I guess the images are loading much faster. Below is the screenshot. I guess it much be the issue of the of hosting server and not the app...

![image](https://cloud.githubusercontent.com/assets/203255/9560683/b3169806-4dd6-11e5-9637-ae81baabc690.png)

**Comment by mquandalle** [comment] 2015-08-30 14:34
I'm pretty sure the long uploading time is due to the fact that newui.libreboard.com uses the meteor free hosting solution. I'll investigate if meteor commercial hosting (Galaxy) is worth it for this project.. But motivation for working on this project is still that people will be able to host it on their own machine.

**Closed by mquandalle** 2015-08-30 14:34 UTC
Labels: Bug
