### ISSUE TITLE
[bug] move cards to rule

### ISSUE THREAD

**Issue by sh2515** [wekan/wekan#2312] opened 2019-04-04 23:31 UTC
## Issue
Example.
When the rule 'on move card to swimlane 1' 'change colour'. What happens is the card changes colour no matter which swim lane it goes in.

Add these issues to elsewhere:
Snap package

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?:
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version:
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Ubuntu 18.04
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
Goto rules
Select when card moved to list or swimlane
Type which ever swim lane you want it to change entering
Select colour

- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
- *If using Docker, what does show command `sudo docker logs wekan-app` ?*
- *If logs are very long, attach them in .zip file*

**Comment by Angtrim** [comment] 2019-04-06 12:52
@xet7 I think this is a duplicate of #2225 and can be closed.

**Closed** 2019-04-06 13:00 UTC
Labels: Bug, Feature:Cards:IFTTT-Rules

**Comment by sh2515** [comment] 2019-04-06 18:18
> @xet7 I think this is a duplicate of #2225 and can be closed.

Thanks, I can confirm this has now been fixed in version 2.59
