### ISSUE TITLE
Old wekan version in snapstore

### ISSUE THREAD

**Issue by Danny-Graf** [wekan/wekan#5226] opened 2023-11-27 13:53 UTC
Hello,

in the snapstore is only an "old" version of wekan available: 

`wekan 6.09 from Lauri Ojansivu (xet7) installed`

Best regards,
Danny

**Comment by xet7** [comment] 2023-11-27 15:17
Yes. There will be automatic upgrade to newest. I'm In Progress of fixing related migration issues.

**Comment by xet7** [comment] 2023-11-27 15:19
> only an "old" version of wekan

No, that is incorrect. Candidate channel has newest WeKan:

https://github.com/wekan/wekan/wiki/OpenSuse

**Comment by Ilav1** [comment] 2023-12-20 09:09
I also have installed version 6.09. When I try to update with these code

`sudo snap refresh wekan --channel=latest/candidate
`

The newest version is installed now. Wekan is not available after updating. When I refresh to the stable version, wekan is available again. 

Updating to the newest version is not possible. Maybe you have an other way to update wekan to the candidate version...

**Comment by xet7** [comment] 2023-12-20 12:21
@Ilav1 

I'm currently coding automatic upgrade. It will upgrade all Snap Stable from 6.09 to newest WeKan automatically.

Manual upgrade currently has too many steps, that are time too consuming to do manually:

1) Mongodump, using Snap 6.09 version of mongodump
2) Mongorestore, using newest mongorestore
3) To get attachments visible
3.1) Rename collections/tables of database:
```
  rename cfs_gridfs.attachments.files attachments.files
  rename cfs_gridfs.attachments.chunks attachments.chunks
  rename cfs_gridfs.avatars.files avatars.files
  rename cfs_gridfs.avatars.chunks avatars.chunks
```
3.2) Convert attachments database structure to new format, with upcoming code function:
```
  convertup cfs.attachments.filerecord attachments
  convertup cfs.avatars.filerecord avatars
```
I'm currently writing code functions for all that. I do not recommend trying it manually.

**Comment by xet7** [comment] 2023-12-20 12:26
@Ilav1 

These are my current In Progress scripts for upgrade and downgrade. These do not yet make attachments visible, coding that is In Progress.

##  upgrade.sh
```
#!/bin/bash

if [ $(whoami) = 'root' ]; then
  echo "Countinuing, because running as root."
else
  echo "Not continuing, because not running as root."
  exit
fi

# SNAP_COMMON=
snap stop wekan.wekan
export LD2=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/snap/wekan/current/lib/x86_64-linux-gnu
export PATH2=$PATH
export PATH=/snap/wekan/current/bin:$PATH
sleep 1
mongodump --port 27019
snap get wekan > snap-settings.txt
snap stop wekan.mongodb
sleep 1
if [ -d "common" ]; then
  rm -rf /var/snap/wekan/common/*
else
  mv /var/snap/wekan/common .
  mkdir /var/snap/wekan/common
fi
snap refresh wekan --channel=latest/candidate
sleep 1
snap start wekan
sleep 1
snap stop wekan.wekan
sleep 1
export PATH=$PATH2
export LD_LIBRARY_PATH=$LD2
mongorestore --drop --port 27019
sleep 1
snap start wekan.wekan
```
## downgrade.sh
```
#!/bin/bash

if [ $(whoami) = 'root' ]; then
  echo "Countinuing, because running as root."
else
  echo "Not continuing, because not running as root."
  exit
fi

snap stop wekan
sleep 1
rm -rf /var/snap/wekan/common/*
snap refresh wekan --channel=latest/stable
sleep 1
snap stop wekan
sleep 1
rm -rf /var/snap/wekan/common/*
cp -pR common/* /var/snap/wekan/common/
snap start wekan
``

**Comment by Ilav1** [comment] 2023-12-20 17:43
Nice to know. Thank you for your work. Do you have any suggestions when the script is done?

The stable version will automatically upgrade to the newest version when the script is finished, right?

**Comment by xet7** [comment] 2023-12-20 17:56
For any code, it is so unpredictable how long it takes to finish it, I don't know.

Most likely I will add that script to this issue, when I have finished it, to make possible manual upgrade.

There is also other questions related to how to upgrade Caddy 1 to newest, when AFAIK Caddy 2 does not support Caddy 1 Caddyfile file forma.

**Comment by Ilav1** [comment] 2024-01-09 21:01
One more question. When I install the latest candidate on a new system, is the latest candidate version updated automaticly by snap? I think the problem is the old version updating to the newsest isn't it?

**Comment by xet7** [comment] 2024-01-09 21:35
@Ilav1 

Yes, Snap Candidate is updated automatically by Snap, it is always newest version.

After I have fixed migrations, I will release newest WeKan also to Snap Stable. Those migrations will convert Snap Stable to newest WeKan, updating database, attachments etc.

**Comment by CasualGarageCoder** [comment] 2024-01-28 03:15
First of all, thank you for the support and the effort.
I've tried the update script. It fails at `mongorestore --drop --port 27019`  but it was predictable (not only because the PATH and the LD_LIBRARY_PATH are not valid, but because of the big "`Failed: error connecting to db server: no reachable servers`". When I've seen this error, I knew that problems were only starting and a long procress/script awaits to finally migrate the whole thing. I'll try to make it work, but I guess there's some pitfalls hidden here and there :)

**Comment by xet7** [comment] 2024-01-29 18:05
@0x6DD8 

The point is for you to wait, when I have fixed attachments migration code, and released automatic update, that updates Snap Stable from 6.09 to newest 7.x automatically.

**Comment by Danny-Graf** [comment] 2024-02-22 15:25
Hi @xet7 

I just wanted to ask, if there is any update about this topic?

thank you and best regards,
Danny

**Comment by Danny-Graf** [comment] 2024-02-23 05:07
@xet7 

Thank you, what would that mean for the update? If I migrate to SQLite, how can I update the installed Wekan version?

Best regards,
Danny

**Comment by xet7** [comment] 2024-02-23 05:41
@Danny-Graf 

No, you don't need to migrate anything.

There will be automatic update to WeKan Snap Stable, that will upgrade from 6.09 to newest 7.x.

**Comment by Danny-Graf** [comment] 2024-02-23 05:46
@xet7 

Okay, thank you for the information. When the automatic update will be proceeded? Do I need to do anything?

Thank you and best regards,
Danny

**Comment by xet7** [comment] 2024-02-23 06:03
@Danny-Graf 

No, you don't need to do anything. When I have finished additional code, and released it to Snap Stable, it updates all Snap Stable installs wordwide automatically very fast.

There is no exact date when it will happen. It will be when fixes are ready and tested that they work.

**Comment by lezioul** [comment] 2024-02-23 09:34
@xet7 : sooo..., no more MongoDB, next stable will be using SQLite? (great news, actually)

**Comment by xet7** [comment] 2024-02-23 10:27
@lezioul 

Yes, that is the plan.

**Comment by jeroenstoker** [comment] 2024-03-10 20:53
Is there something I can do to help you?

**Comment by xet7** [comment] 2024-03-11 09:54
@jeroenstoker 

Yes. Send PRs related to any open issues. And tag me with @xet7 if some issue can be closed. These help every WeKan user.

**Comment by lorodoes** [comment] 2024-03-17 23:58
https://github.com/wekan/wekan/pull/5349

Should be fixed with this pull

**Comment by lezioul** [comment] 2024-03-19 10:37
Hi!
Sorry to re-open this issue but i have a question : can we now upgrade from stable to edge?

Best Regards,

lezioul

**Comment by xet7** [comment] 2024-03-19 11:48
@lezioul 

No, I think. At least it did not work for me, when I tried to change from Stable to Candidate. MongoDB had some error, related to raw database files of MongoDB 3 not being compatible with MongoDB 6. I presume it requires mongodump from MongoDB 3, and mongorestore to MongoDB 6. Maybe other changes too, if attachments are not visible.

**Comment by lezioul** [comment] 2024-06-20 07:44
hi xet7,

is there any way to help you manage a seamless transition from wekan stable to edge?
Please, let me know.

Regards

**Comment by xet7** [comment] 2024-06-20 09:13
@lezioul 

It would help for someone to test current migration scripts, do they work at all, and improve them, to migrate from MongoDB 3 to 6:

https://github.com/wekan/wekan/blob/main/snap-src/bin/mongodb-control#L21

https://github.com/wekan/wekan/blob/main/snapcraft.yaml#L200

It's possible to build snap package with:

```
sudo snap install snapcraft --classic

cd wekan

snapcraft
``

**Comment by hunter440p** [comment] 2024-07-29 18:46
I'm stuck in 6.09 version with snap. It's a big problem for the security to not be able to update. My company will probably abandon wekan for this reason if I can't update it.

Is there a way to migrate to the docker version ?
What are the steps to follow to migrate to the latest version of wekan ?

Best Regards,

**Comment by xet7** [comment] 2024-07-29 21:58
@hunter440p 

a) Wait for automatic update, that upgrades Snap 6.09 to newest Snap 7.x automatically

b) If you are in a hurry, try the manual way:

For Snap, you can make mongodump this way:

https://github.com/wekan/wekan/wiki/Backup#backup-wekan-snap-to-directory-dump

With similar way, using mongofiles from Snap, save attachment, with some code like at https://github.com/wekan/minio-metadata

There is docker-compose.yml at https://github.com/wekan/wekan , there change ROOT_URL, PORT etc, and do:
```
docker-compose up -d
```

Restore to Docker: https://github.com/wekan/wekan/wiki/Backup#restore-docker

If some attachments are missing from boards, add them back manually.

**Comment by xet7** [comment] 2024-07-29 22:03
That manual way to migrate will be improved, with better migration tool, currently in development.

**Comment by hunter440p** [comment] 2024-07-29 22:46
> @hunter440p
> 
> a) Wait for automatic update, that upgrades Snap 6.09 to newest Snap 7.x automatically
> 
> b) If you are in a hurry, try the manual way:
> 
> For Snap, you can make mongodump this way:
> 
> https://github.com/wekan/wekan/wiki/Backup#backup-wekan-snap-to-directory-dump
> 
> With similar way, using mongofiles from Snap, save attachment, with some code like at https://github.com/wekan/minio-metadata
> 
> There is docker-compose.yml at https://github.com/wekan/wekan , there change ROOT_URL, PORT etc, and do:
> 
> ```
> docker-compose up -d
> ```
> 
> Restore to Docker: https://github.com/wekan/wekan/wiki/Backup#restore-docker
> 
> If some attachments are missing from boards, add them back manually.

Thanks a lot !
Do I need to convert from Snap V6.09 to Docker V6.09, then from V6.09 to Docker V7 ?
Mongo DB has a different version in V7, so I wondered if the conversion need to be done by following steps in update of versions (ex : V6.09 to V6.50 then to V6.90 and finally to V7.X)
Thanks

**Comment by xet7** [comment] 2024-07-30 00:24
@hunter440p 

For Snap V6.09, you use versions of mongodump and mongofiles included in that Snap V6.09 directories.

For Docker V7, you use newest mongorestore, that is included in mongo docker container, used at newest docker-compose.yml

**Comment by xet7** [comment] 2024-08-06 19:06
Moved to https://github.com/wekan/wekan/issues/5475

**Closed by xet7** 2024-08-06 19:06 UTC
Labels: Targets:Ubuntu-snap

**Comment by lezioul** [comment] 2024-08-08 08:02
> @hunter440p
> 
> a) Wait for automatic update, that upgrades Snap 6.09 to newest Snap 7.x automatically
> 
> b) If you are in a hurry, try the manual way:
> 
> For Snap, you can make mongodump this way:
> 
> https://github.com/wekan/wekan/wiki/Backup#backup-wekan-snap-to-directory-dump
> 
> With similar way, using mongofiles from Snap, save attachment, with some code like at https://github.com/wekan/minio-metadata
> 
> There is docker-compose.yml at https://github.com/wekan/wekan , there change ROOT_URL, PORT etc, and do:
> 
> ```
> docker-compose up -d
> ```
> 
> Restore to Docker: https://github.com/wekan/wekan/wiki/Backup#restore-docker
> 
> If some attachments are missing from boards, add them back manually.

Sorry, i've just seen your message today and i'll go on holiday leave tomorrow so i won't be able to test it until september :/

**Comment by lezioul** [comment] 2024-08-08 08:03
> @lezioul
> 
> It would help for someone to test current migration scripts, do they work at all, and improve them, to migrate from MongoDB 3 to 6:
> 
> https://github.com/wekan/wekan/blob/main/snap-src/bin/mongodb-control#L21
> 
> https://github.com/wekan/wekan/blob/main/snapcraft.yaml#L200
> 
> It's possible to build snap package with:
> 
> ```
> sudo snap install snapcraft --classic
> 
> cd wekan
> 
> snapcraft
> ```
> 
> And then have WeKan Stable Snap 6.09, and try to install new snap, does it upgrade correctly:
> 
> ```
> sudo snap install wekan.snap --dangerous
> ```

Damn, i've just seen your message today and i'll go on holiday leave tomorrow so i won't be able to test it until september :/

**Comment by xet7** [comment] 2024-08-08 08:23
@lezioul 

Have a nice holiday! Try to relax.

**Comment by xet7** [comment] 2024-11-08 18:06
@lezioul 

Here I explained about attachments and avatars:

https://github.com/wekan/wekan/discussions/5557#discussioncomment-11135860

You can try can you get some progress. I will also try.

**Comment by lezioul** [comment] 2024-11-10 16:49
i've tryied the following : 

1. mongodump my actual DB
2. install fresh stable snap wekan
3. mongoimport my dump
4. using a migration script writen in js to transform collectionFS to meteor-files in a new DB
5. mongodump this newDB
6. install fresh latest/candidate snap wekan
7. import this DB

i have no errors but login is forbidden

here is my script to transform collectionFS, maybe i'm missing a point : 

```
const { MongoClient } = require('mongodb');

async function migrateAllCollections() {
  const client = new MongoClient('mongodb://localhost:27019');
  await client.connect();

  const oldDb = client.db('wekan'); 
  const newDb = client.db('meteorwekan'); 

  // Lister toutes les collections dans l'ancienne base de données
  const collections = await oldDb.listCollections().toArray();

  for (const collection of collections) {
    const oldCollection = oldDb.collection(collection.name);
    const newCollection = newDb.collection(collection.name); // Crée une nouvelle collection avec le même nom

    const documents = await oldCollection.find().toArray();

    // Transformer et insérer les documents dans la nouvelle collection
    const transformedDocuments = documents.map(file => {
      return {
        name: file.name,
        size: file.size,
        type: file.type,
        path: file.path, // Ajustez en fonction de votre configuration CollectionFS
        // Ajoutez d'autres champs requis par Meteor-Files ici
        // Par exemple, si Meteor-Files nécessite un champ `userId`, vous pouvez l'ajouter ici
        // userId: file.userId,
      };
    });

    if (transformedDocuments.length > 0) {
      await newCollection.insertMany(transformedDocuments);
      console.log(`Migré ${transformedDocuments.length} documents de ${collection.name} vers ${newCollection.collectionName}`);
    } else {
      console.log(`Aucun document à migrer pour la collection ${collection.name}`);
    }
  }

  await client.close();
}

```

**Comment by xet7** [comment] 2024-11-10 17:06
@lezioul 

Try this #5562
