### ISSUE TITLE
Bug: Releases missing submodules, leads to old bugs like: Appended double slashes to ROOT_URL

### ISSUE THREAD

**Issue by NoodleBB** [wekan/wekan#962] opened 2017-03-31 14:32 UTC
Problem: Bind Wekan to a path leads to double slashes in the URL, **only when clicking on a card** and when you to "**export board**". 

Steps to reproduce:
* Append path component to the Root URL. `ROOT_URL=https://mydomain.org/wekan`
* Start Wekan. `node ~/wekan/bundle/main.js`
* Open the URL in the browser. `https://mydomain.org/wekan`
* Log-In into Wekan. Select a board. Create some random cards.
* Then click on any card. - **Error: "Page not found"**.

Finally: Inspect the URL and you'll find double slashes. 
![double slash](https://cloud.githubusercontent.com/assets/11850083/24554904/7c77c810-162f-11e7-855a-58de669e12c6.png)

When you remove one of these slashes, you'll see the open dialog.

Rem.: This bug could be related to #907.

**Comment by xet7** [comment] 2017-03-31 14:37
@NoodleBB 

What Wekan version are you using? This is already fixed https://github.com/wekan/wekan/pull/932

**Comment by NoodleBB** [comment] 2017-03-31 14:40
I think Wekan v.0.17.

**Comment by xet7** [comment] 2017-03-31 14:54
@Serubin 

Can you look at this?

**Comment by NoodleBB** [comment] 2017-03-31 19:13
I've setup another Wekan demo (v0.17) that points out the problem. 
[Here you can test it](https://wekan008.serpens.uberspace.de/wekan/b/W7CYeMDRkDekL3tvv/welcome-board#). 

Demo-User: yeswekan
Demo-Pass: yeswekan99

The ROOT_URL is `https://wekan008.serpens.uberspace.de/wekan`.

Steps to reproduce:
* When you **click on the cards** or try to **export board** via board menu, you'll encounter the "Page not found". 
* When you select and remove the second slash behind the "_wekan//_", then it works and you'll see the dialog.

Version: wekan-0.17

@xet7 
**Don't panic.** The access data is just for demo purposes. This is not a production machine. User and all data will be destroyed within 30 days.

**Comment by Serubin** [comment] 2017-04-02 05:17
@NoodleBB I took a look at the demo site you provided. It appears as the javascript is an older version. Make sure you properly rebuild wekan using the code below.

```bash
source app.env

# Rebuild meteor stuff
rm -rf .build
meteor build .build --directory

# Install depends
cd .build/bundle/programs/server
npm install
```

**Comment by NoodleBB** [comment] 2017-04-02 09:02
@xet7 @Serubin 
So it is a bug in the release. I've used your release version:
https://github.com/wekan/wekan/releases/download/v0.17/wekan-0.17.tar.gz

**Comment by xet7** [comment] 2017-04-02 09:08
@NoodleBB 

Releases get old quickly. I do tests and merges on devel head.

**Comment by NoodleBB** [comment] 2017-04-02 09:09
@xet7 
So it's still a bug. To reproduce it follow the steps in the [Manual Installation](https://github.com/wekan/wekan/wiki/Install-and-Update#manual-installation-steps).

**Comment by xet7** [comment] 2017-04-02 09:55
@NoodleBB 

Hmm, maybe I'll check it sometime.

**Comment by xet7** [comment] 2017-04-02 09:58
Moved to #969

**Comment by Serubin** [comment] 2017-04-02 14:51
@NoodleBB Downloading the tar likely does not download the required submodule and will default to using the default flow-router. Try pulling recursively using git and rebuilding.

**Comment by NoodleBB** [comment] 2017-04-02 15:00
@Serubin The unit-tests should throw an error.

**Comment by xet7** [comment] 2017-04-02 15:03
@NoodleBB 

We don't have any unit tests.

**Comment by xet7** [comment] 2017-04-02 15:07
@NoodleBB 

I moved your issue back to here.

We could have some checks and error messages for this.

**Comment by xet7** [comment] 2017-04-02 15:10
@NoodleBB 

Doh, it seems to be my problem. I did not update submodules for releases. I will update releases later.

**Comment by NoodleBB** [comment] 2017-04-02 15:11
> We don't have any unit tests.
Okay. This explain some things.

> I moved your issue back to here.
No problem. Organise it the way, that you'll have the best overview. :simple_smile:

**Comment by xet7** [comment] 2017-04-02 15:14
@NoodleBB 

There could be some tests somewhere, but I have not tried to find them yet. Usually I just build Wekan and test does it work or does it crash. I keep Wekan devel head working.

Travis and Docker builds have some tests, but they are broken. I can build Wekan and it works great though.

**Comment by NoodleBB** [comment] 2017-04-02 15:29
I know, writing unit-tests is boring.

**Comment by xet7** [comment] 2017-04-02 15:30
@NoodleBB 

I updated release v0.18 to include submodules. Can you test does that .tar.gz work for you now?

**Comment by NoodleBB** [comment] 2017-04-02 15:31
Sure.

**Comment by NoodleBB** [comment] 2017-04-02 16:09
Yes it works. 👍

**Comment by xet7** [comment] 2017-04-02 17:44
Great! :)

**Comment by xet7** [comment] 2017-04-03 14:27
Including submodules leads to bug, so language cannot be changed anymore.

I need to regenerate releases without submodules.

**Comment by xet7** [comment] 2017-04-03 16:59
Ok I made a script that regenerated all tar.gz releases and uploaded them.

**Comment by xet7** [comment] 2017-04-03 17:00
I think those existing submodules probably need to be removed, because changing language is important feature.

**Comment by Serubin** [comment] 2017-04-03 17:03
Is there any indication as to what is causing the language issue. The
submodule should have no effect on anything really.

**Comment by NoodleBB** [comment] 2017-04-03 17:04
This is really weird. But the language value is set in the db.

**Comment by Serubin** [comment] 2017-04-05 17:25
@xet7 Any indication on where the language bug is coming from?

**Comment by NoodleBB** [comment] 2017-04-05 17:36
Yes. This is one of the three resources (/tap-i18n/de.json, /cfs/files/avatars/, /setting), that 
doesn't use the ROOT_URL for access.

**Comment by Serubin** [comment] 2017-04-05 18:02
@NoodleBB Ah, thank you!

So this is not an issue with the double slash fix. It's an issue with modules not using the ROOT_URL. This issue should be renamed and linked to those parts of the application.

**Comment by NoodleBB** [comment] 2017-04-07 06:47
> So this is not an issue with the double slash fix. 

Correct. 

> It's an issue with modules not using the ROOT_URL. 

Right. 

> This issue should be renamed and linked to those parts of the application.

This is a separate bug. I've opened an issue under #973 "Bug: Can't set language".
But it was wrongly merged into this one.

**Comment by xet7** [comment] 2017-04-07 07:25
@NoodleBB 

I reopened #973 , it can be continued there.

**Comment by NoodleBB** [comment] 2017-04-07 07:28
Perfect.

**Comment by NoodleBB** [comment] 2017-04-09 16:07
> Ok I made a script that regenerated all tar.gz releases and uploaded them.

So the doubleslash bug was reactivated

**Comment by nztqa** [comment] 2017-06-26 08:35
The bug can't be reproduced.

![wekan_url_double_slashes-iloveimg-compressed](https://user-images.githubusercontent.com/22808079/27530982-ddfc26e4-5a95-11e7-83bf-5f74c4d48b71.gif)

**Comment by rubberduck203** [comment] 2017-07-22 14:34
This appears to be back.

It works in v0.24, but not in v0.25-v0.29.

**Comment by xet7** [comment] 2017-07-22 14:57
@nztqa 

Can you reproduce this bug?

**Comment by rubberduck203** [comment] 2017-07-22 15:02
FWIW I was testing the docker builds from wekanteam/wekan.

**Comment by nztqa** [comment] 2017-07-22 16:44
It's just a docker problem

It starts from here.　https://github.com/wekan/wekan/commit/f0f27d1b95a09d1244dbe3eeef5deb879192136a#diff-3254677a7917c6c01f55212f86c57fbf

**Comment by xet7** [comment] 2017-07-22 18:51
@nztqa 

Is it possible to fix that without adding git submodules back?

For example, should I fork whole meteor repo to Wekan and add changes to there directly?

**Comment by rubberduck203** [comment] 2017-07-22 18:54
If I'm catching the drift, the cache isn't being invalidated. Is that correct?

**Comment by nztqa** [comment] 2017-07-22 23:48
Try with the same path as the source installation (https://github.com/wekan/wekan/wiki/Install-and-Update#install-and-build-wekan)
```
-    mkdir -p /home/wekan/.meteor/packages && ¥
+    mkdir -p /home/wekan/app/packages && ¥
```

**Comment by xet7** [comment] 2017-07-24 12:58
@nztqa 

I tested with those changed and could not reproduce bug anymore. Is it fixed for you too, using wekanteam latest docker image?

**Comment by nztqa** [comment] 2017-07-24 13:15
OK.

**Comment by xet7** [comment] 2017-07-25 12:56
Fixed at 4fdcc144d5342b6571b9e53e9a18640871e0c18b

**Comment by xet7** [comment] 2017-12-20 20:52
This still happends when using snap, when I tried to add wekan to sub-url like example.com/wekan , and there was Drupal website at example.com . I'll try to apply previous fixes to this.

**Comment by xet7** [comment] 2018-01-15 14:25
Please test newest Ubuntu Snap, is double slash bug now fixed.

It seems to work for me.

**Comment by xet7** [comment] 2018-01-15 20:48
With Nginx and Wekan at sub-url it works for me, there is no double slash bug, with Nginx and snap settings at this page:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

**Closed** 2018-01-15 20:48 UTC
Labels: Bug, High-priority

**Comment by tobiasrenger-gh** [comment] 2018-02-07 12:04
I'm running Wekan v0.71 (with Meteor v1.6.0.1) on Windows Server 2012 R2 ([installed it from source](https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows)).

If the environment variable `ROOT_URL` is set to `http://localhost:3000` all URLs are fine. But when `ROOT_URL` is set to `http://localhost:3000/wekan` the links to the cards in the swimlane/activities-sidebar begin with `http://localhost:3000/wekan//b/` (note the double slash after `/wekan`).
