### ISSUE TITLE
Activation code can not be entered when self registration is disabled

### ISSUE THREAD

**Issue by GuiGuiSoft** [wekan/wekan#1749] opened 2018-07-04 13:54 UTC
### Server Setup Information:

* Did you test in newest Wekan?: Yes
* Wekan version: 1.11.0
* If this is about old version of Wekan, what upgrade problem you have?: *N/A*
* Operating System: Ubuntu 16.04 LTS
* Deployment Method: Snap
* Http frontend if any : Nginx
* Node Version: 8.11.1
* MongoDB Version: *How to find it with snap installation ?*
* ROOT_URL environment variable: *by email if needed (no subfolder)*

### Problem description:

**Step to reproduce:**

- Disable Self-Registration in administration panel.
- Send an invitation to a new user
- New user receive the following mail and click on the link
![image](https://user-images.githubusercontent.com/8069239/42280833-2140658c-7fa2-11e8-897f-ae7b7d715e4f.png)
- New user try to log-in but can not enter the invitation code
![image](https://user-images.githubusercontent.com/8069239/42280656-a7b95c8c-7fa1-11e8-9148-396a0898c487.png)

**Expected behavior:**

A field is available to enter invitation code (so the new user can sign-up and use Wekan)

**Comment by neverwet** [comment] 2018-07-07 19:39
I have a same error in latest version from docker hub.

**Comment by TNick** [comment] 2018-07-07 19:41
@neverwet Using devel? Or master?

**Comment by TNick** [comment] 2018-07-07 19:49
The line that decides if the field is set in client code is [here](https://github.com/wekan/wekan/blob/devel/client/components/settings/invitationCode.js#L3) in devel and it states that the code field will be hidden ifL
1) there is no settings object in the database
2) there is a settings object but registration to the public is allowed

**Comment by neverwet** [comment] 2018-07-07 21:11
@TNick 1.18.0, but I don't know develop or master.

**Comment by GuiGuiSoft** [comment] 2018-07-09 11:43
Hello,

The snap updated itself and I confirm that 1.18 still has this issue.

Regards.

**Comment by biji** [comment] 2018-07-10 05:15
It is hidden with `display: none` style

**Comment by biji** [comment] 2018-07-11 04:36
@TNick changes already merged to [master](https://github.com/wekan/wekan/blob/master/client/components/settings/invitationCode.js)
But this issue still happen

my settings:

![image](https://user-images.githubusercontent.com/665559/42550888-987aa57a-84fe-11e8-9b71-d1d5db71ac0a.png)

thanks

**Comment by TNick** [comment] 2018-07-11 16:23
@biji will look into this but right now I'm focused elsewhere.
Do you think that you can download the sourcecode and run it on a local machine?
If so I can guide you in debugging the issue.

**Comment by biji** [comment] 2018-07-12 06:20
I have cloned the repo but not familiar with nodejs development, how to start the app

**Comment by biji** [comment] 2018-07-12 07:40
fedora linux, nodejs v8.11.3 and mongodb set

**Comment by TNick** [comment] 2018-07-12 08:19
curl https://install.meteor.com/ | sh
cd wekan_directory
meteor

În joi, 12 iul. 2018 la 10:40, biji <notifications@github.com> a scris:

**Comment by biji** [comment] 2018-07-12 10:32
No issue on local machine, it seem docker build not using latest source. Docker auto build should be fixed to prevent false issue like this

![image](https://user-images.githubusercontent.com/665559/42627923-ace6467c-85f8-11e8-8d8a-b92fc676e0af.png)

**Comment by Akuket** [comment] 2018-07-12 13:02
Hi, I have built the application with meteor and the source code from github.com/wekan/wekan. Meteor says to me that the application is running at http://127.0.0.1 but when I go there, I have only the Nginx's welcome page. Must I make a special configuration for Nginx? It's the first time I use it.

**Comment by TNick** [comment] 2018-07-12 15:29
Hey, @Akuket .
Please open a separate issue for your question so others with same problem can find it easier.

Thanks.

**Comment by TNick** [comment] 2018-07-12 15:31
@biji @xet7 I think that we can close this issue.

**Comment by GuiGuiSoft** [comment] 2018-07-12 17:42
@biji : what is the Wekan Version displayed in your local docker version ?

On my installation (snap), it is 1.18 and I have the issue
![image](https://user-images.githubusercontent.com/8069239/42649843-0d675ea2-860b-11e8-976e-96fb972a108e.png)

@TNick : so this issue could be a snap issue (if the snap does not contains the last wekan sources, like docker autobuild). I am quite lost with the versioning :thinking:

**Comment by biji** [comment] 2018-07-13 02:30
@Akuket i've add this wiki, maybe help : https://github.com/wekan/wekan/wiki/Install-from-source-without-root

**Comment by biji** [comment] 2018-07-13 02:57
after I logout and press Reload in browser, the `invitation code` disappear :question:

**Comment by Akuket** [comment] 2018-07-13 12:45
If you do `console.log(Settings.findOne());` the value is undefined. But settings are in database.

**Comment by TNick** [comment] 2018-07-14 15:10
That is because the settings are in the database on the server side; the client side does not have them, yet
The template needs to subscribe to settings inn its onCreate, I would assume. This is just a guess.
That being said disabling the feature altogether feels like defeat.

**Comment by Akuket** [comment] 2018-07-16 08:39
Ok, and what do you think about this code ?
`Template.invitationCode.onRendered(function() {
  Meteor.subscribe('setting', {
    onReady : function(){
      const setting = Settings.findOne();

      if (!setting || !setting.disableRegistration) {
        $('#invitationcode').hide();
      }

      return this.stop();
    }
  });
});`

**Comment by TNick** [comment] 2018-07-16 08:57
Or, more in line with current code style:

```javascript
Template.invitationCode.onCreated(() => {
  Meteor.subscribe('setting');
});

Template.invitationCode.onRendered(() => {
  const setting = Settings.findOne();
  if (!setting || !setting.disableRegistration) {
    $('#invitationcode').hide();
  }
});
```
But needs to be tested.

As a side thought, I recall that the recommendation is not to **change** the DOM using JQuery when working with meteor.

**Comment by biji** [comment] 2018-07-16 09:31
@Akuket patch works :+1:  tested with disableRegistration: on and off
@Akuket have you create pr?

```
Template.invitationCode.onRendered(() => {
  Meteor.subscribe('setting', {
    onReady: () => {
      const setting = Settings.findOne();

      if (!setting || !setting.disableRegistration) {
        $('#invitationcode').hide();
      }

      return this.stop();
    }
  });
});
```

**Comment by Akuket** [comment] 2018-07-16 09:41
@biji No pr for the moment.
@TNick Your way of doing things will not work. I tried before. The problem is that the request in the database is done before subscribe. It happens if you test http://localhost: 3000/sign-up. On the other hand, if you click on the button to register on the page of connection, it will work.
So if you listen to the subscribe event onReady, it will work in any case.

**Closed** 2018-07-16 11:49 UTC
