### ISSUE TITLE
Sort languages in alphabetic order and remove abbreviations for some languages

### ISSUE THREAD

**Issue by jony0008** [wekan/wekan#1002] opened 2017-04-14 02:44 UTC
Some languages are only written as abbreviations and should be written using their real name.

**Comment by GhassenRjab** [comment] 2017-06-17 20:12
The abbreviations are caused by incompatible language codes
for example "br" (Breton) is not supported by tap-i18n
and to add Norwegian language support we must specify if it is Bokmål "nb" or Nynorsk "nn" and not only "no" (caused the abbreviation).
My question is these codes need to be changed in Transifex or directly in the code base?
if directly I'll take care of them.
I'll be doing the alphabetic order in any way.

**Comment by xet7** [comment] 2017-06-17 21:30
See "Translating login screen" announcement at:
https://www.transifex.com/wekan/wekan/announcements/

**Comment by xet7** [comment] 2017-06-17 21:36
I added new announcement there, hoping that out translators add missing translations.

**Comment by xet7** [comment] 2017-06-17 21:42
Actually, I probably need to change those in Wekan code. I'll try.

**Comment by xet7** [comment] 2017-06-17 22:20
@GhassenRjab

I did not yet figure out what is the correct filename for those translation files in wekan/i18n directory. I did try bre and no-NB, but they did not work for me when building Wekan. Transifex language to Wekan language https://github.com/softwarerero/meteor-accounts-t9n/tree/master/t9n mappings are at wekan/.tx/config .

**Comment by GhassenRjab** [comment] 2017-06-18 03:07
According to this [link](https://github.com/TAPevents/tap-i18n/blob/43362c8082ecc15edd57a2594f1460569a5b67c5/lib/plugin/etcflanguage_names.js)
The filename for Norwegian (Bokmål) must be nb.i18n.json
and as you can see there is no "br" code, we need to add its support ourselves.
I'll check how to add custom languages to tap-i18n

**Comment by GhassenRjab** [comment] 2017-06-18 14:04
@xet7 I edited the link in my previous comment, I noticed it was not working.
As of the alphabetic order, I say we leave it as it is because it comes sorted by language codes by default.
I tried sorting using the names and the English names of each language but I liked any.
Here is the result of sorting using the English names :
![image](https://user-images.githubusercontent.com/6123547/27261222-a7066344-5436-11e7-9273-f18ddc041db3.png)
We show their translated names but the names using to sort are Arabic, Basque, Catalan, etc..
And here is the result of sorting using the translated names :
![image](https://user-images.githubusercontent.com/6123547/27261230-c3eceb0e-5436-11e7-83e3-ac13cd534e32.png)
All names that are not written with Latin letters are stacked at the bottom.

**Comment by xet7** [comment] 2017-06-18 15:49
@GhassenRjab

Can you add pull request of sorting using the translated names?

I'd like to try it to see how it looks.

**Comment by GhassenRjab** [comment] 2017-06-18 16:36
Done, in PR [#1070](https://github.com/wekan/wekan/pull/1070)

**Comment by xet7** [comment] 2017-06-18 22:52
@GhassenRjab 

Thanks! Looks very nice :) Merged.

**Comment by GhassenRjab** [comment] 2017-06-18 22:57
@xet7 

Good, now we need just to use the language codes that exists in the link in my previous comment to avoid having the abbreviations and this issue can be closed.

**Comment by xet7** [comment] 2017-06-18 23:16
I fixed Norsk bokmål at https://github.com/wekan/wekan/commit/2522398233d2bbcc0a27f2551ea0504ac50862fd

There is still Breton br and Spanish (Spain) es-ES that would need correct language codes.

**Comment by GhassenRjab** [comment] 2017-06-18 23:22
@xet7 

For Spanish (Spain) just use "es" code

**Comment by xet7** [comment] 2017-06-18 23:36
@GhassenRjab

I removed extra es-ES that was not used at https://github.com/wekan/wekan/commit/b98411a441585521e08e7aae0012bf7ce5d91600

**Comment by GhassenRjab** [comment] 2017-06-19 00:22
@xet7 

That leaves us with only br abbreviation. I created this PR #1071 to address the issue.

**Closed** 2017-06-19 07:06 UTC
Labels: i18n
