### ISSUE TITLE
Page not found error

### ISSUE THREAD

**Issue by nadirlc** [wekan/wekan#666] opened 2016-08-14 14:00 UTC
Hello,

We installed the latest stable release of Wekan (v0.10.1). When we click on a card it takes us to an empty page. Please see attached screenshot.
![screenshot from 2016-08-14 18 57 33](https://cloud.githubusercontent.com/assets/20923812/17649529/0a4a2068-6251-11e6-903a-106ab05e2e3e.png)

We installed Wekan on https with a sub folder url. The installation url is: https://exergoit.se/kanban. The Wekan is accessed through Apache Proxy.

When we click on a card the new url has a double slash. If I remove one slash, then the page works fine. It seems the Wekan is not correctly reading the root url.

Thanks,
Nadir Latif

**Comment by AlexanderS** [comment] 2016-08-14 14:22
Duplicate of #624.

**Comment by xet7** [comment] 2017-05-06 22:00
Afaik this is fixed already.

**Closed by xet7** 2017-05-06 22:00 UTC
