### ISSUE TITLE
Dockerhub - Build tagged releases

### ISSUE THREAD

**Issue by weaktyper** [wekan/wekan#831] opened 2017-02-10 18:09 UTC
- Build tagged releases in the dockerhub.
- Freezes the application at each tag as an image.
- This is quite easy to do under `Build Settings` in the dockerhub.

**Comment by xet7** [comment] 2017-02-11 10:57
Duplicate of https://github.com/wekan/wekan/issues/640#issuecomment-279131179

This is also on Wekan roadmap board in "Wishes to mquandalle"

Closing issue.

**Closed by xet7** 2017-02-11 10:57 UTC
