### ISSUE TITLE
Checklist item becomes unclickable (updates previous one) after card reopen

### ISSUE THREAD

**Issue by mandrakey** [wekan/wekan#900] opened 2017-03-09 07:39 UTC
I have recently discovered an issue when using the checklists. Sometimes, one of the checklist items becomes unclickable and instead the one directly above is updated. I can reproduce this issue with the following steps:

1. Create a checklist
2. Add three items ("One", "Two", "Three")
3. Delete item "Two"
4. Add another item "Four"
5. Close the card and reopen it
6. Item "Four" can't be clicked. Clicking on it updates item "Three".

I am currently using the docker image "mquandalle/wekan" from 3 days ago (tag "latest"). I have no idea which version it runs since there seems to be no version number in the UI.

**Comment by HLFH** [comment] 2017-05-03 14:16
It is a big issue. I can reproduce it.

**Comment by GhassenRjab** [comment] 2017-06-21 19:15
I can't reproduce it on Wekan 0.23

**Comment by nztqa** [comment] 2017-06-27 07:13
I can't reproduce it.
@xet7 Please close this issue

![wekan_cheklist_unclick-iloveimg-compressed](https://user-images.githubusercontent.com/22808079/27574999-53fef5d4-5b53-11e7-885e-076022a55095.gif)

**Closed** 2017-06-27 07:16 UTC
Labels: Bug, Feature:Checklists

**Comment by HLFH** [comment] 2017-06-27 12:50
Great. But I still have issues with checklists. https://github.com/wekan/wekan/issues/1090
