### ISSUE TITLE
Wekan Logo problem in admin Panel

### ISSUE THREAD

**Issue by scoubidoo** [wekan/wekan#1583] opened 2018-04-12 09:45 UTC
Hi folks,

i update my Docker App in version 0.83 
![2018-04-12 11_42_11-wekan](https://user-images.githubusercontent.com/6061954/38669507-dda40410-3e46-11e8-892e-c09de98ffb24.png)

it's a minor bug

thx for all your work

**Comment by therampagerado** [comment] 2018-04-12 09:53
It's the same for few versions in snap...

**Comment by iwkse** [comment] 2018-04-13 00:38
Exactly, this is a duplicate of this #1378
I'd probably leave the Logo on a separate div, on a top header and the header to live in a bottom header to avoid problems.

**Closed** 2018-04-17 18:36 UTC
