### ISSUE TITLE
Email configuration form has disappeared

### ISSUE THREAD

**Issue by Kels** [wekan/wekan#1790] opened 2018-07-19 12:52 UTC
## Issue

**Server Setup Information**:

* Wekan version: 1.20
* Operating System: Debian 8
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): bundle

**Problem description**:
Hello, I cannot anymore fill my smtp configuration :(
![](https://image.ibb.co/djbVYd/wekan_email.png)

Regards,

Kelson

**Comment by Chartman123** [comment] 2018-07-19 14:42
Not a bug, see this issue: https://github.com/wekan/wekan/issues/1783

Has been removed since release 1.20.

**Comment by TNick** [comment] 2018-07-20 05:12
Is there a reason for that? Beyond that it was removed because of a password issue that could have been fixed in a different way? 
Having the mail settings in UI is a good feature, IMHO. And the settings can be integrated with the environment variables in a predictable manner:

- read settings from environment
- see if there are settings in database and, if so, use those
- emit a warning if both are set.

**Comment by xet7** [comment] 2018-07-20 09:23
@TNick 

Can you add pull request that:
- restores SMTP settings in Admin Panel
- does not show STMP password visible in admin panel

**Comment by TNick** [comment] 2018-07-20 09:55
@xet7 will do, thank you, benevolent sir. 🥇

**Comment by xet7** [comment] 2018-07-20 10:04
I try to be [less evil](https://github.com/wekan/wekan/wiki/FAQ#how-to-convince-my-company-management-that-wekan-is-less-evil-than-trello).

**Comment by TNick** [comment] 2018-07-20 10:09
_Same with removing and adding back SMTP settings in Admin Panel. _

0.o 
for a moment there I was like "heeeey, wait a minute, this just happened"

_Lauri Ojansivu edited this page 6 minutes ago_

**Comment by ocdtrekkie** [comment] 2018-07-20 14:23
I fixed two typos in it. :D

**Closed** 2018-08-20 20:17 UTC
