### ISSUE TITLE
Export Board to CSV / TSV throws error

### ISSUE THREAD

**Issue by signalcodec** [wekan/wekan#3173] opened 2020-06-14 23:00 UTC
On some boards, the Export to CSV / TSV feature is throwing a very generic error in the browser of 'Couldn't Download - Server Problem'. The logs show an error reading the length of something undefined.
@brymut , are you able to help?

Logs:  

> 2020-06-10T02:58:49Z wekan.wekan[2597]: (node:4095) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
2020-06-10T02:58:49Z wekan.wekan[2597]:     at models/export.js:88:32
2020-06-10T02:58:49Z wekan.wekan[2597]:     at doCall (packages/meteorhacks_picker.js:128:14)
2020-06-10T02:58:49Z wekan.wekan[2597]:     at PickerImp._processRoute (packages/meteorhacks_picker.js:122:5)
2020-06-10T02:58:49Z wekan.wekan[2597]:     at processNextRoute (packages/meteorhacks_picker.js:90:14)
2020-06-10T02:58:49Z wekan.wekan[2597]:     at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
2020-06-10T02:58:49Z wekan.wekan[2597]:     at PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
2020-06-10T02:58:49Z wekan.wekan[2597]:     at packages/meteorhacks_picker.js:162:10
2020-06-10T02:58:49Z wekan.wekan[2597]:     at /snap/wekan/893/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
2020-06-10T02:58:49Z wekan.wekan[2597]: (node:4095) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 42)

**Comment by IamRFC1918** [comment] 2020-06-16 11:59
I have the same problem.

**Comment by signalcodec** [comment] 2020-06-17 16:47
@xet7 i see you've moved away from bounty, I'd like to put this under commercial support. Our company uses Wekan heavily and this feature is what I sold folk on. 
What feature / fix size would this fall under given you didn't originally implement the feature and @brymut has gone dark on us?

**Comment by xet7** [comment] 2020-06-17 16:55
@signalcodec 

I think it's 150€. https://wekan.team/commercial-support/

Is that error on Snap, Docker or Sandstorm?

**Comment by signalcodec** [comment] 2020-06-17 16:57
Snappy snappy snap snap 

About to go into a meeting, I'll send the money over in an hour.

**Comment by xet7** [comment] 2020-06-17 19:42
@signalcodec 

I did add a fix. Please try newest Wekan v4.16, does it work now. You can manually immediately upgrade with:
```
sudo snap refresh
```
or wait when automatic update comes.

For me, it seems that export to CSV/TSV now works on Snap and Sandstorm, but it depends does it work for you.

I'm waiting for your payment.

**Comment by marc1006** [comment] 2020-06-17 22:10
@xet7 
Why did you remove the check `if (exporter.canExport(user))`? If I understand the code correctly, we're now leaking information to users which are not authorized to view a board.

The actual problem was
`2020-06-10T02:58:49Z wekan.wekan[2597]: (node:4095) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined`

And I think this was triggered by the line: https://github.com/wekan/wekan/commit/b00db983c8506e0cdc9968e452c3c8025fc10776#diff-68dff8c7c3ebcddb9fc87d3b28e9c916R87

**Comment by marc1006** [comment] 2020-06-17 22:29
@signalcodec @IamRFC1918 
Can you please describe which fields are used on the board? Or do you know how to reproduce the issue?

**Comment by xet7** [comment] 2020-06-17 22:34
> @xet7
> Why did you remove the check `if (exporter.canExport(user))` ([b00db98#diff-68dff8c7c3ebcddb9fc87d3b28e9c916L83](https://github.com/wekan/wekan/commit/b00db983c8506e0cdc9968e452c3c8025fc10776#diff-68dff8c7c3ebcddb9fc87d3b28e9c916L83))? If I understand the code correctly, we're now leaking information to users which are not authorized to view a board.

Sorry. I will revert that, and only comment out not-working size check.

**Comment by signalcodec** [comment] 2020-06-17 23:25
Money sent on paypal, apologies for the delay, crazy day at work!
@xet7 snap refresh is reporting all snaps upto date but wekan is still sitting on 4.15
@marc1006  we're using start/due/end/label and several custom fields, I have nothing IP sensitive on the board, so I can share the json export if that would help.

**Comment by xet7** [comment] 2020-06-17 23:28
@signalcodec 

Please wait for Wekan v4.17 that I will release soon, and then test does export to CSV/TSV work.

**Comment by xet7** [comment] 2020-06-17 23:48
@signalcodec 

Actually, try first Wekan v4.16 with:
```
sudo snap refresh
```
Does export CSV work with it?

**Comment by xet7** [comment] 2020-06-17 23:50
This is because with v4.16 it did work for me on Snap and Sandstorm.

Next version v4.17 does add some checking back, so I don't know yet does it work with those checks.

**Comment by signalcodec** [comment] 2020-06-17 23:51
No sir
`2020-06-17T23:50:26Z wekan.wekan[10619]: (node:12100) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer. Received undefined
2020-06-17T23:50:26Z wekan.wekan[10619]:     at write_ (_http_outgoing.js:653:11)
2020-06-17T23:50:26Z wekan.wekan[10619]:     at ServerResponse.write (_http_outgoing.js:621:15)
2020-06-17T23:50:26Z wekan.wekan[10619]:     at models/export.js:91:9
2020-06-17T23:50:26Z wekan.wekan[10619]:     at doCall (packages/meteorhacks_picker.js:128:14)
2020-06-17T23:50:26Z wekan.wekan[10619]:     at PickerImp._processRoute (packages/meteorhacks_picker.js:122:5)
2020-06-17T23:50:26Z wekan.wekan[10619]:     at processNextRoute (packages/meteorhacks_picker.js:90:14)
2020-06-17T23:50:26Z wekan.wekan[10619]:     at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
2020-06-17T23:50:26Z wekan.wekan[10619]:     at PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
2020-06-17T23:50:26Z wekan.wekan[10619]:     at packages/meteorhacks_picker.js:162:10
2020-06-17T23:50:26Z wekan.wekan[10619]:     at /snap/wekan/909/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
2020-06-17T23:50:26Z wekan.wekan[10619]: (node:12100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)`

**Comment by xet7** [comment] 2020-06-18 00:00
@marc1006 

When I added those checks back at https://github.com/wekan/wekan/commit/afe00d02cddf016a3ccc1ed9a98a7f10d3339f26 then at Wekan v4.17 I got again error "permission denied", and downloading CSV/TSV does not work. Probably that check does something wrong.

**Comment by xet7** [comment] 2020-06-18 00:01
@marc1006 

That was when I tested Wekan v4.17 on Sandstorm. In Wekan v4.16 without those checks export to CSV/TSV does work.

**Comment by signalcodec** [comment] 2020-06-18 00:03
The export only works on certain, smaller boards.
any largeish board (like 100+ cards) doesn't export.

**Comment by xet7** [comment] 2020-06-18 00:18
@signalcodec 

You can create json export, add it to .zip file and send as email attachment to support@wekan.team

**Comment by signalcodec** [comment] 2020-06-18 00:20
Done

**Comment by brymut** [comment] 2020-06-18 05:37
Hi @signalcodec sorry, I haven't had enough time to have a look at this. Sorry about the bug.

**Comment by xet7** [comment] 2020-06-18 11:33
When looking at code, I think it does first read all of big board to variable, and then output it. It should read cards one at a time and output it as stream to browser download. I will look how to fix it, but it would be faster for @brymut to fix it if he would have time, because he is more familiar with the code.

**Comment by brymut** [comment] 2020-06-18 11:36
I can have a go at it, if I can get some test input to test with and a couple of days into the weekend.

**Comment by xet7** [comment] 2020-06-18 11:54
@brymut 

Please send email to support@wekan.team so I get your email address, and then I can send you example exported Wekan board JSON file. Thanks!

**Comment by brymut** [comment] 2020-06-18 11:59
Sent @xet7

**Comment by xet7** [comment] 2020-06-18 12:06
Thanks @brymut !!

I did send you JSON file. You can test with it export big board to CSV, and import that big CSV back to Wekan.

**Comment by xet7** [comment] 2020-06-18 13:25
When I removed [that canExport check](https://github.com/wekan/wekan/issues/3173#issuecomment-645652771) , exporting to CSV started to work on Sandstorm in Wekan v4.16 for a small board. Before it, it got permission denied. It would need some checking that those that have export to CSV (or TSV) option visible, are also allowed to export those boards they are member of.

But, if that export to CSV works with Snap, then it's possible that it's a Sandstorm-specific bug in user permissions. At Sandstorm I did previously enable multiple boards to fix board not found error, and I have not yet fixed Wekan so that all users inside grain would be members of all boards, and that there would be possibility to manage members somehow inside grain. There are some other issues about this.

If @brymut gets import/export CSV working for big files in Snap, I can look at Sandstorm permissions.

@ocdtrekkie probably can remind me where to look at for Sandstorm specific user permissions, and on what other issues permissions have been discussed at.

**Comment by signalcodec** [comment] 2020-06-25 19:52
@brymut 
I hate to bump an issue, but do you have any updates?

**Comment by IamRFC1918** [comment] 2020-07-03 11:43
any updates on this issue?

**Comment by xet7** [comment] 2020-07-03 11:54
@IamRFC1918 

I will wait does @brymut answer something at this weekend, but if not, I'll try to fix this.

**Comment by signalcodec** [comment] 2020-07-10 03:28
I think @brymut has bailed. 

@xet7 I think all our eggs are in your basket... metaphorically...

**Comment by xet7** [comment] 2020-07-10 09:47
@signalcodec 

Yes it seems so.

There has been about 180 contributors to Wekan, and it has also happened before that when some other contributor has implemented basic functionality to some feature, after getting bounty money (or I have paid them for their contribution) they have stopped contributing. Usually this is because they are busy with moving to live elsewhere, they are busy at work, etc, life happens.

Then there is the question, why I keep continuing maintaining Wekan. Originally at 2016-12 I started maintaining Wekan because I used Wekan myself, scratching my own itch. For one year I maintained Wekan as a hobby. Wekan users have encouraged me to continue countless of times, like can be seen from [Testimonials](https://wekan.team/testimonials/). After one year of maintaining Wekan, because community asked, I added bounties and [Commercial Support](https://wekan.team/commercial-support), and currently progress of [Getting away from BountySource](https://github.com/wekan/wekan/issues/3177) is mostly finished, only some issues have not yet moved away from BountySource.

I do Watch (GitHub feature) all Wekan repos, so I get emails for every new issue, issue comment, pull request etc. From those I get to know what Wekan Community would like to have, does some feature/fix work, what could be improved, what should be changed, etc. I don't know what are everyone's use cases, so I continue because of all that encouragement, feedback, support etc. I still use Wekan myself for my own boards, keeping a lot of notes in cards.

**Comment by OpaqueArc** [comment] 2020-07-21 09:09
@xet7 
As of 4.20 (935)version now, I can confirm that all 4 export methods does not work on my wekan instance(deployed via snap)
Either a large board with hundreds of cards, or a small board of 3 cards yields the same results

Export to json: outputs a 0kb file
Export to csv/tsv: outputs a 16Kb file says"Permission Error"
Export to HTML: does nothing other than reloading the page

I kept `snap logs -f wekan.wekan` when I test through the 4 export methods above, none generated new logs
I can help with testing if needed

**Comment by xet7** [comment] 2020-07-21 17:35
@OpaqueArc 

Yes, because I had to add [Microsoft Legacy Edge browser support to Wekan](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v419-2020-07-18-wekan-release) first. That removed `csv-stringify` package was not compatible with Edge.

I will code export features by using a different way, that is compatible with browsers.

**Comment by papimla** [comment] 2020-07-23 05:11
The [board export API always returns zero bytes](https://github.com/wekan/wekan/issues/3219) was merged into this one but there are no errors in the logs. As of today's 4.21-1-g68391a9 snap, the bug is still present.

```
(eǝ) debian@website-host:~$ sudo snap set wekan debug='true'
 (eǝ) debian@website-host:~$ sudo snap logs -f wekan.wekan
2020-07-23T05:07:26Z wekan.wekan[29305]: LOGOUT_IN= (default value)
2020-07-23T05:07:26Z wekan.wekan[29305]: LOGOUT_ON_HOURS= (default value)
2020-07-23T05:07:27Z wekan.wekan[29305]: LOGOUT_ON_MINUTES= (default value)
2020-07-23T05:07:27Z wekan.wekan[29305]: DEFAULT_AUTHENTICATION_METHOD= (default value)
2020-07-23T05:07:27Z wekan.wekan[29305]: ATTACHMENTS_STORE_PATH= (default value)
2020-07-23T05:07:27Z wekan.wekan[29305]: SCROLLINERTIA=auto (default value)
2020-07-23T05:07:27Z wekan.wekan[29305]: error: error running snapctl: get which option?
2020-07-23T05:07:27Z wekan.wekan[29305]: SCROLLAMOUNT= (default value)
2020-07-23T05:07:27Z wekan.wekan[29305]: PASSWORD_LOGIN_ENABLED=true (default value)
2020-07-23T05:07:27Z wekan.wekan[29305]: MONGO_URL=mongodb://127.0.0.1:27019/wekan
2020-07-23T05:07:36Z wekan.wekan[29305]: Presence started serverId=FF3Z9gQdsjZBPfMF3
2020-07-23T05:07:40Z wekan.wekan[29305]: Meteor APM: completed instrumenting the app
2020-07-23T05:07:42Z wekan.wekan[29305]: {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Thu Jul 23 2020 05:07:41 GMT+0000 (Coordinated Universal Time)","time":{"$date":1595480862179},"level":"info"}
```

This is a blocker, scripts based on board exports are broken because of this bug.

**Comment by xet7** [comment] 2020-07-23 08:17
@papimla 

Yes, new Wekan release with fix for JSON export will come sometime today or tomorrow.

**Comment by xet7** [comment] 2020-07-23 11:36
Problem currently is, that with export fixes, EdgeHTML (Microsoft Legacy Edge browser) does not load Wekan webpage. There are no errors in Chrome. And when I try to start Edge developer tools, developer tools do not open. Someone could test this docker image:
```
image: quay.io/wekan/wekan
```
using docker-compose.yml from https://github.com/wekan/wekan

I did try that pull request that is at https://github.com/adaltas/node-csv-stringify/pulls , it did not fix it. There are some issues at https://github.com/adaltas/node-csv-stringify/issues .

On that docker image above, all export options do work, at least for small boards. But I would like to not break EdgeHTML support, because then my Microsoft Store app on Windows 10 desktop would not open at all, because it requires EdgeHTML support.

**Comment by papimla** [comment] 2020-07-23 23:40
I confirm that export does work with wekan 4.22 on a ~300KB board and a ~800KB board (JSON output size).

Thanks for the quick fix :+1:

**Comment by xet7** [comment] 2020-07-24 09:31
I will most likely use some other csv package than node-csv-stingify, like for example papaparse, or some other. Adding papaparse as Wekan dependency did not prevent EdgeHTML working, so I'll try adding code that uses papaparse for csv export.

**Comment by signalcodec** [comment] 2020-08-02 02:50
@xet7 i hate to bug; i was wondering if you had a timeline for this?

**Comment by xet7** [comment] 2020-08-02 05:49
@signalcodec 

I updated [Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license). I'm thinking of fixing bugs first.

**Comment by signalcodec** [comment] 2020-08-03 15:30
.... i'm so fired

**Comment by xet7** [comment] 2020-08-03 15:56
To be more specific, I'm currently looking at CSV code and figuring out how it works, to fix it.

**Comment by signalcodec** [comment] 2020-08-03 16:05
i commended before i looked at your roadmap, then deleted my comment.

you're a lifesaver. I shall name my first born after you

"xet7" has a nice ring to it...

**Comment by xet7** [comment] 2020-08-07 14:59
After couple of days of helping friends, I finally got back to keyboard and can spend some quality time continuing fixing this. I will add comments to this as I get more progress.

**Comment by xet7** [comment] 2020-08-19 11:54
Note to myself. TODO: Also fix Sandstorm all export options.

**Comment by signalcodec** [comment] 2020-09-17 14:12
I hate to be 'that bitch' but is there any ETA on this?

**Comment by xet7** [comment] 2020-09-17 17:02
Hmm? Maybe sometime during this month.

**Comment by xet7** [comment] 2020-09-28 14:32
## Status

- [ ] Added back code that previously did import/export CSV
- [ ] In Progress: It seems not all fields are imported back, adding more fields to import
- [ ] Changing code so that it works in MS Legacy Edge, so it keeps working on PWA. Or alternatively, waiting for a) MS to create possibility to have Credge based PWA possibility for MS Store on Win10, or b) MS to push Credge to everyone.

**Comment by xet7** [comment] 2020-10-20 14:16
When looking at CSV export code that was added by that another Wekan contributor, it seems that he added new package `csv-stringify` that is not compatible with MS Legacy Edge.

That `csv-stringify` converts Javascript array to CSV string.

But, Wekan already has other CSV package [PapaParse](https://www.papaparse.com), that works with Edge, and seems to work like this for the same purpose:
```
const Papa = require('papaparse');

let input = [ [ '1', '2', '3', '4' ], [ 'a', 'b', 'c', 'd' ] ];

let result = Papa.unparse(input, config);

console.log(result);
```
So when I run it with node:
```
$ node papa.js
1,2,3,4
a,b,c,d
```
Currently I'm looking at PapaParse streaming, so that I could stream big CSV files to be downloaded. Although, currently Wekan JSON export works for big boards, so I don't know how necessary it is, but anyway.

**Comment by xet7** [comment] 2020-10-20 21:25
@signalcodec @IamRFC1918 @OpaqueArc @papimla 

Please try newest Wekan, it has export to CSV/TSV etc at:
Board right hamburger menu / cog icon at right side of Members, Board Settings / Export.

**Comment by papimla** [comment] 2020-10-21 05:13
Hi,

Thanks for the work and for notifying us!

I tried it on a simple board and it works :-) I tried it on a board with custom fields and more cards and it does nothing from the web interface. 

Cheers

**Comment by signalcodec** [comment] 2020-10-21 15:28
I'm getting a different result

Both large and small boards with custom fields are working for me (i could kiss @xet7)

The only teeny tiny hiccup i'm getting is that for some odd reason excel isn't recognizing the comma's in the CSV correctly, it's literally doing a line and seperating the values with comma's but not into columns.

**Comment by signalcodec** [comment] 2020-10-21 15:47
ohhhhh i think i figured out why. I have comma's in some of my descriptions and it. has. caused. chaos.

**Comment by xet7** [comment] 2020-10-21 15:47
Currently that array to CSV converting code has these settings:
https://github.com/wekan/wekan/blob/master/models/exporter.js#L196-L223

There are these column headers:
https://github.com/wekan/wekan/blob/master/models/exporter.js#L229-L249

I push those headers to array here. I could be that amount of columns in header does not match amount of columns in other rows:
https://github.com/wekan/wekan/blob/master/models/exporter.js#L277

Then in loop I push all other cards to the same array:
https://github.com/wekan/wekan/blob/master/models/exporter.js#L405

Then I convert whole array to CSV:
https://github.com/wekan/wekan/blob/master/models/exporter.js#L408

In that exported CSV there could be seen where some quoting, amount of columns, spaces, or something similar is not like it should be. It could be also compared to similar spreadsheet that created with text, numbers etc originally at spreadsheet (like Excel or LibreOffice Calc) to CSV/TSV file, and then checking that it's possible to import that CSV/TSV file back to spreadsheet.

I do also have problems with LibreOffice Calc not detecting CSV correctly.

Currently that CSV export does not use any kind of streaming for bigger files. Basically currently it:
- [Does normal JSON export](https://github.com/wekan/wekan/blob/master/models/exporter.js#L192)
- Does some changes for CSV/TSV
- With only option of delimiter, runs that export [storing it to body variable](https://github.com/wekan/wekan/blob/master/models/export.js#L82-L92)
- And then [writes it to browser](https://github.com/wekan/wekan/blob/master/models/export.js#L91)

**Comment by xet7** [comment] 2020-10-21 15:51
For streaming big files, it would be possible to use [PapaParse step](https://github.com/mholt/PapaParse/blob/master/tests/test-cases.js#L1928-L1950)

For Wekan data, when it has comma, that comma should be escaped someway so that spreadsheet can accept importing that comma correctly.

**Comment by xet7** [comment] 2020-10-21 19:18
Wow, I tried many different ways to have those commas be escaped, and it seems PapaParse different settings did not work. Well, I will try again later, and if PapaParse does not work, I'll just create that CSV with plain Javascript.

**Comment by xet7** [comment] 2020-10-21 19:20
Usually commas should be escaped like `\,`. Although, I don't know does it make sense to fight with commas. Maybe tab separated as the only option would be better.

**Comment by xet7** [comment] 2020-10-21 19:21
Tab separated like `\t` or `\\t`.

**Comment by signalcodec** [comment] 2021-02-12 16:20
The error is back with the latest build

**Comment by xet7** [comment] 2021-02-12 19:23
@signalcodec 

What error?

Do you know how comma etc characters could be escaped in CSV/TSV file?

Have you tried Export to Excel ? It works better than Export to CSV/TSV. I will are more fields to be exported.

**Comment by signalcodec** [comment] 2021-02-12 19:46
Sorry, i was vague.

It's an error downloading, just chrome / edge saying there's a server error and that the download failed.

I'm not sure I have an answer to your second question.

And I have tried Exporting to Excel, we LOVE it. However, it doesn't include custom fields right now and we have deliverables that rely on us including the custom fields in our export.
If all the fields are exported in the excel export we'd be overjoyed.
I'd wet myself with joy!

**Comment by signalcodec** [comment] 2021-03-10 17:53
Okay, I managed to get in and read the error on the server side

`2021-03-10T17:50:04Z wekan.wekan[31239]: (node:32195) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
2021-03-10T17:50:04Z wekan.wekan[31239]:     at models/exporter.js:382:32
2021-03-10T17:50:04Z wekan.wekan[31239]:     at Array.forEach (<anonymous>)
2021-03-10T17:50:04Z wekan.wekan[31239]:     at models/exporter.js:372:25
2021-03-10T17:50:04Z wekan.wekan[31239]:     at Array.forEach (<anonymous>)
2021-03-10T17:50:04Z wekan.wekan[31239]:     at Exporter.buildCsv (models/exporter.js:302:18)
2021-03-10T17:50:04Z wekan.wekan[31239]:     at models/export.js:86:18
2021-03-10T17:50:04Z wekan.wekan[31239]:     at doCall (packages/meteorhacks_picker.js:128:14)
2021-03-10T17:50:04Z wekan.wekan[31239]:     at PickerImp._processRoute (packages/meteorhacks_picker.js:122:5)
2021-03-10T17:50:04Z wekan.wekan[31239]:     at processNextRoute (packages/meteorhacks_picker.js:90:14)
2021-03-10T17:50:04Z wekan.wekan[31239]:     at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
2021-03-10T17:50:04Z wekan.wekan[31239]:     at PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
2021-03-10T17:50:04Z wekan.wekan[31239]:     at packages/meteorhacks_picker.js:162:10
2021-03-10T17:50:04Z wekan.wekan[31239]:     at /snap/wekan/1402/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
2021-03-10T17:50:04Z wekan.wekan[31239]: (node:32195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 187)`

Apologies if this is no help.

**Comment by kvrivers** [comment] 2022-10-31 17:45
Getting a similar error when trying to export. Was getting similar issues cited in [Issue 1289](https://github.com/wekan/wekan/issues/1289), ran the python script to clean up the database, which fixed some boards, and other boards that do not export to CSV throw the following error:

> root@SANDSTORM:/home/wekanadmin/wekan-python# snap logs wekan
> 2022-10-31T09:27:18-06:00 wekan.wekan[16559]:     at Exporter.buildCsv (models/exporter.js:267:18)
> 2022-10-31T09:27:18-06:00 wekan.wekan[16559]:     at models/export.js:201:26
> 2022-10-31T09:27:18-06:00 wekan.wekan[16559]:     at doCall (packages/meteorhacks_picker.js:128:14)
> 2022-10-31T09:27:18-06:00 wekan.wekan[16559]:     at PickerImp._processRoute (packages/meteorhacks_picker.js:122:5)
> 2022-10-31T09:27:18-06:00 wekan.wekan[16559]:     at processNextRoute (packages/meteorhacks_picker.js:90:14)
> 2022-10-31T09:27:18-06:00 wekan.wekan[16559]:     at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
> 2022-10-31T09:27:18-06:00 wekan.wekan[16559]:     at PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
> 2022-10-31T09:27:18-06:00 wekan.wekan[16559]:     at packages/meteorhacks_picker.js:162:10
> 2022-10-31T09:27:18-06:00 wekan.wekan[16559]:     at /snap/wekan/1998/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
> 2022-10-31T09:27:18-06:00 wekan.wekan[16559]: (node:18219) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)

Is there any update on this bug?

**Closed** 2023-11-21 22:12 UTC
Labels: Bug, Feature:Import-export-sync
