### ISSUE TITLE
Uncaught Error: language zh does not exist

### ISSUE THREAD

**Issue by willin** [wekan/wekan#1026] opened 2017-05-04 16:27 UTC
like #681 

```
Uncaught Error: language zh does not exist
    at Function.e.setLanguage (1733d26….js?meteor_js_resource=true:190)
    at 1733d26….js?meteor_js_resource=true:307
    at e.Computation._compute (1733d26….js?meteor_js_resource=true:35)
    at new e.Computation (1733d26….js?meteor_js_resource=true:35)
    at Object.e.autorun (1733d26….js?meteor_js_resource=true:35)
    at 1733d26….js?meteor_js_resource=true:307
    at a (1733d26….js?meteor_js_resource=true:3)
    at HTMLDocument.u (1733d26….js?meteor_js_resource=true:3)
```

latest docker production version

installed following https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-in-production

**Comment by xet7** [comment] 2017-05-04 18:07
@willin 

1) What language is it? zh_CN or zh_TW or some other?

2) Is translation for it here?
https://github.com/softwarerero/meteor-accounts-t9n/tree/master/t9n

3) What did you click to get that error?

**Comment by mo-han** [comment] 2017-05-05 02:12
@willin @xet7 

This old issue **was** solved before but somehow reappears in the lates version (0.18).
Since those releases before 0.18 (such lick 0.17, 0.16, etc) are new enough and work great, it would be a good idea to not touch v0.18.

**Comment by xet7** [comment] 2017-05-05 19:25
Fixed by 6c26dad562cc50046c81bf9fedeb8b0923ff4827 (sorry, forgot to mention in commit message).

Reopen this if it still happens.

Closing issue.

**Comment by xet7** [comment] 2017-05-05 22:48
That code prevented changing language, so I had to revert it. So this could be still broken, but I don't know how to reproduce that error without step by step instructions.

**Comment by mo-han** [comment] 2017-05-21 03:44
@xet7 
No specific steps. Just install from official binary, run it, and access it through a browser with language set to zh-CN.

**Comment by xet7** [comment] 2017-05-21 13:02
@mo-han @willin 

Please test today's new release v0.23, does this still happen?

I was unable to reproduce this error with it with v0.23.

**Comment by xet7** [comment] 2017-06-02 14:46
If this still happens, please reopen issue.

**Closed by xet7** 2017-06-02 14:46 UTC
Labels: i18n
