### ISSUE TITLE
wekan Docker Image results in MongoError: database name must be a string

### ISSUE THREAD

**Issue by mlechner** [wekan/wekan#2846] opened 2019-12-10 11:22 UTC
When trying to get wekan running on Doxcker as described on https://github.com/wekan/wekan/wiki/Docker I get an error within the Container:
`/build/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^

MongoError: database name must be a string
    at Function.create (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:43:12)
    at validateDatabaseName (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/db_ops.js:720:22)
    at new Db (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/db.js:182:3)
    at MongoClient.db (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:237:14)
    at packages/mongo/mongo_driver.js:186:25
    at runWithEnvironment (packages/meteor.js:1286:24)
`
Tried images from quay.io/wekan/wekan and wekanteam/wekan (@dockerhub)

**Comment by RaraAvis8** [comment] 2020-05-18 16:16
I've encountered exactly the same issue.

I have Wekan running inside of Docker container with Traefik for SSL. It is configured using `docker-compose.yml` file. 

The image I used initially was `wekanteam/wekan:v2.01`. I've tried to update to `wekanteam/wekan:v4.03`. I've updated `docker-compose.yml` and then `docker-compose stop`/`pull`/`up -d`. But when container has started I was not able to login. I was getting `Login forbidden` message all the time.

I've searched issues and documentation but found no solution. (Most possible root cause was the incorrect `root_url` settings but it was correct in my case. It was set initially `ROOT_URL=https://wekan.mydomain.com` and worked earlier without issues.)

So I decided to update image gradually stepping by ~10 versions. I successfully updated to `wekanteam/wekan:v2.92`. But update to v3.00 doesn't work. Inside container I see exactly the same error - "database name must be a string".

I've updated version farther up to v3.91 and the error still here. But as I've mention with v4.03 there is no such error during startup. (I haven't checked versions in between.)

I had a look at up to date user manual and noticed that `MONGO_URL` looks differently than in mine `docker-compose` file.

Mine is:

>  - MONGO_URL=mongodb://db

(here `db` is a link to `wekandb`)

Official (https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml):

> - MONGO_URL=mongodb://wekandb:27017/wekan

So I've tried to change mine to the recommended value. With version 3.00 it fixes the problem with "database must be a string" and with startup. But error with "Login forbidden" still not allow to use Wekan.

I've also tried to change MONGO_URL in v2.92 and it starts but in this case I get "Login forbidden".

I'm not sure were to move from here. It looks like "Login forbidden" issue could appear when connection to DB is successful data about users is not found? Has its location changed somewhere in between 2.92 and 3.00? What is this `/wekan` last part of URL?

@xet7 Maybe you could suggest something here?

My `docker-compose.yml`:
```version: '3'

services:
  wekan:
    image: wekanteam/wekan:v2.92
    links:
      - wekandb:db
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://db
      - ROOT_URL=https://wekan.mydomain.com
    networks:
      - internal
      - traefik-proxy
    labels:
      - traefik.backend=wekan
      - traefik.frontend.rule=Host:wekan.mydomain.com
      - traefik.port=8080
      - traefik.docker.network=traefik-proxy
    depends_on:
      - wekandb

  wekandb:
    image: mongo:3.2
    volumes:
      - ./mongodb:/data/db
    labels:
      - traefik.enable=false
    networks:
      - internal

networks:
  traefik-proxy:
    external: true
  internal:
    external: false
```

**Comment by RaraAvis8** [comment] 2020-05-18 16:58
Okay. I've found it in MongoDB documentation: https://docs.mongodb.com/manual/reference/connection-string/

This last `/wekan` part in `MONGO_URL` is `defaultauthdb`. If it is not specified it falls back to `admin`.

I've explicitly specified it in my `MONGO_URL`:

```
- MONGO_URL=mongodb://wekandb:27017/admin
```
After this I was able to update up to v4.03.

Maybe it worth to mention in some update guide. I not sure were is the best place for this information.

**Comment by RaraAvis8** [comment] 2020-05-18 17:35
It looks like I cannot change wiki pages in project. 
Here https://github.com/wekan/wekan/wiki/Docker if we change part of the command:
```
-e "MONGO_URL=mongodb://db"
```
to
```
-e "MONGO_URL=mongodb://wekandb:27017/wekan"
```
then manual Docker startup that is described at the page should start working.
It is also make sense to add to this page if someone is updating from pre v2.92, the parameter should be as following:
```
-e "MONGO_URL=mongodb://db/admin"
```

**Comment by xet7** [comment] 2020-05-18 19:55
Newest docker-compose.yml with included comments and documentation is already at https://github.com/wekan/wekan

**Comment by RaraAvis8** [comment] 2020-05-18 20:13
Why to write on wiki page

> Note: Currently these Docker command examples do not work, help welcome

if help is not welcome? :disappointed:

**Comment by xet7** [comment] 2020-05-19 09:56
@RaraAvis8 

Sorry that I closed this in accident.

Thanks! I will test does it work.

**Comment by xet7** [comment] 2020-05-19 10:00
Sometimes I have not drinked enough coffee and don't think enough what to answer to issues or when to close them.

**Comment by xet7** [comment] 2020-05-19 11:15
@RaraAvis8 

Did you get Wekan running with Docker commands? I tried, this, and it did not work:
```
docker run -d --restart=always --name wekan-db mongo

docker run -d --restart=always --name wekan --link "wekan-db:db" -e "WITH_API=true" -e "MONGO_URL=mongodb://wekandb:27017/wekan" -e "ROOT_URL=http://localhost:3000" -p 3000:8080 wekanteam/wekan
```
Maybe there is some error in syntax?

**Comment by RaraAvis8** [comment] 2020-05-19 14:48
There is a typo in `MONGO_URL`. It should be either
```
MONGO_URL=mongodb://wekan-db:27017/wekan
```
or
```
MONGO_URL=mongodb://db:27017/wekan
```
After the change Wekan starts successfully on my PC.

**Comment by RaraAvis8** [comment] 2020-05-19 14:55
@xet7 Regarding the closed issue - no problem. Partially it was my fault - I wrote too much at once :-)

**Closed** 2021-02-20 00:54 UTC
Labels: Bug
