### ISSUE TITLE
No vertical scroll within Sandstorm iframe

### ISSUE THREAD

**Issue by yusf** [wekan/wekan#560] opened 2016-03-29 10:16 UTC
When I'm in Sandstorm, I'm unable to scroll vertically past my screen height in lists that are longer than the screen. The scrollbar doesn't even appear.

If I open the iframe content in a new tab however, it works.

OS X 10.10.5, FF 45.0.1

**Comment by zeigerpuppy** [comment] 2016-04-08 03:48
I can confirm this, it certainly causes some issues with usability, 
OS  X 10.9.5, FF 45.0.1

**Comment by zeigerpuppy** [comment] 2016-04-08 03:48
I can confirm this, it certainly causes some issues with usability, 
OS  X 10.9.5, FF 45.0.1

**Comment by jinnko** [comment] 2016-05-14 21:27
Confirmed it's still an issue on FF46.0.1.

In Safari it appears to work, but Safari keeps reloading the page for some reason so it's not usable.

In Chrome it works.

Would be good if it worked in at least Firefox too.

**Comment by dlavati** [comment] 2017-03-05 12:54
Confirmed on FF 51 on Win10.
After reloading or opening oasis in a new tab, it worked again, but could not reproduce.

**Comment by xet7** [comment] 2017-03-05 13:51
@dwrensha 

Is this Sandstorm or Wekan bug?

**Comment by xet7** [comment] 2017-09-01 20:40
This is fixed on newest Wekan for Sandstorm.

**Closed by xet7** 2017-09-01 20:40 UTC
Labels: Contribute:Pull-requests-encouraged, Targets:Sandstorm
