### ISSUE TITLE
Excessive CPU usage

### ISSUE THREAD

**Issue by Couby** [wekan/wekan#718] opened 2016-10-25 19:28 UTC
Hi,

I'm running a Wekan dedicated CT on a proxmox server.
With 512MiB RAM and 1 CPU as ressources for the CT.

I notice the CT CPU load is nearly 100% permanently.
For the server it represents 50% of its load (56% -> 6% when shutting down the Wekan CT).

It works but I don't think it is a normal load for the server, and it seems to slow down my other services.

Is it related to my installation or can it be confirmed by some other wekan admins ?

Regards.

**Comment by bevinhex** [comment] 2017-01-11 05:18
Got the same issue here, First got https://github.com/wekan/wekan/issues/245 issue, solved by following the solution in the thread, But after solving the error, CPU still takes up 100%

**Comment by robert-scheck** [comment] 2017-03-09 14:58
Same issue here, the excessive CPU usage seems to start when using Wekan the first time via web interface (nearly no CPU usage between starting and first usage).

Hardware resources do not seem to make a considerable difference when looking @Couby's post, affected environment here has 2x 2.8 GHz vCPU and 4 GB RAM, while Wekan simply consumes one vCPU with 100% CPU usage and 45.3% of memory (according to `top` and `ps aux`).

**Comment by xet7** [comment] 2017-03-12 15:15
@maulal 

Do you have idea how to fix this?

**Comment by maulal** [comment] 2017-03-13 07:58
Hi, it's certainly a matter of indexes, i need to know the version of wekan and mongodb your working on?

Don't hesitate to check if you have the indexes related to  #837 in your database.

**Comment by maulal** [comment] 2017-03-14 20:13
@bevinhex and @robert-scheck ? any news ?

**Comment by bevinhex** [comment] 2017-03-16 10:50
I also saw some logs about some node modules is installing something that is irrelivant from 'baidu', so could not trust it much (maybe I'm being parenoid)
end up using https://taskboard.matthewross.me/ instead

**Comment by robert-scheck** [comment] 2017-03-16 11:27
@maulal, the affected environment here has Wekan 0.11.1-rc1 and MongoDB 2.6.12

**Comment by maulal** [comment] 2017-03-16 13:21
@robert-scheck ok, in this version, some indexes were missing. Take the last released version (v0.16), it should be good.

**Comment by AlexKornitzer** [comment] 2017-03-22 18:06
Our system is running at 100% CPU all the time on CentOS 7: Wekan 0.16 (Release Build) and MongoDB 2.6.12. Are there any logs we can provide to help diagnose the issue?

**Comment by maulal** [comment] 2017-03-23 07:58
@AlexKornitzer 
At least let's say the cpu consumption for each processes (during 5min).
In mongodb by default, slow queries (>100ms) are logged, you can check that point.

**Comment by AlexKornitzer** [comment] 2017-03-23 15:18
I believe that the issue is due to Wekan or its node libraries and not mongo. If I restart the wekan service CPU is under 1%, but as soon as a client connects to the service the CPU jumps to 100% where it stays even once the client has disconnected. Our number of entries within the DB is small and I have even tried with a clean database.

We are running the service behind an nginx SSL reverse proxy so I am not sure if this could be the issue. I also get a websockets error reported in firefox, could it be that on a failed websocket connection it tries to reconnect endlessly? Similar to this? https://github.com/node-apn/node-apn/issues/180

Running tcpdump I can see that even on a disconnect from the client the server continues to send a packet every 10 seconds to the client.

**Comment by AlexKornitzer** [comment] 2017-04-10 14:32
Found the source of my issue, now using meteor's node.

`/opt/meteor/meteor node ...`

Source: https://forums.meteor.com/t/meteor-bundle-on-production-100-cpu/30837/40

**Comment by denysvitali** [comment] 2017-04-14 12:23
We noticed the same thing on our server. 100% of CPU.

![wekan-wtf](https://cloud.githubusercontent.com/assets/4939519/25043132/f7504b68-211d-11e7-9e7e-627050a27a61.png)

Seriously... WTF?!!!!

**Comment by AlexKornitzer** [comment] 2017-04-14 12:26
Yeah it's a meteor thing, not sure why their framework is not node version agnostic.

**Comment by xavierpriour** [comment] 2017-04-27 22:38
Hi, same problem here with the official docker recommended in the doc (`wekanteam/wekan:meteor-1.4`).
It uses node v6.10.2, whereas meteor 1.4 supports node 4.8 only.

I'll be happy to try and submit a PR, if you can just point me to the part of the repo where the docker builds are defined.

**Comment by xet7** [comment] 2017-04-28 00:36
Node version has been changed yesterday:
https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-from-source
https://github.com/wekan/wekan/blob/devel/Dockerfile
https://github.com/wekan/wekan/blob/master/Dockerfile

A moment ago I merged Dockerfile fixes:
https://github.com/wekan/wekan/pull/1016

Also see other changes:
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md

If you notice there's changes needed elsewhere, please change it or add comment to this issue.

**Comment by xet7** [comment] 2017-04-28 00:40
There will probably be more Dockerfile fixes in near future to get it working properly.

Installing from source works correctly though.

**Comment by stephenmoloney** [comment] 2017-04-28 10:06
I didn't see this issue. I wasn't aware that meteor only supports node v4. Hopefully, the latest version change fixes it. The latest build includes node v4.8.1

**Comment by xavierpriour** [comment] 2017-04-28 17:06
I confirm issue is solved, afaik you can close the issue, thanks again @xet7

**Comment by Madko** [comment] 2017-06-08 08:13
Same here, how to get the fix ?

**Comment by xet7** [comment] 2017-06-08 08:38
@Madko 

For example Github Wiki platforms page, docker-compose wekan-mongodb. What did you use to install wekan?

**Comment by AlexKornitzer** [comment] 2017-06-08 10:11
If you are using the release bundle or source, then I find that the easiest way is to install the matching meteor version and run the meteor node: `/opt/meteor/meteor node <PATH_TO_WEKAN>/build/bundle/main.js`

**Comment by Madko** [comment] 2017-06-08 12:10
@xet7 it's a manual install on CentOS 7.

@AlexKornitzer will try to find out more about meteor

**Comment by Madko** [comment] 2017-06-08 12:42
Thanks, it works with meteor (was a bit "fun" to install with their curl | sh)

**Comment by AlexKornitzer** [comment] 2017-06-08 12:45
Yeah downgrading node is not a good solution so those are the steps I took on our Centos machine. Has been running great since.

**Comment by mfshiu** [comment] 2017-12-10 16:01
Use this package is in Wekan VERY important: 

> [mixmax:smart-disconnect](https://atmospherejs.com/mixmax/smart-disconnect)

Meteor connection cost is very expensive, if your MongoDB contains large data, your active users are over several hundreds, you must use the package to auto disconnect user when they leave their focus on Wekan over 1 minute. I read [the article by Eliezer Steinbock](https://medium.freecodecamp.org/scaling-meteor-a-year-on-26ee37588e4b), then make my Wekan CPU ultra down.

**Comment by xet7** [comment] 2019-12-03 22:04
mixmax:smart-connect was removed from Wekan at [Wekan v3.03](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v303-2019-08-04-wekan-release).

From that fix details:

"Remove mixmax:smart-disconnect, previously it did disconnect Wekan when browser tab was not active, but because now users are working on multiple boards at different browser tabs and switching all time time, there was constant loading, so now after removing all tabs keeps active. This can increase server CPU usage. Thanks to xet7."

Additionally, removing mixmax:smart-disconnects fixes data loss. Data loss happened, when someone changes to other tab, first tab of Wekan did not have time to sync those changes to server, and then when browser was closed, changed data was lost forever.

**Closed** 2023-02-02 20:01 UTC
