### ISSUE TITLE
On sandstorm, share link does not let users edit the board

### ISSUE THREAD

**Issue by birdsarah** [wekan/wekan#349] opened 2015-10-07 17:06 UTC
I've setup a wekan on sandstorm and shared it with some colleagues with the "can edit" setting. They are able to see the board, but they cannot add any cards themselves. 
- these are users without sandstorm.io accounts (who aren't going to have one)
- etherpad instances on sandstorm support this, if that's helpful.

**Comment by mquandalle** [comment] 2015-10-07 18:11
Hum, I didn’t realize that I forgot to implement the sharing permissions in case the sandstorm user isn’t identified. 

Wekan currently assumes that a board member at least has a name (to be displayed in the activity feed). I’m not sure what to display for unlogged users (something like “Unamed user 1”?). Also if the user edits the board in unlogged mode, and then logs in, how would I be able to reconcile the two identities? Do you have any clue @kentonv?

**Comment by kentonv** [comment] 2015-10-07 18:27
So, Sandstorm actually provides a name in X-Sandstorm-Username even for non-logged-in users. Currently that name is simply "Anonymous User", I think. Some day we might provide a more informative name based on the sharing graph -- for example if the board was shared by e-mail, we know the user's e-mail address even if they haven't logged in, and we could incorporate that into the display name. But we haven't thought much about this yet. Note that for anonymous users, Sandstorm does *not* send X-Sandstorm-User-Id, so there's no way to tell if two anonymous users are the same person. We could conceivably be able to tell if they're using the same sharing link, but that doesn't necessarily mean they are the same person (e.g. if the invite was sent to a mailing list, posted in a chat, etc.).

Unfortunately since the user isn't logged in they don't get a Meteor user entry and so getting at the headers may be hard, though it seems like you managed to do so for avatars even before I added explicit support for that to accounts-sandstorm. :)

**Comment by mquandalle** [comment] 2015-10-07 18:35
Reading a HTTP header is easy enough, don’t worry :) The difficult part is that I really rely on board members (people that can edit it) being present in the user collection. So I guess I may create a new user everytime someone fetch the grain using a share link, but that will create a lot of dead users in the collection and in the UI (members shown on the sidebar).

Maybe one other possibility would be to create one single member for all the people accessing the grain from a given link. This user would have a name (`linkName user`?) and permissions (the link permissions) and would be displayed accordingly in the sidebar and the activity feeds. Does that sound reasonable to you Kenton?

**Comment by dwrensha** [comment] 2015-10-08 15:08
I, for one, think that it's not a bad compromise to give all anonymous users read-only access. It would be really nice, though, if there were some instructions like "sign in to get write access".

**Comment by mquandalle** [comment] 2015-10-08 15:26
Yes that’s another solution, but I’m afraid it is currently not possible to have an actionable sign-in link/button to display the appropriate Sandstorm popover.

**Comment by birdsarah** [comment] 2015-10-08 16:58
Also, doesn't signing into sandstorm imply paying money, this would obviously have an impact. On etherpad, you can just temporarily rename yourself, it doesn't keep between sessions, but that's ok.

**Comment by mquandalle** [comment] 2015-10-08 17:06
I think only the grain owner have to pay for it.

**Comment by ocdtrekkie** [comment] 2015-10-08 17:29
@birdsarah Just to confirm, @mquandalle is right, it doesn't cost anything to sign into Sandstorm, or to use someone else's apps/files/grains they share with you. Signing in just identifies you as an individual and makes it possible to assign permissions to you.

Additionally, Sandstorm Oasis actually has a free tier, so users can even run their own grains for free, and, of course, self-hosters probably don't charge for anything, but you need an invite to create your own grains.

**Comment by birdsarah** [comment] 2015-10-08 17:51
Oh cool - thanks!

**Comment by radomici** [comment] 2015-10-09 03:19
What if anyone who is trying to open a Wekan grain in edit mode via sharing link is prompted for setting up a board member name before attempting to edit anything? And warned if chosen name is already taken?

**Comment by radomici** [comment] 2015-10-10 17:54
Wekan grain still opens in read only mode via sharing link and does not allow editing even after logging in to the Sandstorm's free tier account.

**Comment by dwrensha** [comment] 2015-10-10 17:56
@radomici: is it possible that you are running into #352?

**Comment by radomici** [comment] 2015-10-10 18:40
Sounds like the issue. Just for clarification: Sharing link opens the grain in read only mode. I log in into using an email different from my Sandstorm account-associated email (just like any person that I'm sharing the link with would do in order to gain write access). But the board still does not allow modification or adding a member.
BTW: different issue. Just found the deleting card does not work. I click on delete and nothing happens, a card is still there.

**Comment by larjona** [comment] 2015-10-24 20:22
In my experience, sharing wekan with edit capabilities only works for logged in users with "invited user" permissions. I'm experiencing this issue and unrelated to #352 

Steps to reproduce:
1.- Install wekan in your sandstorm.io box
2.- Open a new wekan board
3.- Add some lists and cards
4.- Go to Share -> Get a shareable link, drop down the type of link to select "CAN EDIT".
5.- Log out
6.- Access the wekan board using the shareable link you copied in step 4.
7.- You are able to see the board, but you cannot add/delete lists nor cards
8.- log in as a new user
9.- You got the same behaviour
10.- Log out
11.- Log in as admin
12.- Go to Admin settings, and change the permissions to the user that logged in in step 8, from "Guest" to "Invited user"
13.- Log out
14.- Log in as the same user that logged in in step 8.
15.- Now you can edit.

One more thing: I have two admin users in my box. When I logged in with the admin user that was not the creator of the wekan board, I could not edit either!! I didn't investigate this further, because when the main issue is fixed, this one will be fixed too, I think.

**Comment by dwrensha** [comment] 2015-10-24 21:31
@larjona: Wow, interesting find. I think you are running into this issue: https://github.com/sandstorm-io/sandstorm/issues/1076, which I just filed.  A user's "invited" status should not be visible to grains at all. My theory is that your new user just needed to refresh the page in order to be able to edit.

**Comment by larjona** [comment] 2015-10-24 21:51
Thanks  @dwrensha. Definitely, you are true and it's the issue #1076 , because I am using email tokens to log in. I set the user permissions again to "Guest" and wekan allowed editions, and I also tried to reproduce the issue and reload the page as you suggested, and after reload I was able to edit.
The admin user also was able to edit after reload.
Thanks!

**Comment by radomici** [comment] 2015-11-07 06:21
Is this sharing issue already fixed? I still can't edit wekan board via the shareable link. I tried to follow larjona's stept but I don't know what/where is Admin Settings from step 12.

**Comment by larjona** [comment] 2015-11-07 21:32
@randomici You have to be an Admin in sandstorm.io to access that menu option. It's on the top-right corner of your sandstorm.io window: when you are not signed in sandstorm.io, it says "Sign in"; after you sign in, it changes to your name or id. When you click there, it drops down to "Account settings", "logout", and other options (and if you are an admin, "Admin settings").

**Comment by radomici** [comment] 2015-11-10 05:12
@larjona , I don't have "Admin settings" in that menu. I'm not quite understand what that admin options are related to. Who is admin? I am subscribed to the Stadard sandstorm plan, should I have the "Admin settings" option? If I'm not suppose to have "Admin settings" I will never be able to share Wekan board for editing by someone else?

**Comment by larjona** [comment] 2015-11-10 05:40
@radomici You don't need Admin settings (I thought that, but I was wrong).
1.- Just share your wekan with edit capabilities.
2.- People need to sign in sandstorm.io to be able to edit (so wekan learn their names, for the cards), but they can remain as guests.
3.- If they signed in with github or google, they can edit right now.
4.- If they signed in with email token, they need to reload the page, and they can edit. <<< this is the bug that need to be fixed (force an automatic reload for users signing in with email token. I was going to Admin settings and giving them permissions, and then, the automatic reload was happening, but in fact, the permissions are not needed, just a reload of the page is needed).

Regards

**Comment by jadeqwang** [comment] 2015-11-11 19:05
Hey everyone, I encountered this issue as well. I tried to share "edit" permissions with a virtual assistant on a Wekan board, and they reported not being able to edit. So I tried out the link that I gave them with a separate account, and was unable to create new cards. I went back and checked the "See who has access" list, and sure enough, the link given to FancyHands is listed as having "edit" permissions.

So even if the new person is signed in, they can't do anything. :-/

**Comment by jadeqwang** [comment] 2015-11-11 19:43
Update: turns out I encountered that b/c I was testing with 2 accounts with the same name (my Sandstorm gmail and my personal gmail). Doh.

**Comment by mquandalle** [comment] 2015-11-11 19:47
(cf.  #352)

**Comment by mitar** [comment] 2016-04-18 22:03
> The difficult part is that I really rely on board members (people that can edit it) being present in the user collection.

Exactly this was my [long rant yesterday on Sandstorm IRC channel](https://botbot.me/freenode/sandstorm/2016-04-17/?msg=64397751&page=2). I really think that Sandstorm should just provide ephemeral uid for anonymous users, so that from the perspective of an app anonymous users look like normal users (they have name, uid, handle). So that apps can add them to the database and use them to reference them from other documents/tables. And reuse all the permission logic for normal users. The only difference is that once user closes their window, the uid is never reused again.

The app can then use normal/traditional cron job to delete inactive users (which those anonymous users would be) or handle them in any way app wants.

In this way app does not have to implement anything special. And Sandstorm handles all the life-cycle of the user. Even if user starts as an anonymous user and then decides to register, Sandstorm can remember the uid it provided for that anonymous user and link it to real user. So app again does not have to handle that in any special way. For app it is just that that uid changed name and handle. And that the app will see the uid in the future again.

Requiring apps to specially handle anonymous users is really hard and require apps to special-case Sandstorm.

**Comment by mitar** [comment] 2016-04-18 22:05
(Related: Sandstorm should also [handle that usernames are unique per grain](https://github.com/sandstorm-io/sandstorm/issues/1859).)

**Comment by kentonv** [comment] 2016-04-21 08:54
As I said on IRC, an app can easily fall back to `X-Sandstorm-Tab-Id` when there is no `X-Sandstorm-User-Id` as a way to get the effect of ephemeral users. However, not all apps want that effect, therefore we cannot just do this for everyone. It's only a line or two of code to do this in your app. I would accept a PR against accounts-sandstorm which adds the ability to enable such a mode as an option.

**Comment by mitar** [comment] 2016-04-21 08:59
`X-Sandstorm-Tab-Id` has bad usability. If somebody has grain opened in multiple browser windows/tabs they would not be the same user.

> However, not all apps want that effect, therefore we cannot just do this for everyone.

Can you please give me an example of an app which has both permission system and ignores `X-Sandstorm-User-Id`? I can understand that there are apps which simply never use `X-Sandstorm-User-Id` because all their users are anonymous (to them it will not hurt if `X-Sandstorm-User-Id` becomes available). And there are apps which currently do not support anonymous users because they otherwise have permissions and it is simply too hard to make change to support also anonymous users in a user friendly and consistent way.

So show me an app which would break if we would start supplying `X-Sandstorm-User-Id` for all users?

**Comment by kentonv** [comment] 2016-04-21 10:09
> X-Sandstorm-Tab-Id has bad usability. If somebody has grain opened in multiple browser windows/tabs they would not be the same user.

That's working as intended. Anonymous users are anonymous.

> Can you please

I'm really sorry, but I can't. We've spent a lot of time debating this point already (in other places) and I need to move on to other things.

**Comment by mitar** [comment] 2016-04-21 10:29
> That's working as intended. Anonymous users are anonymous.

But it works differently than what people expect from "private browsing" in browsers. I think that is a good user experience and it is something users are used to and understand. You are requiring from them to re-learn what means "anonymous" (private) in the browser. Re-learning is always tricky in the security settings.

I think it is amazing to have a platform which can respect "private browsing" (and do-not-track) natively. But this current implementation is not that. It goes to some strange variation of the "anonymous" I would claim no user is really asking for. I would claim users want anonymity per browsing session, not per tab. Per tab anonymity is madness. Do you do any user studies for this design decisions?

![26601725_zps4be6bcc1](https://cloud.githubusercontent.com/assets/585279/14706016/3394ecc2-0771-11e6-9f54-75d4b3d1346f.jpg)

**Comment by mquandalle** [comment] 2016-04-21 10:38
I haven’t read the whole conversation again, but in the case of Wekan-like apps that want to track what each user is doing, the app could restrict unregistered users to read-only access as proposed above https://github.com/wekan/wekan/issues/349#issuecomment-146574181. Any problem with that?

**Comment by mitar** [comment] 2016-04-21 10:43
Yes. This is what all apps which permissions will end up doing. Simply ignoring any permissions anonymous users might have. This is why this design of anonymous users fails. It tries to provide permissions for anonymous users but in practice apps will then simply not provide any permissions to those users (except read-only permissions).

**Comment by dwrensha** [comment] 2016-04-21 14:31
> Can you please give me an example of an app which has both permission system and ignores X-Sandstorm-User-Id? 

[filedrop](https://apps.sandstorm.io/app/nn7axgy3y8kvd0m1mtk3cwca34t916p5d7m4j1j2e874nuz3t8y0), [ethercalc](https://apps.sandstorm.io/app/a0n6hwm32zjsrzes8gnjg734dh6jwt7x83xdgytspe761pe2asw0), and [gitweb](https://apps.sandstorm.io/app/6va4cjamc21j0znf5h5rrgnv0rpyvh1vaxurkrgknefvj0x63ash) come to mind. There are probably others.

**Comment by zertrin** [comment] 2016-04-21 17:02
I don't really understand in which direction the solution to this issue is going, so let me explain how I expected my user experience would look like, and what happened instead:

1. I want to share a board with a relative (not computer skilled) with a share link. When doing that I make sure to select "can edit". At this point the UI reads as following "_Anyone with this link: can edit_".
2. I send the link to the other person which opens it.
3. They see the board but can't edit it.
4. They are confused, and so do I, because I was expecting someone in possession of the link to be able to edit.
5. After asking them to register to the sandstorm instance by email (which they, as not computer skilled people, struggle to achieve... Here the user experience goes suddenly to the bottom) it didn't work either.
6. We abandon --> user experience = 0

By reading this thread it seems that after the step 5 we missed reloading / logging out and in / closing the browser and restarting again / whatever else... 

But the whole point here is that we shouldn't even reach step 5. At step 3 the user in possession of the link should just be able to edit the board.

I hope that the discussion here is still focused on making the step 3 working without needing to go to step 5. [The comment](https://github.com/wekan/wekan/issues/349#issuecomment-212849320) of @mquandalle makes me worry...

**Comment by mquandalle** [comment] 2016-04-21 17:20
@zertrin What I was just saying is that for certain applications like Wekan, the user will need to be registered and logged in to make some edit—and that’s because we need to accurately associate actions to their author identity. So far that’s no different from having to create a Trello account to edit a Trello board.

On Sandstrom the authentication layer is handled by the platform, not the app, among other advantages this is a good thing because it dispense you to create new accounts for every single app you want to use. This also means that the user you want to invite on a board will have to be registered and logged into the Sandstorm host.

For this to work in term of user experience, you would have either to share by identity (in which case the relative is already registered in the host and everything works fluently), or share by link. In the latter case the UI would have to display something like “sign in/log in to edit this board” which isn’t currently implemented (@kentonv does Sandstorm now allows an app to open the login form?).

**Comment by ocdtrekkie** [comment] 2016-04-21 17:24
@mquandalle I think what's being discussed or advocated for, is that if you have a link with editing permissions, Sandstorm would allow an anonymous user to use that permission. If an app was supportive of this, only people with that link could edit anonymously.

**Comment by mitar** [comment] 2016-04-21 19:48
@dwrensha, perfect examples. Let's see:
* filedrop uses only [permissions](https://github.com/zombiezen/filedrop/blob/eb42a2254be91efb92668f70cb895d17715d7059/filedrop.go), not `uid`, so starting passing `uid`s for all users would not break anything
* ethercalc does not support Sandstorm permissions at all: https://github.com/audreyt/ethercalc/issues/146 (and will probably have the same issues as I am describing here)
* gitweb uses only [permissions](https://github.com/dwrensha/gitweb-sandstorm/blob/7e04eee0d5d9271fbaf502d7386004bd3e8fc7cc/.sandstorm/etc/nginx/nginx.conf#L19) and not uid, so nothing would break if we started offering uid to all users

So, my statement still stands: there is no app which handles permissions which registered users, and handles permissions with anonymous users. Or you have apps where all users are anonymous, or you have apps where users can be registered, but then anonymous users of those apps do not have any permissions which require database changes (maybe just reading around).

**Comment by mitar** [comment] 2016-04-21 19:55
Let me summarize discussion here, because I really wrote a lot:
* the problem is how to provide write permissions for anonymous (not-registered) Sandstorm users for apps which require UID to associate changes in the database
* Sandstorm does not provide an UID for their anonymous users
* I am claiming that it should, and just discard the UID after the session and never reuse it, so that users cannot be tracked, but that for the app it should look like a normal user, and could reuse normal permissions logic and associate that UID with changes
* @kentonv is saying that this is bad and we should instead using tabId to get unique ID for Sandstorm anonymous users
* I am saying that using tabId is bad because each browser tab during same browsing session would have then a different user and this is not something users expect from "private browsing", they should just get their UID forgotten after they close the session
* I am pointing out that current design requires from apps to do carry heavy burden to support anonymous users with write permissions and that for that fact apps will choose simply to require them to register to be able to edit, which will diminish usefulness of Sandstorm anonymous users feature

Conclusion, if Sandstorm does not change anything:
* wekan can simply require all users to be registered (anonymous users cannot use it)
* wekan can use for database ID Sandstorm tabId, but then in different browser tabs there will be different users; so if the same person open given link twice in the same browser at the same time, wekan will see it as two different users

**Comment by ocdtrekkie** [comment] 2016-04-21 20:02
@mitar That EtherCalc issue is very old. Edit and View permissions work on EtherCalc on Sandstorm. (I know this because I use them.)

As @dwrensha suggested, EtherCalc does implement permissions, but doesn't have a strong concept of user identity.

**Comment by mitar** [comment] 2016-04-21 20:06
You are right. It is not in the master branch, so I didn't find the code. So it is here:
* ethercalc, uses just [permissions](https://github.com/audreyt/ethercalc/blob/sandstorm/main.js#L446) and it would not break if we providing uid for all users

My case still holds.

**Comment by klischka** [comment] 2017-02-03 21:17
Any news on this?  I use Wekan on Sandstorm and ran into one problem: I wanted a board to be editable by anyone whom I shared the link with (a barcamp). Sandstorm supports this function, but Wekan currently requires users to be logged in in order to edit. People who visit my share link need to log in. I think support for anonymous edits would benefit some users.

**Comment by 1000i100** [comment] 2018-09-19 00:37
I also would like anonymous edits like said here : https://github.com/wefork/wekan/issues/94
and ideally, with and without sandstorm.

Perhaps a guest user can be auto-used to allow visitor to edit without login when authorship is not a problem ?

**Comment by xet7** [comment] 2021-01-12 22:46
Summary: Allow edits by anonymous users on all platforms, if there is permissions for that. Try to figure out how to generate per user id, because usually all anonymous users show as same one user id.

Moved to #3022

**Closed by xet7** 2021-01-12 22:46 UTC
Labels: Targets:Sandstorm
