### ISSUE TITLE
Cannot add member to card when webhook is enabled

### ISSUE THREAD

**Issue by miselico** [wekan/wekan#1475] opened 2018-02-09 12:15 UTC
## Issue
**Impacted version**: 0.68.0

**Server Setup Information**:  Followed https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-for-testing
* Operating System: Debian 3.16.51 (host)
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): docker
* Node Version: ?
* MongoDB Version: 3.2.14
* ROOT_URL environment variable (Is there a subfolder?): No

**Problem description**:
I wanted to try webhooks, so added a URL  to the webhook menu. Now, I did not receive any HTTP requests, so I might have done something wrong there. But, I noticed that as long as the webhook URL is set, I seem to be able to do everything on the board as usual, except adding users to cards.
After removing the URL, this becomes possible again.

**Comment by xet7** [comment] 2018-02-09 12:23
Please upgrade to newest Wekan release.

Webhooks are usually added to Rocket.Chat, slack etc. You can look at Webhook features and format in Wekan GitHub wiki Features page and Webhooks links in wiki menu.

Usually problem with webhooks is that you have some firewall blocking receiving webhooks, or some typo in webhook URL.

You can also search other Wekan GitHub open and closed issues and pull requests with word "webhook" for more information.

**Comment by miselico** [comment] 2018-02-09 15:41
And I was convinced I was running the latest version :) You have a fast-paced release cycle.

**Comment by miselico** [comment] 2018-02-09 20:41
I now upgraded to the latest version (0.73.0). I got the webhook to work, but the issue still exists:
When a webhook cannot be executed, no users can be added to the card. The question is whether: 1) the user should be notified of this failure or 2) the failure is silenced, but normal progress continues. Alternatively, an option is to not allow any modification when webhooks fail.

**Comment by GavinLilly** [comment] 2018-02-20 12:36
This looks like a duplicate of the issue I was describing in #1402

**Comment by xet7** [comment] 2018-02-20 12:54
Moved to #1402

**Closed by xet7** 2018-02-20 12:54 UTC
Labels: Bug, Feature:Webhooks

**Comment by miselico** [comment] 2018-02-20 15:41
This is a duplicate indeed.
