### ISSUE TITLE
Public board with many cards inaccessible

### ISSUE THREAD

**Issue by 0xC4N1** [wekan/wekan#2636] opened 2019-08-16 16:42 UTC
## Issue
**Server Setup Information**:

* Did you test in newest Wekan?: Tested with wekanteam/wekan:latest from 2019-08-16T03:27:42.881841071Z
sha256:628aa3e68338b9e5f69ec6175203d58703be67fa16deb3a7fdad5ee7b43b5d95
* MongoDB Version: 4.2.0

**Problem description**:
Upon accessing a public board with more than 10 cards in a list as guest or non-admin, the Wekan UI gets stuck in an endless loading loop.
![wekan-issue-public-board-not-loading](https://user-images.githubusercontent.com/7902457/63183344-0b8c2d80-c055-11e9-805c-f3b1f6b0d616.gif)
- *Explain steps how to reproduce*
 1. create 10 cards in the same list on a public board via admin session
 2. access public board as guest or non-admin user in a private browsing window
 3. create the 11th card from admin session
 4. observe that the 11th card doesn't appear in the guest session. 
 5. refresh the page in the guest session. Wekan gets stuck loading.
 6. delete a card from the admin session
 7. refresh the page in the guest session. Wekan loads successfully.

**Comment by xet7** [comment] 2019-08-16 19:12
I really don't know does Wekan with with MongoDB 4.2.0, it's development version and many things could be broken. I would think MongoDB 4.0.12 is current production version.

**Comment by 0xC4N1** [comment] 2019-08-16 19:48
Thank you for your reply! I will try mongo:4.0.12 tomorrow. However I'm not sure if that's the cause since I've also observed this issue appearing with mongo:3.2.16 and 3.2.11.

**Comment by xet7** [comment] 2019-08-16 20:06
Is there any errors in webbrowser Inspect console?

**Comment by 0xC4N1** [comment] 2019-08-18 09:34
Upon successfully loading Wekan with less than 11 cards in a list there are [5 exceptions](https://github.com/wekan/wekan/files/3512853/wekan-loading-success.log). Loading Wekan with more than 10 cards there are
[7 exceptions](https://github.com/wekan/wekan/files/3512852/wekan-loading-issue.log).

This issues keeps occurring with mongo:4.0.12. Tested with a fresh database. No further errors in the docker log. I can see the cards and boards collections being transmitted via websocket in the browsers network monitor.

**Comment by hever** [comment] 2019-08-19 09:27
Same problem as #2311?

**Comment by 0xC4N1** [comment] 2019-08-19 09:45
> Same problem as #2311?

Yes that issue seems relevant. It works with `v2.56` mentioned there.

**Comment by hever** [comment] 2019-08-19 13:52
Problem will be in this commit ... https://github.com/wekan/wekan/commit/261754f18b8a5e6e6eedf39d6f6b143a752b0588

Maybe around function spinnerInView()

**Comment by anmol26s** [comment] 2019-09-09 19:11
Some solution out there yet?

**Comment by justinr1234** [comment] 2019-09-09 19:31
@anmol26s do you have any server logs you can post?

**Comment by justinr1234** [comment] 2019-09-10 19:27
The issue is the subscription isn’t returning ready which causes infinite loading on the bordBody template. It should likely be fixed in the latest version or Wekan. The other linked issue in this list doesn’t appear to be related to this one, even though they’d seem similar.

**Comment by juliensl** [comment] 2019-09-19 14:42
Hi ! 
Same problem for me.
I got 3 more messages in my webbrowser Inspect console, if that can help : 

```
Exception from Tracker recompute function: undefined 3c7194b3621bf330aca98f6397b54075b3dba7d2.js:1:6755

Error: Must be attached undefined 3c7194b3621bf330aca98f6397b54075b3dba7d2.js:1:6755

t.prototype.firstNode@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:63:5154
e.prototype.constructView/a.templateInstance@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:63:35278
N@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:233:2969
r._getTemplateHelper/i<@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:233:4173
tracker.js/s.nonreactive@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:35:4179
r._getTemplateHelper@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:233:4143
f.View.prototype.lookup@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:63:32750
template.listHeader.js/Template.listHeader</</<@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:339:280889
f.If/</<@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:63:27962
n/</<@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:63:18999
e._withTemplateInstanceFunc@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:63:37826
n/<@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:63:18951
f._withCurrentView@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:63:23077
n@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:63:18900
_compute@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:35:2321
_recompute@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:35:2476
tracker.js/s._runFlush@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:35:3485
a@https://plan.live-for-good.org/3c7194b3621bf330aca98f6397b54075b3dba7d2.js?meteor_js_resource=true:1:3083
 undefined 3c7194b3621bf330aca98f6397b54075b3dba7d2.js:1:6755
```

I'm not sure that it's can help you :laughing:

**Comment by xet7** [comment] 2020-04-25 17:05
Try newest Wekan.

**Closed by xet7** 2020-04-25 17:05 UTC
