### ISSUE TITLE
Prevent comment only from moving cards 

### ISSUE THREAD

**Issue by adminschb01** [wekan/wekan#2951] opened 2020-03-03 15:05 UTC
thanks for this awsom tool.

this is related to issue #2941 
is there a way to prevent board members from moving cards between lists, but keeping them able to comment cards.
i tried the profile "comment only" but they still be able to move cards.
thanks

**Comment by xet7** [comment] 2020-03-03 15:25
Thanks! I did not notice this new bug before. Previously card did not move on those users.

**Comment by adminschb01** [comment] 2020-03-12 13:28
any news about this.
thanks

**Comment by xet7** [comment] 2020-03-12 14:37
Fixing is in progress, but not ready yet.

**Comment by nickbe** [comment] 2020-03-17 13:01
I just saw the issue title. It would be wrongnto prevent workers from moving cards, because this is exactly what the worker rule was designed for:

He „works“ on issues and has to keep the project manager informed about the progress. For this to work he moves the card from one column or „state“ to the next. And wekan sends a mail, telling the manager that the card status has advanced.

**Comment by xet7** [comment] 2020-03-17 15:31
@nickbe 

Hmm, probably I did misunderstand this issue. Just a moment I remove word "worker" from this.

**Comment by nickbe** [comment] 2020-03-18 12:17
Ah thanks :) 
commenters should of course not be able to move cards 😁

**Comment by NicoP-S** [comment] 2020-04-02 19:57
@xet7 you did some changes a while ago (https://github.com/wekan/wekan/commit/bf78b093bad7d463ee325ad96e8b485264d4a3be) 

There are two if statements which seems not to be true. Where will the sortable data attribute set? 

>  if ($cards.data('sortable')) {

https://github.com/wekan/wekan/blob/bf78b093bad7d463ee325ad96e8b485264d4a3be/client/components/lists/list.js#L142-L151

**Comment by NicoP-S** [comment] 2020-06-09 11:04
I did a update of Wekan to 4.09 and also a mongodb upgrade to 4.x  ( docker ) 
Now the comment only role is not able to move cards.

**Comment by marc1006** [comment] 2020-06-10 10:26
@NicoP-S It's possible that it was fixed by a commit from me (981ed546f1cae45ad8b92b393ee29c1a26277f32). I haven't verified this, but the old code did not match with the comments in the code.

So this means we can close this issue?

**Comment by xet7** [comment] 2020-06-10 10:34
Thanks ! I did test this, this is already fixed.

**Closed by xet7** 2020-06-10 10:34 UTC
Labels: Bug, Feature:Roles
