### ISSUE TITLE
Scrollbar not working on Change Language popup 

### ISSUE THREAD

**Issue by prawee** [wekan/wekan#857] opened 2017-02-20 16:27 UTC
This effect may be cause of recent updated

**Comment by nztqa** [comment] 2017-06-27 07:23
I can't reproduce it.
@xet7 Please close this issue
![wekan_changelaunguage-iloveimg-compressed](https://user-images.githubusercontent.com/22808079/27575485-ededfdb0-5b54-11e7-9e12-e3d75a1b4e6e.gif)

**Closed** 2017-06-27 08:14 UTC
Labels: Bug
