### ISSUE TITLE
Other Users cannot create labels

### ISSUE THREAD

**Issue by remcooverweg** [wekan/wekan#1229] opened 2017-09-19 20:11 UTC
## Issue
**Impacted version**: 0.37

**Server Setup Information**:

* Operating System: Linux Ubuntu 14.04 Sandstorm
* Node Version: 0.37
* MongoDB Version: NA

**Problem description**:
Only the user who created the grain/bord can create labels, other users who can edit the board (create cards, move cards, create lists) cannot create or edit a label.

When a user clicks on create label,it shows the new label for 1 sec and then it dissapears.

Login with other account i can reproduce the problem

**Comment by ocdtrekkie** [comment] 2017-09-20 21:07
Hmm... next question is: Does it work on non-Sandstorm Wekan. If someone can test that, it will help narrow down where the bug is.

**Comment by crapnicki** [comment] 2017-09-28 16:47
We are testing and experiencing the same issue.

Manual Installation:
```
Wekan version: 0.41.0
Node version: v4.8.4
OS Type: Linux
OS Platform: linux
OS Arch: x64
OS Release 3.10.0-0693.2.2.el7_x86_64 (CentOS 7)
```

**Comment by nztqa** [comment] 2017-09-29 05:40
Only an board administrator can create a label
Authority setting
![wekan_create_label_ authority-iloveimg-compressed](https://user-images.githubusercontent.com/22808079/31002082-56bd878a-a523-11e7-8b8d-629176cd1586.gif)


It's about this?
"Create Label" buttons are displayed is a bug
![wekan_create_label_disply-iloveimg-compressed](https://user-images.githubusercontent.com/22808079/31001961-796e0846-a522-11e7-9351-f4853cbcab63.gif)

**Comment by remcooverweg** [comment] 2017-09-29 07:09
I only have the option when i click on someone from the members list "filter cards".  I am the admin though of the board.

**Comment by nztqa** [comment] 2017-09-29 07:43
@remcooverweg 
Not available in sandstorm 
[this commit](https://github.com/wekan/wekan/commit/8b3a6a78190f9e03f6ca24315a9c977967355c0c#diff-4da89a936cfcfedea5b6c5fa88691477)
I'm not familiar with sandstorm

**Comment by crapnicki** [comment] 2017-09-29 13:11
@nztqa This resolved the issue.

I think instead of it just disappearing, either the option should to add labels/edit labels should be hidden, or it should throw an error.

**Comment by remcooverweg** [comment] 2017-09-29 14:26
@ crapnicki Any idea when this will also be resolved in Official Sandstorm release, or do i need to edit it manually (if that is even possible) Or should i just go to native Linux installation?

**Comment by ocdtrekkie** [comment] 2017-09-29 14:36
So, to be clear, the current issue (which I expect is the same in Sandstorm and non-Sandstorm builds?) is that non-admins can see the create label button?

@remcooverweg If the issue is fixed in Wekan, it will generally make it to Sandstorm shortly thereafter. We do a little extra testing before approving updates to the Sandstorm version.

**Comment by remcooverweg** [comment] 2017-09-29 15:52
So, to be clear, the current issue (which I expect is the same in Sandstorm and non-Sandstorm builds?) is that non-admins can see the create label button?

@ocdtrekkie I expected that all users could create or edit a label. If it was intended that the admin is the only one who can do this, then i will open a new feature request, asking if other users may also edit and/or create a label. Hope this helps in giving clarity.

**Comment by ocdtrekkie** [comment] 2017-09-29 16:09
I don't see a huge reason not to let normal users create labels, other similar software does.

If a change is made to Wekan to allow it, the change should correctly occur in Sandstorm as well, once it makes it into a release.

**Closed** 2017-10-01 07:09 UTC

**Comment by remcooverweg** [comment] 2017-10-01 17:32
Big Thanks nztqa! for the speedy follow up with a fix.
