### ISSUE TITLE
Feature Request: Search in all boards

### ISSUE THREAD

**Issue by rlach** [wekan/wekan#2074] opened 2018-12-27 12:31 UTC
**Problem description**:
- Wekan can currently search for cards only in the current board. In Trello you can also choose to search in all boards you have access to.

This way you could:
* find subtasks related to stories you currently have in your board
* find cards in other boards matching selected name

It's very useful for workflows where users move stories between boards.

Screenshot of the search example on Trello:
![zrzut ekranu z 2018-12-27 13-30-08](https://user-images.githubusercontent.com/5655000/50480329-8c6dba80-09db-11e9-88c7-66cfb58aa723.png)

**Comment by superlou** [comment] 2019-01-04 21:15
It would also be really helpful if this could search for all cards that someone is a member of. This could satisfy some use cases of #2055.

**Comment by bhueck** [comment] 2019-02-04 14:04
I also think this is a "must have" feature to get wekan in production (for a company).

**Comment by gsommavilla** [comment] 2019-07-02 09:27
Is there any update about this issue?
The "search-in-all-boards" feature is really something that I would love to have.

**Comment by xet7** [comment] 2019-07-02 10:46
@gsommavilla 

No one has started coding search feature yet. It would require someone to have time to read Wekan source code existing search feature, and add to it searching for other boards of user too. Code contributions as pull requests welcome. See Wekan GitHub wiki for Developer Docs and Directory Structure.

**Comment by xet7** [comment] 2019-07-02 10:56
If it is really important to have this soon, someone can add bounty, see:
https://www.bountysource.com/issues/68005834-feature-request-search-in-all-boards
https://wekan.team/bounties/index.html

**Comment by r0bbie** [comment] 2020-07-03 16:27
While I can't support the 500 € at this point unfortunately, would definitely be really keen to see this feature at some point, and if there was a BountySource (or similar, since I see you're moving away from that!) setup I'd happily chip in with others.

**Comment by xet7** [comment] 2020-07-03 16:53
@r0bbie 

Current payment methods are here:
https://wekan.team/commercial-support/

It works similarly, so if someone sends some part of that 500 € then it is added to [Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license).

**Comment by xet7** [comment] 2020-09-15 10:24
Moved to here from https://github.com/wekan/wekan/issues/552#issuecomment-692482399

From @gregruthenbeck 

> Search doesn't search comments. It would be great if it did.

Yes, I would think this `Search in all boards` will include searching comments. I did get funding for this feature at this week.

> Can this behavior be added/enabled relatively easily?

No, it can not be added relatively easily. Programming this requires many hours of work to get feature working correctly. Anyway, I hope to get this finished at this year.

**Comment by xet7** [comment] 2020-09-16 22:34
Someone asked at Wekan Community:

> Does anybody knows whether you can filter card by comment date, to get the cards that have been commented in the last week for instance ?

Maybe this could be related to this search instead, being some search option.

**Comment by xet7** [comment] 2020-11-19 22:02
@superlou 

In theory, yes, and that 500 euro has already been prepaid. In practice, it could be just enough, or require total 1000 euro of work. It could work fine, or slow down Wekan a lot.

Usually it's just throwing a lot of features to Wekan to see could it even possibly work.

**Comment by superlou** [comment] 2020-11-21 16:11
Ah, that makes sense. I'm going to look into getting further sponsors.

**Comment by xet7** [comment] 2021-01-18 09:32
Those new changes will be in next Wekan release, that will happen sometime today or tomorrow. I will fix one not-related Wekan bug before making new Wekan release.

**Comment by jrsupplee** [comment] 2021-01-18 09:50
@xet7 

Not sure if you looked at the way I did the translatable search instructions using Markdown.  Do you think this will be a problem for translators?

**Comment by xet7** [comment] 2021-01-18 09:54
@jrsupplee 

No. First that I have tested and figured out Finnish translations, I will add info for translators to Transifex about how to translate.

**Comment by xet7** [comment] 2021-01-18 10:51
@jrsupplee 

Can you make colors translated, with examples? For example, now when in English I search:
```
label:red
```
In Finnish I can currently search:
```
nimilappu:red
```
Colors are already translated like `color-red`, so with that added, I could search for:
```
nimilappu:punainen
```
At search instructions could be a list of labels with translated color names, where for example red labels have red background and same visible-enough (light or dard) foreground color like at labels at board:
```
[red] [yellow]...
```
That would be in Finnish:
```
[punainen] [keltainen]...
```

**Comment by jrsupplee** [comment] 2021-01-18 14:44
@xet7 
I will look at this. I don't think it will be difficult.

**Comment by jrsupplee** [comment] 2021-01-20 20:37
@xet7 
Sorry to comment on a closed issue, but did not want to open a new one.

I have been thinking about your suggestion of having a list of the color like the label.  I worked something up and added functionality so that clicking on the color adds it to the search.

![image](https://user-images.githubusercontent.com/1286169/105231470-a274e780-5b6f-11eb-814e-32482af9072b.png)

I did the same thing for list names.

We could do something like this for all the different criteria but if the lists get big it will become unwieldy.

What do you think, is this worth pursuing?

Code: https://github.com/jrsupplee/wekan/tree/new-search

**Comment by xet7** [comment] 2021-01-20 20:52
@jrsupplee 

Yes, this is great! I also do not remember color names etc, and what they are when translated to Finnish, so it's great to have visible list of all those search options. Please add PR. Thanks a lot!

**Comment by xet7** [comment] 2021-01-22 10:00
@jrsupplee 

Is it already possible to search from attachment filenames? If not, is it possible for you to add that?

**Comment by xet7** [comment] 2021-01-22 10:20
@jrsupplee 

What do you think, would it be possible for you to add feature `My Attachments` ? That would show all attachments of your member boards and public boards?

**Comment by xet7** [comment] 2021-01-22 10:22
@jrsupplee 

Also, if you don't have time, please ignore my questions above.

**Comment by jrsupplee** [comment] 2021-01-22 14:50
@xet7 
> Is it already possible to search from attachment filenames? If not, is it possible for you to add that?

I have added some new operators (due date, created date, modified date).  I don't think this would be difficult but I have not looked at attachments.

**Comment by jrsupplee** [comment] 2021-01-22 14:55
@xet7 
> What do you think, would it be possible for you to add feature `My Attachments` ? That would show all attachments of your member boards and public boards?

Might be best to add this as a feature request.  I don't have time to do this now, but I doubt it would be difficult.

The time consuming part for me is the HTML (jade) and CSS to display things in a decent way.  *My Cards* should be modified to look more like the Wekan theme.  But it works so I am not motivated to spend the time tweaking the display.

**Comment by xet7** [comment] 2021-01-22 15:11
@jrsupplee 

Ok, I'll add it as Feature Request, so someone interested in it can add it.

**Comment by mfilser** [comment] 2021-01-22 18:59
I am not sure to open a new issue or not.
At global search: If using Wekan with German language, the sort does not work with lists / boards / labels.
For example here is a screenshot:
![grafik](https://user-images.githubusercontent.com/13166201/105533304-3c619f00-5cec-11eb-8e3f-68b3f2cd21fa.png)

![grafik](https://user-images.githubusercontent.com/13166201/105533226-1b994980-5cec-11eb-94fc-0b9021548446.png)

![grafik](https://user-images.githubusercontent.com/13166201/105533252-2653de80-5cec-11eb-95bc-6498b6cd7c93.png)

![grafik](https://user-images.githubusercontent.com/13166201/105533356-4edbd880-5cec-11eb-8b2e-77f8147f9341.png)

**Comment by jrsupplee** [comment] 2021-01-22 20:49
@mfilser 

> I am not sure to open a new issue or not.
> At global search: If using Wekan with German language, the sort does not work with lists / boards / labels.

The problem is with the German translation of the operators.  They should be specified in lowercase but in German they have the first letter capitalized.  I will submit a patch to account for this.

Until then you can search with the abbreviated operators.
* `b:"Test"` for board
* `s` for swimlane
* `l` for text
* `m` for member
* `a` for assignee

**Comment by mfilser** [comment] 2021-01-22 22:12
@jrsupplee
Thank you a lot, i will try it. 

I just clicked on the label, list and board tags you created, maybe the abbreviated letters can be the default behavior for this? 

Also thank you a lot for your work, you are doing very well. 
Also @xet7 of course.
And all others of course too ;)

**Comment by xet7** [comment] 2021-01-22 23:00
Fix for search operators with uppercase letters at https://github.com/wekan/wekan/pull/3470

**Comment by bronger** [comment] 2021-01-24 21:13
I still see an issue: The direct link generated to the global search contains i18n operators but this is not accepted by Wekan. In the URL, only English operator names are accepted.

**Comment by jrsupplee** [comment] 2021-01-24 21:22
@xet7 

I had trouble getting `TAPi18n.__()` to work in a template `onCreated`.  It always seemed to return the English (the default).  What is going on with this?

**Comment by jrsupplee** [comment] 2021-01-24 21:55
It looks like `.onCreated()` is called before insertion to the DOM.  So I guess I should use `.onRendered()`

**Comment by bronger** [comment] 2021-02-01 06:15
I18n operator names in query strings in URLs still do not work in v4.91.

**Comment by jrsupplee** [comment] 2021-02-01 14:33
@bronger 

Could you try opening the inspection console for the page and then running the searches again.

**Comment by bronger** [comment] 2021-02-01 15:20
I don’t understand what you need me to do. You can see the problem here: https://op.its.kfa-juelich.de:8843/global-search?q=Liste%3AA. Login/password is test/12345.

**Comment by jrsupplee** [comment] 2021-02-01 15:35
I can ping the server op.its.kfa-juelich.de but Wekan will not open.

**Comment by bronger** [comment] 2021-02-01 15:47
Sorry, drop the port number.  Login as test/12345 at https://op.its.kfa-juelich.de/, then open https://op.its.kfa-juelich.de/global-search?q=Liste%3AA.

**Comment by jrsupplee** [comment] 2021-02-01 16:40
@xet7 

There is an issue that the `TAPi18n` system appears to not get initialized before the `onRendered()` of the component is called.

Is it possible that this code from `i18n.js` could have a slight delay in its execution so it completes after `onRendered()` is called?

```
// We save the user language preference in the user profile, and use that to set
// the language reactively. If the user is not connected we use the language
// information provided by the browser, and default to english.

Meteor.startup(() => {
  TAPi18n.conf.i18n_files_route = Meteor._relativeToSiteRootUrl('/tap-i18n');
  Tracker.autorun(() => {
    const currentUser = Meteor.user();
    let language;
    if (currentUser) {
      language = currentUser.profile && currentUser.profile.language;
    }

    if (!language) {
      if (navigator.languages) {
        language = navigator.languages[0];
      } else {
        language = navigator.language || navigator.userLanguage;
      }
    }

    if (language) {
      TAPi18n.setLanguage(language);
      // eslint-disable-next-line no-console
      console.log('language set!');
      T9n.setLanguage(language);
    }
  });
});
```

**Comment by xet7** [comment] 2021-02-01 23:33
@jrsupplee 

Yes, `tap:i18n` is old and buggy. I also have problem that at serverside with `Meteor.isServer` it does not translate to user's language.

Is it possible for you to try changing `tap:i18n` to `ostrio:i18n` https://atmospherejs.com/ostrio/i18n if it's any better? For example:
```
cd wekan

meteor remove tap:i18n

meteor add ostrio:i18n
```
And then trying does translation syntax mentioned at https://atmospherejs.com/ostrio/i18n work?

Alternatively, there could be other i18n packages that could maybe work: https://atmospherejs.com/?q=i18n

**Comment by jrsupplee** [comment] 2021-02-02 10:49
@xet7 

> @jrsupplee
> 
> Yes, `tap:i18n` is old and buggy. I also have problem that at serverside with `Meteor.isServer` it does not translate to user's language.
> 
> Is it possible for you to try changing `tap:i18n` to `ostrio:i18n` https://atmospherejs.com/ostrio/i18n if it's any better?

Sounds like a lot of work and the documentation for `ostrio:i18n` is pretty sparse.

I tried removing the `TAPi18n` initialization code from the `Tracker.autorun()`.  This is possibly delaying the execution.  The system seems to run fine.  So `i18n.js` is now:

```
Meteor.startup(() => {
  TAPi18n.conf.i18n_files_route = Meteor._relativeToSiteRootUrl('/tap-i18n');
  const currentUser = Meteor.user();
  let language;
  if (currentUser) {
    language = currentUser.profile && currentUser.profile.language;
  }

  if (!language) {
    if (navigator.languages) {
      language = navigator.languages[0];
    } else {
      language = navigator.language || navigator.userLanguage;
    }
  }

  if (language) {
    TAPi18n.setLanguage(language);
    // eslint-disable-next-line no-console
    console.log('language set!');
    T9n.setLanguage(language);
  }
});
```

What do you think, could this solve the issue?

**Comment by xet7** [comment] 2021-02-02 15:04
@jrsupplee 

Please add pull request. Thanks!

**Closed** 2021-04-01 11:54 UTC
Labels: Feature:Search
