### ISSUE TITLE
Email "From" field is ignored when set in admin panel

### ISSUE THREAD

**Issue by ArcturusB** [wekan/wekan#896] opened 2017-03-06 15:13 UTC
I updated to v0.12 in Docker yesterday, and rushed to the brand new admin panel
(thanks a million for it btw! 👍). After disabling self-registration, I configured
emails, which I wasn't using before.

In the admin panel, I configured Wekan to use a SMTP server running on the Docker host system, with
account `wekan@host.example`. I was able to send test invitation emails, but
these don't have a "From" field, even though I set it in the admin panel, so I'm receiving something like:

    From:
    Subject: arcturus sent you an invitation
    To: user+test1@host.example

Here is the admin panel content:

    SMTP Host: mail.host.example
    SMTP Port: 25
    Username: wekan
    Password: *****
    From: wekan@host.example

It seems as if the "From" field was totally ignored by Wekan.

---

The SMTP server:

- is running on `host.example:25`,
- is configured to accept mails from 172.17.0.0/16,
- knows account `wekan@host.example`.

Here are the Dovecot/Postfix logs I get when sending an invitation email from
the admin panel. Hopefully they can help trace back the origin of the issue:

    Mar  6 15:39:55 host postfix/smtpd[17590]: connect from unknown[172.17.0.3]
    Mar  6 15:39:55 host postfix/smtpd[17590]: DEC1C6030A: client=unknown[172.17.0.3], sasl_method=PLAIN, sasl_username=wekan
    Mar  6 15:39:55 host postfix/cleanup[17594]: DEC1C6030A: message-id=<>
    Mar  6 15:39:55 host postfix/qmgr[17235]: DEC1C6030A: from=<anonymous@[127.0.0.1]>, size=580, nrcpt=1 (queue active)
    Mar  6 15:39:56 host dovecot: lda(user): msgid=unspecified: saved mail to INBOX
    Mar  6 15:39:56 host postfix/pipe[17595]: DEC1C6030A: to=<user+test1@host.example>, relay=dovecot, delay=0.15, delays=0.05/0.01/0/0.09, dsn=2.0.0, status=sent (delivered via dovecot service)
    Mar  6 15:39:56 host postfix/qmgr[17235]: DEC1C6030A: removed
    Mar  6 15:44:55 host postfix/smtpd[17590]: timeout after END-OF-MESSAGE from unknown[172.17.0.3]
    Mar  6 15:44:55 host postfix/smtpd[17590]: disconnect from unknown[172.17.0.3]

**Comment by xet7** [comment] 2017-03-06 19:05
@lkisme 

Do you know how to fix this?

**Comment by lkisme** [comment] 2017-03-08 16:28
I already found the root cause, need a little more time to do some test on it.

**Comment by xet7** [comment] 2017-03-12 14:57
Fixed in today's Wekan release v0.13.

**Closed by xet7** 2017-03-12 14:57 UTC
