### ISSUE TITLE
Bug: Comment on a Board can make the activities invisible

### ISSUE THREAD

**Issue by Nephos** [wekan/wekan#516] opened 2016-02-10 14:41 UTC
Hello,

First I want to say that your work is very cool.

I got this issue on 2 different boards:

On a board with 10 users, 5-6 list, and few comments the first time, not only one in the second case.

When I or any of my team make a new comment, then the comments of the task stop to appear in the task comments list. And the activities associated (like member addition, etc.) neither on the task. But still on the global activity bar.

On theses items, there is an other problem: if i set a description on the task, then, when I click on them, there is a problem. The task doesn't unfold.
![screenshot_20160210_154546](https://cloud.githubusercontent.com/assets/979584/12950422/63575ce2-d00d-11e5-8408-4c229b4082c2.png)

I have theses logs

![screenshot_20160210_154732](https://cloud.githubusercontent.com/assets/979584/12950498/ca1707ac-d00d-11e5-95f8-cd017e02cdcc.png)

![screenshot_20160210_153359](https://cloud.githubusercontent.com/assets/979584/12950200/421dc3a0-d00c-11e5-9b3e-d273d00f8135.png)
 
```text
Exception in queued task: t<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:401:872
@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:401:828
l@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:20508
l/</<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:18463
e._withTemplateInstanceFunc@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:53:4982
l/<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:18406
d._withCurrentView@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:22533
l@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:18364
t.Computation.prototype._compute@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:2366
t.Computation@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:1298
t.autorun@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:4079
d.View.prototype.autorun@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:18543
d._materializeView/<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:20445
t.nonreactive@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:4260
d._materializeView@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:20420
e@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:14911
d._materializeDOM@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:14145
d._materializeDOM@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:14189
d._materializeView/<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:20871
t.nonreactive@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:4260
d._materializeView@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:20420
d.Each/</a.stopHandle<.addedAt/<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:28642
t.nonreactive@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:4260
d.Each/</a.stopHandle<.addedAt@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:28300
d/o<.addedAt@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:48:2575
f._observeFromObserveChanges/a.addedBefore@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:69:3337
f._CachingChangeObserver/n.applyChange.addedBefore@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:69:2414
.observeChanges/c/</<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:67:4001
.runTask@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:5:4220
.flush@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:5:4477
.drain@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:5:4578
f.prototype.resumeObservers@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:67:11582
p.Collection/a<.endUpdate@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:84:3096
.registerStore/</r[e]@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:78:8972
._livedata_data/<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:78:16504
A.forEach@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:3:1007
._livedata_data@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:78:16475
e.connection._livedata_data@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:170:5430
u/o@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:78:6487
._launchConnection/t.socket.onmessage/<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:78:567
A.forEach@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:3:863
._launchConnection/t.socket.onmessage@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:78:523
v</r.prototype.dispatchEvent@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:77:1119
v</C.prototype._dispatchMessage@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:77:14711
v</C.prototype._didMessage@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:77:15601
v</C.websocket/o.ws.onmessage@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:77:17702

8e71878...ce=true (ligne 5)
19

Exception in queued task: d.Each/i@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:27957
d.Each/</a.stopHandle<.addedAt/<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:28693
t.nonreactive@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:4260
d.Each/</a.stopHandle<.addedAt@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:28300
d/o<.addedAt@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:48:2575
f._observeFromObserveChanges/a.addedBefore@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:69:3337
f._CachingChangeObserver/n.applyChange.addedBefore@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:69:2414
.observeChanges/c/</<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:67:4001
.runTask@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:5:4220
.flush@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:5:4477
.drain@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:5:4578
f.prototype.resumeObservers@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:67:11582
p.Collection/a<.endUpdate@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:84:3096
.registerStore/</r[e]@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:78:8972
._livedata_data/<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:78:16504
A.forEach@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:3:1007
._livedata_data@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:78:16475
e.connection._livedata_data@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:170:5430
u/o@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:78:6487
._launchConnection/t.socket.onmessage/<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:78:567
A.forEach@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:3:863
._launchConnection/t.socket.onmessage@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:78:523
v</r.prototype.dispatchEvent@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:77:1119
v</C.prototype._dispatchMessage@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:77:14711
v</C.prototype._didMessage@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:77:15601
v</C.websocket/o.ws.onmessage@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:77:17702

8e71878...ce=true (ligne 5)
Exception from Tracker recompute function:
8e71878...ce=true (ligne 5)
TypeError: Users.findOne(...) is undefined
8e71878...ce=true (ligne 5)

t<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:401:872
@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:401:828
l@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:20508
l/</<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:18463
e._withTemplateInstanceFunc@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:53:4982
l/<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:18406
d._withCurrentView@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:22533
l@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:18364
t.Computation.prototype._compute@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:2366
t.Computation@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:1298
t.autorun@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:4079
d.View.prototype.autorun@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:18543
d._materializeView/<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:20445
t.nonreactive@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:4260
d._materializeView@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:20420
e@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:14911
d._materializeDOM@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:14145
d._materializeDOM@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:14189
a@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:20582
t.nonreactive@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:4260
l@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:20549
l/</<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:18463
e._withTemplateInstanceFunc@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:53:4982
l/<@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:18406
d._withCurrentView@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:22533
l@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:52:18364
t.Computation.prototype._compute@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:2366
t.Computation.prototype._recompute@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:2601
t._runFlush@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:28:3564
e@https://DOMAIN.herokuapp.com/8e718784e5e106f4d9f24ce29592400fd1f93740.js?meteor_js_resource=true:5:2033
```

**Comment by vitaliy-kuzmich** [comment] 2016-03-09 11:33
the same problem.

**Comment by vitaliy-kuzmich** [comment] 2016-03-11 13:11
problem solved, close this ticket. the problem is not in wekan, problem in DB, probably @Nephos deleted the user from users collection, but did not from boards.

#remove user from wekan system:
#1. remove from db.boards
#2. remove from db.users

#1. find all boards with this user
db.boards.find({members:{$elemMatch:{userId:"qaWu8sJ7cWpSechXL"}}},{})
#copy full member item, and paste as at example below:
db.boards.update({},{$pull:{members:{$in:[{ "userId" : "qaWu8sJ7cWpSechXL", "isAdmin" : false, "isActive" : true }]}}},{multi:true})

#2.
 db.users.remove({"_id":"qaWu8sJ7cWpSechXL"})

**Closed** 2016-03-14 12:20 UTC
