### ISSUE TITLE
Importing JSON Information from Trello

### ISSUE THREAD

**Issue by Heliotherm** [wekan/wekan#610] opened 2016-05-24 10:13 UTC
Hi, I tried to import Informations from trello. Created the users as told in the Wiki. But for some reason I always get the information that the Json Information is not in the right format. 
Although it is an Export directly from trello. 
Is there a limitation to it?

**Comment by mquandalle** [comment] 2016-07-18 14:30
There isn’t any known limitation. It would be great if you could craft and share a JSON export that reproduce the error, while removing your private data in it.

**Comment by xet7** [comment] 2017-02-10 13:15
@Heliotherm has not provided example file. Closing issue.

**Comment by 88fingerslukee** [comment] 2017-06-23 21:59
I'm having this issue with v.24.  Any ideas how I can craft the JSON to remove my private data? It's a pretty big board.

**Comment by xet7** [comment] 2017-06-24 20:10
@88fingerslukee 

Use some [Awesome JSON tools](https://github.com/burningtree/awesome-json)

Or filtering and deleting:

1) In Trello, use filter or search to find cards that you want to delete
2) Export Trello board
3) Import into Wekan

Or using API to find and delete info:

a) Use [Trello API](https://developers.trello.com)
b) Use [Wekan REST API](https://github.com/wekan/wekan/issues/1037)

**Comment by xet7** [comment] 2017-06-24 20:13
AFAIK import JSON from Trello work currently. 

You can also [copy exported JSON file to clipboard](https://unix.stackexchange.com/questions/211817/copy-the-contents-of-a-file-into-the-clipboard-without-displaying-its-contents) so it's easier to paste.

**Comment by 88fingerslukee** [comment] 2017-06-30 17:26
This is going to be impossible as it's a huge board and it would take forever to go through and sanitize the data. Also, how could I possibly recreate the issue if I have no idea what the issue is?  Isn't there some log file that will give more detailed errors or specific line of the JSON that's causing the barf?

**Comment by sk33z3r** [comment] 2017-08-09 15:07
I am also having this issue, but only with large boards. As 88fingerslukee mentioned, the JSON data is massive and has my company's sensitive data in it (around 1.3 million characters). It would be impossible to strip and sanitize this entire thing to post publicly.

Is there some other way we can provide you with information to help resolve our issues? Are there certain parts of the data that are useful, like the first several lines? The error in Wekan pops up almost immediately after choosing the members to link. Any other possible logs or debug output?

**Comment by xet7** [comment] 2017-08-12 09:23
@GhassenRjab 

Previously when importing boards problem has been that some labels don't have names. Could it be related to this? Or do you have other ideas how to debug this?

**Comment by xet7** [comment] 2017-08-12 09:37
Moved to #1174

**Closed by xet7** 2017-08-12 09:37 UTC
Labels: Bug, Feature:Import-export
