### ISSUE TITLE
Add support for more label colors

### ISSUE THREAD

**Issue by tuliom** [wekan/wekan#462] opened 2015-12-31 14:17 UTC
Depending on the size of the project you need to have more than 10 labels and you'll certainly end up with 2 labels having the same color.

**Comment by mquandalle** [comment] 2015-12-31 14:20
Is this a duplicate of #457?

**Comment by araczkowski** [comment] 2015-12-31 15:50
it will be even better if we will have "icon labels" (Font Awesome)

**Comment by tuliom** [comment] 2015-12-31 18:54
@mquandalle yes, it's indeed a duplicate.
Looks like I don't have permission to modify the labels here. Could you mark this as a duplicate and close it, please?
Thanks!

**Closed** 2016-01-01 01:12 UTC
Labels: Duplicate
