### ISSUE TITLE
Not be able to leave comments onto an activity

### ISSUE THREAD

**Issue by thomasfrivold** [wekan/wekan#292] opened 2015-09-04 09:49 UTC
Hi

When I enter any comments into the activity for a card in Wekan, nothing happens. The comment is not shown and it seems it is not stored.

I am running Wekan on a Sandstorm instance.

Any ideas on how I can get it working?

Cheers

**Comment by mquandalle** [comment] 2015-09-04 10:56
Closing, as a duplicate of #270.

**Closed by mquandalle** 2015-09-04 10:56 UTC
