### ISSUE TITLE
Bug: Some modules not using ROOT_URL with subfolder

### ISSUE THREAD

**Issue by NoodleBB** [wekan/wekan#973] opened 2017-04-03 12:10 UTC
Since update on v0.18 i can't set the language in the client anymore.

The selection opens, but when clicking on the menu entry, it doesn't select it. No checkmark and no language change.

_Wekan 0.18. Release version. Manual install._

**Comment by xet7** [comment] 2017-04-03 14:27
Moved to #962

**Comment by xet7** [comment] 2017-04-07 07:26
Moved back to here, and can be continued here.

**Comment by NoodleBB** [comment] 2017-04-07 08:58
This is one of the three resources i've found (/**tap-i18n**/, /cfs/files/**avatars**/, /**setting**), that doesn't use the fully specified ROOT_URL for loading. Those fail permanently to load. - You'll see that in the browsers console. 

When you copy and change the URLs manually, then these resources are accessible without problems. 

>  It's an issue with modules not using the ROOT_URL. 

Right.

**Comment by NoodleBB** [comment] 2017-04-09 15:27
Same problem with attachments.

**Comment by xet7** [comment] 2017-05-07 15:23
Related to #386 and https://github.com/CollectionFS/Meteor-CollectionFS/issues/884

**Comment by GhassenRjab** [comment] 2017-06-21 18:33
I use Wekan 0.23 and I couldn't reproduce the issue to be able to debug it.
Is this issue specific to Wekan 0.18 or I missed something trying to reproduce?

**Comment by NoodleBB** [comment] 2017-06-22 10:20
> or I missed something trying to reproduce?
The [manual install](https://github.com/wekan/wekan/wiki/Install-and-Update#manual-installation-steps) of the [release version](https://github.com/wekan/wekan/releases/download/v0.24/wekan-0.24.tar.gz)? 

The discussion made some turns. There was a previous issue that belongs to this: https://github.com/wekan/wekan/issues/962

**Comment by nztqa** [comment] 2017-06-26 01:03
Subdirectory problems. https://github.com/wekan/wekan/issues/133
@NoodleBB Please add (subdirectory/subfolder/prefixed paths) to the title.

**Comment by nztqa** [comment] 2017-06-26 02:20
Language settings problem.

Related: 
  * https://github.com/TAPevents/tap-i18n/issues/140
  * https://github.com/TAPevents/tap-i18n/blob/master/README.md#configuring-tap-i18n
  * https://github.com/RocketChat/Rocket.Chat/pull/3772

I think there is no problem.
```
diff --git a/client/lib/i18n.js b/client/lib/i18n.js
index 4c02211..97a9137 100644
--- a/client/lib/i18n.js
+++ b/client/lib/i18n.js
@@ -3,6 +3,7 @@
 // information provided by the browser, and default to english.
 
 Meteor.startup(() => {
+  TAPi18n.conf.i18n_files_route = Meteor._relativeToSiteRootUrl('/tap-i18n');
   Tracker.autorun(() => {
     const currentUser = Meteor.user();
     let language;
```

**Comment by nztqa** [comment] 2017-06-26 06:02
Admin panel  problem. (Subpath is missing in admin panel)

I think there is no problem.
```
diff --git a/client/components/users/userHeader.jade b/client/components/users/userHeader.jade
index 51b0888..84ef5a0 100644
--- a/client/components/users/userHeader.jade
+++ b/client/components/users/userHeader.jade
@@ -18,7 +18,7 @@ template(name="memberMenuPopup")
       li: a.js-change-language {{_ 'changeLanguagePopup-title'}}
       li: a.js-edit-notification {{_ 'editNotificationPopup-title'}}
     if currentUser.isAdmin
-      li: a.js-go-setting(href='/setting') {{_ 'admin-panel'}}
+      li: a.js-go-setting(href="{{pathFor 'setting'}}") {{_ 'admin-panel'}}
   hr
   ul.pop-over-list
     li: a.js-logout {{_ 'log-out'}}
```

**Comment by nztqa** [comment] 2017-06-26 07:07
Avatars problem (Subpath is missing in /cfs/files/avatars)
No problem.
![image](https://user-images.githubusercontent.com/22808079/27528042-76e75bec-5a89-11e7-91a4-ec77eef99bb2.png)

**Comment by xet7** [comment] 2017-06-26 09:44
Merged. Is this now fixed?

**Comment by nztqa** [comment] 2017-06-26 10:06
@xet7 Please close this issue

**Closed** 2017-06-26 10:10 UTC
Labels: Bug
