### ISSUE TITLE
Is it possible to run Libreboard without Sandstorm or Docker?

### ISSUE THREAD

**Issue by egrigolon** [wekan/wekan#187] opened 2015-06-11 16:31 UTC
Is it?

Edit: Sorry for the auto-correct, I meant libreboard.

**Comment by JohnPostlethwait** [comment] 2015-06-11 23:37
I would like to know this as well...

**Comment by gonzoramos** [comment] 2015-06-12 06:38
same here

**Comment by ocdtrekkie** [comment] 2015-06-12 06:53
LibreBoard is built with Meteor (see meteor.com). You can definitely run Meteor applications on your server without Sandstorm or Docker, but it will need to be a server where Meteor can be installed.

**Comment by mquandalle** [comment] 2015-06-12 17:07
Actually you don't *need* to meteor on your server production. Once v0.9 is released we will provide a `npm install` `npm start` source, along with the docker and sandstorm packages.

**Comment by gonzoramos** [comment] 2015-06-12 17:29
Cannot wait for this ability! Right now I just cannot self-host libreoffice on my OSX box:

- Kitematic image will not load / download
- Docker CLI running instructions seem to do nothing
- Sandstorm.IO is not supported on OSX
- Missing instructions on how to run it on Meteor

Many thanks in advance!
-G

**Comment by egrigolon** [comment] 2015-06-12 18:47
@mquandalle thanks for the info, and thanks for fixing the issue title as well. I hope this version is out soon.

@gonzoramos same for me, I set up a Linux machine running Ubuntu just to install Sandstorm but I had not success configuring it.

**Comment by JohnPostlethwait** [comment] 2015-06-12 19:00
Just did the meteor route. 

Turns out you just have to install meteor on your server https://www.meteor.com/install `cd` to the libreboard source dir, and then run `meteor` and it should be running for you. There are likely some more options you will want to set, or to daemonize it...

**Comment by gonzoramos** [comment] 2015-06-12 19:14
Awesome! It works like a charm. Thank you all!

**Comment by egrigolon** [comment] 2015-06-12 21:00
So, I tried running meteor from the cloned directory. This is what I got using sudo...

```shell
s2:libreboard (master*) $ sudo meteor
[[[[[ ~/projects/libreboard ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While building the application:
   error: Bower dependencies list must be a dictionary in bower_components/perfect-scrollbar/bower.json
   bower_components/autosize/src/autosize.js:1:35: Unexpected token {
   bower_components/autosize/example/index.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)

=> Your application has errors. Waiting for file change.
```
and without sudo...

```shell
s2:libreboard (master*) $ meteor
[[[[[ ~/projects/libreboard ]]]]]

=> Started proxy.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.

/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: EACCES, unlink '/home/s2/projects/libreboard/.meteor/local/build-garbage-r1yv3k/README'
    at Object.Future.wait (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.rm_recursive (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/files.js:268:9)
    at Object.files.renameDirAlmostAtomically (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/files.js:822:11)
    at [object Object]._.extend.complete (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/builder.js:482:11)
    at /home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/bundler.js:1933:13
    at /home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/bundler.js:2147:20
    at /home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:245:19)
    at Object.exports.bundle (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/bundler.js:2040:31)
    at /home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:554:24
    at time (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/profile.js:231:28)
    at Function.run (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/profile.js:377:12)
    at bundleApp (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:544:34)
    at [object Object]._.extend._runOnce (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:591:35)
    at [object Object]._.extend._fiber (/home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:821:28)
    at /home/s2/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:402:12
    - - - - -
```

Any ideas?

**Comment by egrigolon** [comment] 2015-06-12 21:20
I solved the issue. I just removed the entire directory and cloned it again. It's working now! Thanks everyone.

@mquandalle I'd add this to the official readme so people can also run it as standalone mode.

**Comment by ePirat** [comment] 2015-06-13 12:15
Please note, just running `meteor` command is not the correct way to set up a production server, it is only intended for development!

**Comment by ePirat** [comment] 2015-06-13 12:33
The correct steps to set up libreboard for production use are the following:

1. Clone the git repository
    ```sh
git clone https://github.com/libreboard/libreboard.git`
    ```
   (This clones the latest development version, use a tag instead if you want a stable one)

2. Install meteor, follow the [guide on their website](https://www.meteor.com/install) to do so.

3. Change to the directory you just cloned and execute the meteor build command:
    Make sure the directory you specify for the build command is __not__ in your project directory and it's empty or does not exist, else it will be deleted recursively!
    ```sh
cd ./libreboard && meteor build ../libreboard-build --directory
    ```

4. Change to the build server directory and install dependencies:
    ```sh
cd ../libreboard-build/bundle/programs/server && sudo npm install
    ```

5. Change back to be base build directory
   ```sh
cd ../../../
    ```

6. Set the needed environment variables:  
    In order to run, you need to set some env varaibles:
    ```sh
export MONGO_URL='mongodb://127.0.0.1:27017/libreboard'
export ROOT_URL='https://example.com'
export MAIL_URL='smtp://user:pass@mailserver.example.com:25/'
export PORT=8080
    ```

7. Run the server
    ```sh
node main.js
    ```

**Comment by ePirat** [comment] 2015-06-13 12:38
Oh and obviously you need to have mongodb installed and set up correctly.

**Comment by egrigolon** [comment] 2015-06-13 16:26
Thanks @ePirat I'll definitely try it out. Right now I'm just running it on a dev environment and already notice some bugs like Full Name note showing correctly in the field or even available in the members search. Probably because I'm just simply running ```meteor```. Thanks again!

**Comment by ePirat** [comment] 2015-06-13 16:34
Most of the bugs are due to the current master is under heavy development, as a new design is worked on, and a lot of code has to be rewritten for that purpose.

**Comment by ePirat** [comment] 2015-06-13 16:35
If you need a stable version, consider either waiting for 0.9 release or use 0.8 (if possible, not sure if it is still available)

**Comment by ePirat** [comment] 2015-06-14 12:32
I have added install instructions to the wiki: https://github.com/libreboard/libreboard/wiki/Install

Would be great if someone could extend the Docker section, as I have no idea how that stuff works ;)

**Comment by james-portman** [comment] 2015-06-18 22:01
Hi,

just a note,
I missed the wiki instructions as others might,
is it possible to put the install section of the wiki straight into a README file in the root of the project?

I will do it and make a pull request if it would be helpful.

**Comment by ePirat** [comment] 2015-06-19 03:18
I don't think that is a good idea right now. Maybe a link only, if really necessary. Those instructions will change when 0.9 is realeased and I just put them up in the wiki so that there is at least somethign there that people can use, to prevent unsafe installations.

**Comment by xiaohelong2005** [comment] 2015-07-15 01:24
@ePirat message is in detail,I hope there is a official document  book or reference.

**Comment by xiaohelong2005** [comment] 2015-07-15 04:33
Thanks @ePirat,follow your wiki,when install ,some problems happened to me.paste as follows,just for advising.

Content:

**Comment by xiaohelong2005** [comment] 2015-07-15 05:05
5.	throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
	      ^
Error: `/home/long/libreboard/.build/bundle/programs/server/node



Node fibers have to be re-installed after unpacking the bundle. To fix this problem go to the server directory.

$ cd bundle/server
Then un-install fibers

$ npm uninstall fibers
Then install fibers

$ npm install fibers
Then start your application

$ cd ../
$ PORT=3000 
$ MONGO_URL=mongodb://localhost:27017/myapp 
node bundle/main.js


 @ePirat,the end 
/home/long/libreboard/.build/bundle/programs/server/node_modules/fibers/fibers.js:16
	throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
	      ^
Error: `/home/long/libreboard/.build/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.28/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/home/long/libreboard/.build/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/long/libreboard/.build/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)


I have failed...
why installing is so complicated ,not tar and run as a shell, in China , to visit the site abroad ,the speed is harrassed.

**Comment by ePirat** [comment] 2015-07-15 09:34
> why installing is so complicated

It isn't really that complicated, that's usual node apps build process.
I am not sure why you have issues with `fibers`, I can't reproduce them. BTW try not to use nodejs but node instead. (Create a symlink so that you can use node instead of nodejs)

**Comment by xiaohelong2005** [comment] 2015-07-24 03:12
please pack all resource in one package!!!

**Comment by ePirat** [comment] 2015-07-24 11:10
@xiaohelong2005 There is no new release yet and it would not make sense to package anything that is not a final release.

**Comment by mquandalle** [comment] 2015-09-01 21:41
I'm closing this issue because the OP question has been answered. If you want to continue the discussion on raw hosting, please use #90.

**Closed by mquandalle** 2015-09-01 21:41 UTC
Labels: Question, Targets
