### ISSUE TITLE
Lists placement is broken since today (3.53)

### ISSUE THREAD

**Issue by sclerc-chss** [wekan/wekan#2800] opened 2019-11-15 09:39 UTC
**Server Setup Information**:

* Did you test in newest Wekan?: yes 
* Wekan version: 3.53.0
* Operating System:Debian 9.9
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Node Version: 8.16.2
* MongoDB Version: 3.2.22
* What webbrowser version are you using? bug confirmed on Firefox 68.2.0esr, Chrome 78, Vivaldi 2.8, Edge 42

**Problem description**:
A new list is automatically created at the beginning of the table. 
If I want to move a list, it is automatically moved at the beginning of the table.

I tried to change the mode of the new option "Sort the list By" but there isn't any change of comportement.

In my old tables created before this update, the placement of existing lists has been modified without any action.

![B8H07EpXBM](https://user-images.githubusercontent.com/53857862/68933100-3f7e0880-0794-11ea-92b3-18aece07092d.gif)

Thank you.

**Comment by xet7** [comment] 2019-11-15 09:57
@whowillcare 

I don't understand how list sorting feature works. I have changing code related to it:
https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v353-2019-11-14-wekan-release

In Wekan v3.51, I received bug report that order of sorting was reversed. Now with Wekan v3.53 I get this bug report.

Could sorting be visible and working in desktop mode both with and without drag handles? And that sorting by name would work correctly?

**Comment by hever** [comment] 2019-11-15 11:04
Me too - _In my old tables created before this update, the placement of existing lists has been modified without any action._

**Comment by xet7** [comment] 2019-11-15 12:40
Currently @whowillcare is one of the biggest, greatest and most active Wekan contributors, as I have mentioned [at wiki](https://github.com/wekan/wekan/wiki/Team). He has contributed many features and fixes to Wekan. Usually, when he has time, he replies and adds fixes to features he has added, like before.

In general, it does not matter if original order of lists has been lost. When @whowillcare has fixed this, it's a very good feature to be able to sort lists by name etc.

**Comment by amgfreak** [comment] 2019-11-15 12:59
I do also have the same issue with wekan 3.53 (installed with snap) on Ubuntu 18.04 since today. As I've noticed, the problem occurs only in "Swimlanes" view, not if I've chosen list view.
@hever @sclerc-chss is this behaviour the same with you?

**Comment by sclerc-chss** [comment] 2019-11-15 13:06
I use only the swimlanes view so I don't think to test in list view.

I haven't the problem in list view too.

**Comment by nickbe** [comment] 2019-11-15 14:26
You have to set the sort order to manual if you want the same list order than before.

**Comment by sclerc-chss** [comment] 2019-11-15 14:29
@nickbe I'm in manual mode and I can't retrieved the same list order than before (in swimlanes mode)

**Comment by whowillcare** [comment] 2019-11-15 14:35
When you choose to show drage handles in your own preference setting in
desktop mode, your previous orders will be back. or in sort mode to choose
to sort by manual i believe, then your original order will be restored

**Comment by whowillcare** [comment] 2019-11-15 14:36
I haven't tested in swimlanes mode b4. I will take a look when I have time.

**Comment by amgfreak** [comment] 2019-11-15 15:02
This worked for me, thank you @whowillcare!
> When you choose to show drage handles in your own preference setting in desktop mode, your previous orders will be back. or in sort mode to choose to sort by manual i believe, then your original order will be restored
> […](#)

**Comment by sclerc-chss** [comment] 2019-11-15 15:15
@whowillcare It works for me too with this "trick" but I would like to can hide this in a normal use (I find that this mode pollute the table).

Thank you for your help !

**Comment by TheMasterFX** [comment] 2019-11-15 18:01
In my opinion there should be a possibility to make the order fixed by the board creator!?

**Comment by mikesutton** [comment] 2019-11-17 21:20
@whowillcare are you saying this is intended behaviour or that the 'show drag handles' is the workaround for an unintended behaviour.

I am struggling to see a use case for a list jumping to the first position to the left on save.

The 'drag handles' trick does work but introduces visual issues because of the handle and long titles. Unfortunately this is makes creating new boards a completely unpleasant experience. 

Also I don't thing lists should be sorted any other way than manually - perhaps allow multiple lists to be moved at the same time, but any other 'magic' to sort them defeats the general use cases of a flow.

Perhaps if a board is used as a kind of CRM, where each list represents a contact - not a flow, and the cards represent stuff about the contact, one might sort the lists alphabetically. But that use case would not be a typical kanban one.

What can we do to get this fixed?

**Comment by nickian** [comment] 2019-11-17 23:18
I noticed the list order is broken on my Snap installation as well. This new features is not at all intuitive. Why not test this kind of thing more thoroughly and make sure there are no breaking changes before release to snap auto-updated installations?

**Comment by xet7** [comment] 2019-11-18 01:54
I will look at at this a little, but if I can't figure out how to get this working, I will remove this feature in near future.

**Comment by xet7** [comment] 2019-11-18 02:17
@nickian 

It's not possible for me to test for everything, Wekan users report all kinds of bugs that I did not even notice at all.

**Comment by hever** [comment] 2019-11-18 08:30
@mikesutton 
> Also I don't thing lists should be sorted any other way than manually

I think so. What is the idea of anyhow sorting lists coming from?

This update is really problem, many users call me for help - they absolutely don't know what happens to theirs board a trying to repair it.

**Comment by nickbe** [comment] 2019-11-18 08:55
I also have to agree. This new feature seems rather unneccessary to me.  We're using wekan with dozens  of boards now, but I can't image why it should be possible to reorder them in another way. 

Since the problem with mobiles and the accidential movement of columns persists I thought someone was messing with my board columns. btw. Is there a solution for problem on mobiles in sight?

**Comment by xet7** [comment] 2019-11-18 09:38
@nickbe 

At mobiles there is already solution for accidental movement, there is more drag handles, other parts of Swimlanes/Lists/Cards are used for moving around board without dragging.

If on mobile you request desktop website, you can enable `top right your username` / `Change `Settings` / `Show desktop drag handles` so that desktop version of Wekan works better on mobile with drag handles.

Drag handles are not yet added to Checklists and Subtasks #2081 , maybe sometime later they could also be added.

**Comment by amgfreak** [comment] 2019-11-18 11:46
@mikesutton I do also have visual issues, e.g. with long list names. I agree with @TheMasterFX that it could be useful for many users if they have an opportunity to fix list order, maybe as a similar setting like it already exists to show drag handles.

**Closed** 2019-11-18 20:26 UTC

**Comment by nickbe** [comment] 2019-11-19 10:35
Would it not be better to simply turn of dragging columns on mobiles?
