### ISSUE TITLE
Missing proper error handling on logout

### ISSUE THREAD

**Issue by guppie70** [wekan/wekan#450] opened 2015-12-21 14:29 UTC
The current version of Wekan (0.9) does not properly handle logout/session loss.
When a user is working in Wekan, leaves for lunch break, and then comes back to his PC - he has probably been logged out in Wekan. The application however does not report this. It remains fully functional without any message to the user that his session is lost and that he needs to login again...
We have had multiple occasions where users lost hours of work due to this problem!
Please implement proper Ajax error handling so that the application detects when a user session is terminated and that there is a need to login again.
Many thanks in advance!

**Comment by mquandalle** [comment] 2015-12-21 14:44
That’s strange, I never experienced such a problem.

Technically speaking we don’t use Ajax requests to communicate between the client and the server, but instead we rely on a stateful websocket connection. If this connection is closed, the client will try to reconnect regularly using an authentication token kept in the browser local storage (so there is no need to login again). And by the way, this isn’t a protocol I designed, this is all standard from the Meteor platform.

One thing we definitely need to solve is reporting disconnection in the UI,  probably with a notification on top of the screen saying “Disconnected, will try to reconnect in 8 seconds”. That’s should be pretty easy to implement, and would prevent users to lose changes.

But for the actual disconnection issue, I don’t know what the problem is. It may be related to your deployment environment (for example, maybe websocket are not enabled, in which case the application fall back into HTTP long polling). Also, feel free to talk with me by email, I always like to know who is using Wekan in production :)

**Comment by guppie70** [comment] 2015-12-21 15:23
Hi Maxime,

Thank you so much for your quick reaction!
Am not sure what is actually making our situation unique/different from how others are using the Wekan software.
Your suggestion for a clear message (“Disconnected, will try to reconnect in 8 seconds”) would be highly appreciated by my team members! Maybe the authentication token has an expiry date after which it’s not valid anymore? And when the application attempts to use it after that date is passed, there is no possibility anymore to automatically restore the connection?
We have found that a simple “hard refresh” (i.e. shift+reload) is sufficient to check if the user needs to login again.
The “funny” thing is that the complete application seems to work even when the web socket connection is closed: dragging & dropping cards, creating new cards, etc. All is working normally. Hence the user has no clue that something is wrong and simply continues his work.
If you give me your email address I can explain in a bit more detail how we are using your application.
Regards,


Johan.

**Comment by mquandalle** [comment] 2015-12-21 17:30
Let's talk about the disconnect indicator in #451, so I can close it when it gets resolved and keep this issue open until we figure out the connection problem.

The fact that the application works offline is by design, it's useful when you have latency between the client and the server and you don't want to wait 2 seconds after pressing <kbd>Enter</kbd> to see your card appear on the board.

You can contact me at mquandalle [at] wekan [dot] io.

**Comment by xet7** [comment] 2017-05-06 22:12
Reconnecting works with refresh at least, and logout seems to work currently.

**Closed by xet7** 2017-05-06 22:12 UTC
Labels: Bug
