### ISSUE TITLE
Can't login to Wekan.io

### ISSUE THREAD

**Issue by elmarti** [wekan/wekan#745] opened 2016-12-06 15:15 UTC
I've tried multiple browsers (ie, Firefox, Chrome), no error response simply the following is logged. Perhaps a network issue?

![cantlogintowekan](https://cloud.githubusercontent.com/assets/4789968/20930838/df985644-bbc6-11e6-9b31-70d65704950d.png)

**Comment by ocdtrekkie** [comment] 2016-12-06 15:21
This is usually caused by some sort of SSL error. It's worth noting that Wekan.io's SSL cert from Cloudflare is very recent (12/4/2016). With SSL errors, it's always worth double checking your own date and time settings.

As a note: The maintainer of Wekan has been very silent for the last several months, so you should not assume if something happens to Wekan.io that it will be fixed.

**Comment by AlexanderS** [comment] 2016-12-06 18:45
The certificate from `ddp.wekan.io` is expired on 2016-10-15 05:08 PM.

**Comment by ocdtrekkie** [comment] 2016-12-06 19:24
Strange, since the certificate covering wekan.io itself is a wildcard cert.

**Comment by xet7** [comment] 2017-03-24 17:56
Wekan now uses GitHub pages at https://wekan.github.io and forum has been moved so at forum at least password and GitHub login works now.

**Closed by xet7** 2017-03-24 17:56 UTC
