### ISSUE TITLE
.build folder not generated during manual installation

### ISSUE THREAD

**Issue by johnc1984** [wekan/wekan#230] opened 2015-08-03 12:47 UTC
https://github.com/libreboard/libreboard/wiki/Install

From the manual installation guide:
```meteor build .build --directory```

Running this command ends with:
```Killedating package catalog ```

The libreboard directory contents are:
drwxrwxr-x 9 john john 4096 Aug  3 13:34 .
drwxr-xr-x 8 john john 4096 Aug  3 13:34 ..
-rw-rw-r-- 1 john john  129 Aug  3 13:34 bower.json
drwxrwxr-x 5 john john 4096 Aug  3 13:34 client
drwxrwxr-x 2 john john 4096 Aug  3 13:34 collections
-rw-rw-r-- 1 john john 2175 Aug  3 13:34 Contributing.md
-rw-rw-r-- 1 john john  289 Aug  3 13:34 Dockerfile
drwxrwxr-x 8 john john 4096 Aug  3 13:34 .git
-rw-rw-r-- 1 john john   51 Aug  3 13:34 .gitignore
drwxrwxr-x 2 john john 4096 Aug  3 13:34 i18n
-rw-rw-r-- 1 john john 1939 Aug  3 13:34 .jscsrc
-rw-rw-r-- 1 john john 1751 Aug  3 13:34 .jshintrc
-rw-rw-r-- 1 john john 1100 Aug  3 13:34 LICENSE
drwxrwxr-x 2 john john 4096 Aug  3 13:34 .meteor
drwxrwxr-x 2 john john 4096 Aug  3 13:34 public
-rw-rw-r-- 1 john john 1200 Aug  3 13:34 README.md
-rw-rw-r-- 1 john john 4398 Aug  3 13:34 sandstorm.js
-rw-rw-r-- 1 john john 3874 Aug  3 13:34 sandstorm-pkgdef.capnp
drwxrwxr-x 4 john john 4096 Aug  3 13:34 server
-rw-rw-r-- 1 john john  211 Aug  3 13:34 .travis.yml

No .build folder, this renders the rest of the guide impossible to follow. Being completely new to meteor i wouldn't know where to begin debugging this :/

I have the latest node and mongo installed.

**Comment by ePirat** [comment] 2015-08-21 17:15
As this isn't a real bug of libreboard as far as I know, I am not sure if it belongs here, anyway. Could you provide me with the full output of the `meteor build .build --directory` command?

**Comment by hue-plu** [comment] 2015-09-01 08:13
OS:
arch linux latest
.build directory was not created when I build this in memory 512M  VM. ( Especially error did not go out )
Change the setting in memory 1G, has been .build directory is created where it was performed again .

※Although it might not matter and, if it is helpful

**Comment by mquandalle** [comment] 2015-09-20 20:52
I'm closing this because it’s probably not a bug with Wekan. Feel free to open a thread on the new [forum](http://discuss.wekan.io) if you encounter any issue during Wekan installation.

**Closed by mquandalle** 2015-09-20 20:52 UTC
Labels: Question, Targets:Raw-hosting
