### ISSUE TITLE
Card and List move no longer possible

### ISSUE THREAD

**Issue by derbolle** [wekan/wekan#2771] opened 2019-10-30 12:39 UTC
## Issue
Tonight we updated Wekan 3.44 to 3.49. After the Update we noticed that we cannot move cards or lists anymore. After reverting back to 3.44 it worked again.

**Server Setup Information**:

* Did you test in newest Wekan?: yes

* Wekan version: 3.49

* Operating System: Docker Swarm on Debian 10

* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker Swarm with docker-compose file

* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Traefik reverse Proxy

* Node Version: 8.16

Mongo Version 4.0.11

* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Firefox 69 and Chrome

**Comment by jhgovsi** [comment] 2019-10-30 13:00
I can confirm the same. Workaround (I hope this is not intended feature from now on):

**Change Settings -> Show desktop drag handles**

Otherwise, card dragging is disabled on desktop!

**Comment by NoxInmortus** [comment] 2019-10-30 15:37
Hello, I do reproduce the issue, and I confirm it is resolved by enabling "Show desktop drag handles".
Even if it works after that, there is now a sort of cross on every card, and it's reducing card names visibility.

Also, I can drag and drop only clicking on the cross, not anywhere on the card like before. I understand this feature (to not move cards by accident), but something feel a bit like a step back :/

**Comment by alexanderadam** [comment] 2019-11-01 08:41
Is there a PR for this fix in the work?

**Comment by xet7** [comment] 2019-11-01 20:07
@alexanderadam 

There will not be PR, because I'm maintainer of Wekan, and will commit fix directly to repo master branch when it's ready.

**Comment by alexanderadam** [comment] 2019-11-03 07:26
Okay, just to be sure: so the only possibility is to get notified by subscribing this issue, right?

**Comment by jhgovsi** [comment] 2019-11-13 09:59
any news on progress of fixing this rather critical (regarding the user acceptance within our team) issue?

**Comment by bkraul** [comment] 2019-11-13 12:42
@jhgivsi It's a little bit of bad timing. I was actually in the middle of introducing wekan to our team, but the  moving the cards is central to the usability of the project...Thanks for looking into this, @xet7

**Comment by derbolle** [comment] 2019-11-13 12:43
Hello jhgovsi, 
As stated by xet7 the 3.49 should Work. If not: we Use version 3.44 wäre dragging works as intended


> Thanks for testing, I will look how it works on those browsers.
> 
> You are running newest commits from master branch.
> 
> Actual Wekan v3.49 is at docker image tag v3.49:
> 
> ```
> image: quay.io/wekan/wekan:v3.49
> ```
> 
> Or alternatively from Docker Hub:
> 
> ```
> image: wekanteam/wekan:v3.49
> ```
> 
> https://github.com/wekan/wekan/blob/master/docker-compose.yml#L118

**Comment by bkraul** [comment] 2019-11-13 13:18
Missed that. Thanks for pointing it out @derbolle . I have set this to 3.49 and board is fully functional. Thanks!

**Closed** 2019-11-13 17:36 UTC
