### ISSUE TITLE
Card details view page not found error

### ISSUE THREAD

**Issue by k4r7u** [wekan/wekan#624] opened 2016-06-10 07:54 UTC
When running Wekan in a subdir though an Apache proxy the URL for the card details view contains a '/' too much and results in a page not found error:
![image](https://cloud.githubusercontent.com/assets/8782287/15957698/0c8b2a86-2ef1-11e6-9ae9-6a8bbb1c6689.png)
https://example.com/wekan//b/4zpAbTm6AxxZW7rf7/work/jkjaqJCGhgTcXhGKT
The board itself is shown fine: https://example.com/wekan/b/4zpAbTm6AxxZW7rf7/work

If I remove one slash from the URL of the card details view, it is shown as expected.

**Comment by valqk** [comment] 2016-08-08 13:01
I have exactly same problem. If I remove // before //b and url goes like /b everything is OK.

**Comment by AlexanderS** [comment] 2016-08-08 13:07
Do you have a trailing `/` in your `ROOT_URL` environment variable?

**Comment by valqk** [comment] 2016-08-08 14:11
I did think it was my mistake at first and removed it, but with or without it's the same - Only card comment url gets double slash.
If you tell me where should I look for it I'll push a PR.

**Comment by AlexanderS** [comment] 2016-08-08 14:47
Can you please try something like `Meteor.absoluteUrl('b')` in the javascript console of your browser? Does this include the doubled `/`, too?

**Comment by valqk** [comment] 2016-08-08 20:41
It says: "http://example.com/wekan/b"

**Comment by kurtteichman** [comment] 2016-08-13 18:19
I can get the same output as valqk, but the issue still remains. I do not have a trailing slash in the ROOT_URL.

Thanks for the reference @AlexanderS

**Comment by AlexanderS** [comment] 2016-08-13 19:12
I do not know why this happens, but I will look into it. (But maybe not before Monday.)

**Comment by AlexanderS** [comment] 2016-08-15 15:31
Can somebody please evaluate the following lines (in the javascript console of your browser):

```js
FlowRouter.url('card', {boardId: 'board', slug: 'board-slug', cardId:'card'})
FlowRouter.path('card', {boardId: 'board', slug: 'board-slug', cardId:'card'})
FlowRouter._basePath
__meteor_runtime_config__.ROOT_URL
__meteor_runtime_config__.ROOT_URL_PATH_PREFIX
```

The issue might by in the [kadirahq/flow-router](https://github.com/kadirahq/flow-router) package. I think the issue might be, that `_basePath` in https://github.com/kadirahq/flow-router/blob/master/lib/router.js#L6 does not contain a trailing slash.

**Comment by kurtteichman** [comment] 2016-08-15 15:48
```
FlowRouter.url('card', {boardId: 'board', slug: 'board-slug', cardId:'card'})
"https://server.org/wekan//b/board/board-slug/card"
FlowRouter.path('card', {boardId: 'board', slug: 'board-slug', cardId:'card'})
"/wekan/b/board/board-slug/card"
FlowRouter._basePath
"/wekan"
__meteor_runtime_config__.ROOT_URL
"https://server.org/wekan"
__meteor_runtime_config__.ROOT_URL_PATH_PREFIX
"/wekan"
```

**Comment by AlexanderS** [comment] 2016-08-15 16:08
Yes, like expected. Flow router removes the `PATH_PREFIX` and supplies the remaining URL to `Meteor.absolutUrl` with the trailing `/` and that results in the double slash.

As quick fix, can you try to add the following in `config/router.js` (f.e. just at the top of the file):

```js
if (FlowRouter._basePath) {
    FlowRouter._basePath = FlowRouter._basePath + '/';
}
```

**Comment by kurtteichman** [comment] 2016-08-15 17:06
Thanks for that. I've had a few issues building meteor with a fairly modern version of nodejs. I'll see if I can give it another try a little later on tonight. Thanks a bunch for the help.

**Comment by AlexanderS** [comment] 2016-08-15 17:17
Note: The meteor version currently used by wekan requires node-0.10.x (see also #634)

**Comment by valqk** [comment] 2016-08-15 22:30
I'm using docker from mquandalle/wekan:latest
I've just changed the /app/config/router.js , restarted the docker (using docker-compose as in docs)
but nothing changed. I still get double //b/ url and in console:
`
FlowRouter.url('card', {boardId: 'board', slug: 'board-slug', cardId:'card'})
> "http://exmplae.com/wekan//b/board/board-slug/card"
FlowRouter.path('card', {boardId: 'board', slug: 'board-slug', cardId:'card'})
> "/wekan/b/board/board-slug/card"
FlowRouter._basePath
> "/wekan"
__meteor_runtime_config__.ROOT_URL
> "http://example.com/wekan"
__meteor_runtime_config__.ROOT_URL_PATH_PREFIX
> "/wekan"
`

maybe I should compile/populate some way the code?
p.s. If I go and check the code
`if (FlowRouter._basePath) {
    FlowRouter._basePath = FlowRouter._basePath + '/';
}`
is on the top of /app/config/router.js - just after the let.
I do something wrong or it's anoter issue on my side?

**Comment by AlexanderS** [comment] 2016-08-15 23:32
I do not have any experience with docker, but:

```
FlowRouter._basePath
> "/wekan"
```

looks like it does not work. It should evaluate to `"/wekan/"` if the code works. So either my code does not work or the code is not running. Running the production version of a meteor app should load the minified code, so you may not find a individual file representing `/config/router.js`.

**Comment by valqk** [comment] 2016-08-16 07:17
I did find the /app/config/router.js but as you said node is using the minified version.
I'll see how to minify the app in the docker container and test and report.
Will you release this 'patch' in future releases or because it's a library problem you won't add it, because the new version of FlowRouter should fix it?

**Comment by AlexanderS** [comment] 2016-08-16 10:49
@mquandalle should decide that. But  first it would be great if someone could confirm that it will actually fix this problem.

**Comment by valqk** [comment] 2016-08-16 23:30
Hmmm... strange. I did follow the https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-from-source but I still get the same result //b/ and that's only for edit of the card but not add card.
How can I change the app version or something I can check in JS console so I'm sure I did started the new changes in source code?

**Comment by AlexanderS** [comment] 2016-08-16 23:37
You can simply add a `console.log(FlowRouter._basePath);` inside the if and watch if you get a message in your javascript console.

**Comment by valqk** [comment] 2016-08-21 11:05
Ok, so I've tested on the docker image + did git clone in another docker and tested.
When I put
`if (FlowRouter._basePath) {
    FlowRouter._basePath = FlowRouter._basePath + '/';
}`
I start getting 404s everywhere.

**Comment by cimi** [comment] 2016-09-23 12:55
I can confirm this problem still persists - I am running it under a subdirectory with a reverse proxy and everything works fine except card pages which break because of the double slash.

I can help out with a fix if someone tells me where to start digging.

**Comment by cimi** [comment] 2016-09-28 12:59
I've tried the proposed fix and I can confirm what @valqk said: appending the slash to the `_basePath` in `router.js` makes it impossible to load boards (i.e. you can't acccess anything anymore). I've tried to add it conditionally (only when it's missing, in case something else changes it) but it doesn't seem to affect anything:

```
if (!/\/$/.test(FlowRouter._basePath)) {
  FlowRouter._basePath = FlowRouter._basePath + '/';
}
```
A weird thing I did notice when debugging is that:

```
    return FlowRouter.url('card', {
      boardId: board._id,
      slug: board.slug,
      cardId: this._id,
    });
```

does __not__ call the `card` action from `router.js`, but goes directly to the router library (`packages/kadira_flow-router/lib/router.js`) where the base path gets stripped out without the slash causing the double slash to show up in the link.

So either we append the slash and the boards don't load or we don't append the slash and the cards don't load. @AlexanderS @mquandalle any thoughts?

**Comment by AlexanderS** [comment] 2016-09-28 14:41
This is the related issue in flow-router: https://github.com/kadirahq/flow-router/issues/684

This will most likely fix it: https://github.com/kadirahq/flow-router/pull/691 So let's wait until flow-router is fixed and than update the dependency in wekan to use it.

**Comment by piningforthefjords** [comment] 2016-10-03 20:50
I set up the Wekan docker environment as outlined on https://github.com/wekan/wekan/wiki/Install-Wekan-Docker-for-testing only minutes ago and found an incorrect link when trying to open the card details view. All other links point to the server IP while the card details view point to localhost, which obviously doesn't work from an external client. 
The attached screen shot is taken while hovering over a card.
![skarmdump1](https://cloud.githubusercontent.com/assets/1346646/19053535/9f0b9dbc-89bb-11e6-9e7a-0c9eb6f48ecd.jpg)

**Comment by AlexanderS** [comment] 2016-10-04 15:04
@piningforthefjords Just to be sure: You adjusted the `ROOT_URL` setting in the example?

**Comment by piningforthefjords** [comment] 2016-10-04 19:08
@AlexanderS Not sure, and unfortunately I already dropped the docker files (really likes the UX but missing an admin panel). If the cards is the only place ROOT_URL is used I probably missed it.

**Comment by fr4g3r** [comment] 2016-10-04 20:39
The `ROOT_URL`  is the URL where the redirect happens, therefore its probably that you used your localhost address.

**Comment by baracoder** [comment] 2016-10-12 22:18
A workaround for now: match the url with double slash and redirect on the server

**Comment by valqk** [comment] 2016-10-23 11:54
Any news on this issue? It's a showstopper for me.

**Comment by cimi** [comment] 2016-10-25 09:22
This action on this issue (or lack thereof) has made me stop considering using wekan - I've switched to a different solution.

**Comment by jodumont** [comment] 2016-10-28 13:20
I add this issue with the docker-image
Like people said I correct my **ROOT_URL=** and everything work fine now :)

**Comment by rka** [comment] 2017-01-24 13:37
Any update on this maybe? 
My ROOT_URL is http://example.example.com/wekan im pretty sure i set this up the right way.

**Comment by mnewmedia** [comment] 2017-01-24 13:44
Seems like project was only driven by @mquandalle and like its expectable if a project depends on one person, if the person got to do other stuff the repo will sleep until he has time again or somebody else jumps in.
So.... ... .. . =)

**Comment by nammn** [comment] 2017-01-24 13:47
@mquandalle is the owner of the repo. As of this reason this project sadly has died. 
But there is a fresh fork, which is currently developed.
https://github.com/wefork/wekan

@rka did you try the work? Else you could try caddy? this one seems to work.

**Comment by rka** [comment] 2017-01-24 13:51
Thanks ill try the other fork

**Comment by jaimeagudo** [comment] 2017-01-25 13:12
happening again https://github.com/kadirahq/flow-router/issues/684

**Comment by Jeansen** [comment] 2017-02-04 18:41
Same here. Just came across this project. So I followed the instructions to run the two docker containers to have a first look and try things out. But after creating a card and clicking on it, I get the error: Board not found.

**Comment by mnewmedia** [comment] 2017-02-04 21:12
@Jeansen repo dead look at https://github.com/wefork/wekan

**Comment by ocdtrekkie** [comment] 2017-02-04 22:17
@mnewmedia No, repo is no longer dead. Wefork is being migrated back into Wekan!

**Comment by netvandal** [comment] 2017-02-13 10:30
I'm facing the same problem with a custom install using nginx as proxy. flow-router seems up to day and nothing else seems broken, but I can't access the card details as a double // is added. How could i help to debug this?

**Comment by NegativeFeedback** [comment] 2017-02-21 04:29
both of the above suggestions did not resolve this in my case.

**Comment by Jeansen** [comment] 2017-03-12 20:20
Check this out: https://hub.docker.com/r/mquandalle/wekan/tags/
Instead of running with the latest tag, try 0.10. This works for me, e.g.:
`docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://localhost:8181" -p 8181:80 mquandalle/wekan:0.10.0
`

**Comment by xet7** [comment] 2017-03-13 06:48
@Jeansen 

v0.10 was released 2015-12-22, does not include Checlists etc.

v0.13 was released yesterday.

Moved to #785

**Comment by dirk-olmes** [comment] 2017-07-21 00:07
The problem persists using the latest v0.28 container. My ROOT_URL is something like https://www.example.com/wekan (no trailing slash) and only the link for opening a card is affected.

**Comment by xet7** [comment] 2017-07-21 15:47
@dirk-olmes 

Do you mean Docker or Ubuntu snap?

**Comment by dirk-olmes** [comment] 2017-07-21 17:03
It is this Docker image : https://hub.docker.com/r/wekanteam/wekan/

**Comment by valqk** [comment] 2017-07-24 10:49
There is a regression in docker image mentioned above.
I've just updated to solve a 100% CPU usage and I got this issue again...

**Comment by xet7** [comment] 2017-07-24 18:45
@dirk-olmes @valqk 

I updated Docker image of wekanteam:latest. It should be fixed now, please test.

**Comment by valqk** [comment] 2017-07-24 22:03
Nope. After stop+pull+start+reload in browser still has double // 

> #> docker pull wekanteam/wekan
> Using default tag: latest
> latest: Pulling from wekanteam/wekan
> Digest: sha256:b83cfbae2e3e06c82752adeb93643b7a48b8ace306dea8a49f43f1fa3998a948
> Status: Image is up to date for wekanteam/wekan:latest
> 
I think this Is the correct image:

> #>docker image ls
> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> wekanteam/wekan     latest              0ff951295b79        10 hours ago        422MB
> wekanteam/wekan     meteor-1.4          b65052b0d93f        2 days ago          415MB
> mongo               latest              9c4b5d74399d        12 months ago       327MB
>

**Comment by dirk-olmes** [comment] 2017-07-25 03:46
I'm using the same image as @valqk but my tests behind a mod_proxy setup on Apache and on Nginx work fine now.

**Comment by valqk** [comment] 2017-07-25 10:38
I'm sorry.
My mistake, but just saw it. I was starting meteor-1.4 image.
With latest issue is fixed.
Now everything is OK with latest image.

**Comment by xet7** [comment] 2017-07-25 12:56
Fixed at 4fdcc144d5342b6571b9e53e9a18640871e0c18b

**Closed by xet7** 2017-07-25 12:56 UTC

**Comment by deftscorpio** [comment] 2017-07-25 13:01
@xet7 How to get it fixed for non docker installations?

**Comment by xet7** [comment] 2017-07-25 13:18
@deftscorpio

I'm currently fixing those platforms that I have access to.

Basically fix is similar like at:
https://github.com/wekan/wekan/wiki/Install-and-Update#install-and-build-wekan

Before building Wekan, clone additional repos of flow-router and meteor-useraccounts to directory wekan/packages, not ~/.meteor/packages:

```
# Download Wekan
git clone https://github.com/wekan/wekan
cd wekan
mkdir packages
cd packages
git clone https://github.com/wekan/flow-router.git kadira-flow-router
git clone https://github.com/meteor-useraccounts/core.git meteor-useraccounts-core
sed -i 's/api\.versionsFrom/\/\/api.versionsFrom/' ~/.meteor/packages/meteor-useraccounts-core/package.js
cd ..
```
