### ISSUE TITLE
Prevent Wekan from sending mail about selfmade changes

### ISSUE THREAD

**Issue by niklasdahlheimer** [wekan/wekan#2317] opened 2019-04-05 16:29 UTC
## Prevent Wekan from sending mail about selfmade changes

**Server Setup Information**:

* Wekan version: V2.48.0
* Operating System: DSM/Synology
* Deployment Method: Docker
* Node Version: v8.15.1
* MongoDB Version: 3.6.4

**Problem description**:

Currently every time a user moves/adds/removes/etc. a card he/she is receiving a mail about this changes if he/she set the board to "watching". In my opinion it is not nessecary to receive mails about changes done by myself, because you know when you done changes by yourself :)
**Is there a possibility to exclude the "editor himself" from the notification mails**?

Greetings!

**Comment by xet7** [comment] 2019-04-05 19:00
Currently Wekan only has these email notification settings. Others are not implemented yet.

![email_notification_settings](https://user-images.githubusercontent.com/15545/55650398-4603d500-57ee-11e9-8ba6-60e296569ef7.png)

**Comment by niklasdahlheimer** [comment] 2019-04-05 21:48
Hey Lauri! Thanks for responding!
Actually I do not ask for more notification settings, I just wanted to discuss with you guys if it makes sense like Wekan is behaving right now: Sending users unnecessary mails about their own actions. It's like Github and any forum would send me mails everytime I write or comment on a post. That's not the way notifications should work, should they?

**Comment by xet7** [comment] 2019-04-06 04:17
@niklasdahlheimer 

Yes, GitHub does send me emails about comments that I posted using webbrowser. Above functionality about email notifications was designed by author of Wekan and did exist in Wekan before I started maintaining Wekan at 2016-12.

In current Wekan, admin user can also set automated Rules that do actions like move card when user is not logged in. Those also send email, if watching etc.

Wekan is combined effort of every Wekan contributor that has added PR etc to Wekan to add features etc. Anyone is free to add PR to add new email behaviour. Wekan code is well structured, so it's possible to figure out where to make required changes.

There could be similar open issues about email behaviour already, I have not looked at them yet.

**Comment by chrkoe** [comment] 2019-05-08 09:29
> There could be similar open issues about email behaviour already, I have not looked at them yet.

like #1631 ?

I'm also very interested in this feature. Is there any plan to work on it?

**Comment by xet7** [comment] 2019-05-08 15:11
@chrkoe 

I am current maintainer of Wekan. I also provide Commercial Support for Wekan https://wekan.team . You can contact me at x@xet7.org .

**Comment by rodrigocipriani** [comment] 2019-05-29 18:08
I also need it ❤️

**Comment by saschafoerster** [comment] 2019-09-08 20:18
@xet7 this here is a duplicate of #1631, so I guess @niklasdahlheimer and @gpelouze 's request can be joined. I will add my +1 for less notification spam. :)

**Comment by xet7** [comment] 2019-09-09 08:09
Moved to #1631

**Closed by xet7** 2019-09-09 08:09 UTC
