### ISSUE TITLE
Can't see card comments with Chrome

### ISSUE THREAD

**Issue by tscrip** [wekan/wekan#656] opened 2016-07-26 21:59 UTC
On Chrome version 51, I have to hover over the comments entry box in order for the comments to show up. I have tried in FireFox and this does not seem to be an issue.

**Comment by xet7** [comment] 2016-08-01 20:41
@tscrip 

What version Wekan?

- Docker Wekan latest ? See #659 .
- Docker Wekan 0.10 ? I use this, seems not affected on Chrome 52.
- Git repo, what branch ?
- Sandstorm version ?

**Comment by tscrip** [comment] 2016-08-02 04:42
I am running 11 rc2. This is running on a virtual CentOS server.
I am not using sandstorm. I am manually running the main.js or whatever it is with node. 
I also noticed in version 10 this was not an issue.

**Comment by AlexanderS** [comment] 2016-08-03 17:18
This seems to be caused by bda1df5ada4cc086e4e05748f8019afbb24e0117 and is a result of #646.

**Comment by mkoitka** [comment] 2016-09-19 11:41
Just commenting to add, that since 0.11 this bug is present for me in all major browsers (Windows 10, FF, Chrome, IE, Edge)

**Comment by xet7** [comment] 2017-02-03 09:03
I think this is already fixed in latest Wekan, for example Docker image. Closing issue.

**Closed by xet7** 2017-02-03 09:03 UTC
Labels: Bug
