### ISSUE TITLE
Users Still Visible after being deleted.

### ISSUE THREAD

**Issue by lslamp** [wekan/wekan#1614] opened 2018-04-30 13:40 UTC
## Issue

**Server Setup Information**:

* Operating System: Ubuntu 16.04.4 LTS
* Deployment Method(snap/sandstorm/mongodb bundle): sandstorm
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): 
* Node Version: ??
* MongoDB Version: ??
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):https://hyvasand.sandcats.io/grain/fpJnwC2fTtbT9LsHakArBw/b/sandstorm/libreboard

**Problem description**:
I have been running Wekan for a number of months now and I am very happy, the issue that I am facing is that I have added a user that joined the company, and he was only here for 2 months when he was asked to leave. So I deleted the user account from the portal. Now when I open wekan, the user is still listed.
![image](https://user-images.githubusercontent.com/6013759/39429873-9563e59a-4c8c-11e8-9668-8852afa2fa8b.png)
In Wekan the user is still listed.
![image](https://user-images.githubusercontent.com/6013759/39429923-b70fadf0-4c8c-11e8-8658-50cf6c1f6c81.png)

How can I remove this user. I do not want to see the deleted user.

Thanks
Lawrence

**Comment by ocdtrekkie** [comment] 2018-04-30 13:42
It isn't possible currently to remove them from appearing on Wekan on Sandstorm. The reason being is that Wekan grains cannot see if you have removed them on Sandstorm. If Wekan allowed you to remove them, it would be possible for you to believe you removed them, while they may still have permission to access the board on Sandstorm.

**Comment by ocdtrekkie** [comment] 2018-04-30 13:43
This is a duplicate of #1192.

**Comment by lslamp** [comment] 2018-04-30 13:51
Is there no way to delete them from both Wekan and SandStorm?

Lawrence

**Closed** 2018-04-30 13:52 UTC

**Comment by ocdtrekkie** [comment] 2018-04-30 13:58
Currently not. I just proposed a possible option in the existing issue, if you want to subscribe to that issue report, you'll get notifications on any further discussion.
