### ISSUE TITLE
Can't add user to board

### ISSUE THREAD

**Issue by Icsab** [wekan/wekan#4009] opened 2021-09-15 09:24 UTC
When I'm trying to add a member to a board using the REST API add_board_member (/api/boards/{board}/members/{user}/add) the response is always empty, the status code is 200.  If I change the board ID or the user ID to a value that doesn't exist, the status code is still 200 and the response is empty.  

**Server Setup Information:**

- Wekan Version	5.58.0
- Meteor version	2.2
- Node version	12.22.6
- MongoDB version	3.2.22

**Comment by xet7** [comment] 2021-09-16 06:37
@Icsab 

- Is that Snap, Source or Docker version of Wekan?
- Did you [Login to REST API](https://github.com/wekan/wekan/wiki/REST-API#example-call---as-form-data) and use returned bearer token in your add_board_member REST API call?
- Did you check [api.py](https://github.com/wekan/wekan/blob/master/api.py) for examples, do you have any API call working?
- Is there something wrong with [add_board_member REST API code](https://github.com/wekan/wekan/blob/master/models/users.js#L1915) ? Can you try to [fix and submit pull request](https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin) ?

**Comment by Icsab** [comment] 2021-09-16 09:08
@xet7 

- It's a Snap version
- yes, I'm using a bearer token to call the add_board_member REST API, in fact, the only way to get a non-empty result is to use a wrong token 
- I have a few working API calls, I'm creating a new user (works fine), a new board (works fine), I'm trying to assign the new user to this new board (not working)

**Comment by crewnew-git** [comment] 2021-09-17 09:53
> I'm trying to assign the new user to this new board (not working)

We'll need to sometimes create board & assign there but also often to assign to already created board. I understood that only the user created the board can add users there so I guess all the boards should be created by the same user that also our scripts using API are using.

**Comment by xet7** [comment] 2021-09-17 11:35
I have not looked at related API code yet, but usually if something in REST API does not work, it's possible for anyone that has written some code just to read that API code and add similar more working API calls, and send pull request. Many Wekan contributors have added more API calls as pull requests previously.

Sure I could also add those API calls, but I'm only one of the many Wekan contributors.

**Closed** 2021-09-25 15:20 UTC

**Comment by gustavengstrom** [comment] 2023-04-04 18:13
I can confirm that this still seems to be broken. @xet7 : I can start working on this and post a pull request. I prefer developing in docker. How can I get hot reloading to work?

**Comment by xet7** [comment] 2023-04-04 20:18
@gustavengstrom 

Using `meteor` command: https://github.com/wekan/wekan/wiki/Emoji

But using Docker or Windows is very very slow and unusable. It's much better to dual boot to Ubuntu or Linux Mint and develop there.

**Comment by gustavengstrom** [comment] 2023-04-04 20:30
Ok, thanks. Found this: https://github.com/wekan/wekan-dev. 

Is this perhaps an alternative? Or is it also slow?

**Comment by xet7** [comment] 2023-04-04 20:39
@gustavengstrom 

I have not used wekan-dev . I only use https://github.com/wekan/wekan/wiki/Emoji

More specifically, I use rebuild-wekan.sh from https://github.com/wekan/wekan to install dependencies, run `meteor` command etc.

**Comment by gustavengstrom** [comment] 2023-04-05 20:20
@mfilser:  did not get this to work immediately so I decided to go with @xet approach instead. I have submitted a pull request which should solve the above problem. Note, however that the API docs are missing that the action string must be set to ´add´
