### ISSUE TITLE
"My Cards" Section not showing my cards

### ISSUE THREAD

**Issue by luistiktok** [wekan/wekan#4395] opened 2022-03-05 18:20 UTC
Hello, I'm using Wekan docker version 6.11.0 on Ubuntu 20.04. For some reason I cannot seen any card assigned or created by me under "My Cards" section. Myabe i'm missing something or is a bug. Thank you.

**Comment by subashsn** [comment] 2022-03-10 09:21
Cards not showing up in My Cards or Due Cards also

Same. Tried assigning it, due date, etc.

**Comment by subashsn** [comment] 2022-03-10 09:38
**Confirmed** that it **works in v6.09**, but **doesn't work since 6.10**. 

Error log when trying to view My cards:
```
wekan_1    | Exception from sub myCards id aooronqbjJ4rzCNHu Error: Publish function returned an array of non-Cursors
wekan_1    |     at Subscription._publishHandlerResult (packages/ddp-server/livedata_server.js:1101:20)
wekan_1    |     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1063:10)
wekan_1    |     at Subscription.MeteorX.Subscription._runHandler (packages/lamhieu_unblock.js:68:22)
wekan_1    |     at Session.MeteorX.Session._startSubscription (packages/lamhieu_unblock.js:56:7)
wekan_1    |     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
wekan_1    |     at Session.MeteorX.Session.protocol_handlers.sub (packages/lamhieu_unblock.js:27:15)
wekan_1    |     at packages/ddp-server/livedata_server.js:559:43
```

Error log when trying to view My cards:
```
wekan_1    | Exception from sub globalSearch id vPA2b3vY3Bhmc7HpA Error: Publish function returned an array of non-Cursors
wekan_1    |     at Subscription._publishHandlerResult (packages/ddp-server/livedata_server.js:1101:20)
wekan_1    |     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1063:10)
wekan_1    |     at Subscription.MeteorX.Subscription._runHandler (packages/lamhieu_unblock.js:68:22)
wekan_1    |     at Session.MeteorX.Session._startSubscription (packages/lamhieu_unblock.js:56:7)
wekan_1    |     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
wekan_1    |     at Session.MeteorX.Session.protocol_handlers.sub (packages/lamhieu_unblock.js:27:15)
wekan_1    |     at packages/ddp-server/livedata_server.js:559:43
```

Hope it helps with fixing it.

Thanks for the great tool! :)

**Comment by mfilser** [comment] 2022-03-10 10:07
I have a look at this...

**Comment by luistiktok** [comment] 2022-03-10 18:28
Good to know i am not the only one. But indeed, it is a great tool.

**Closed** 2022-03-11 10:14 UTC
