### ISSUE TITLE
search plugin/addon

### ISSUE THREAD

**Issue by Scept1c** [wekan/wekan#216] opened 2015-06-27 18:39 UTC
Hi.
It's possible add feature to search Card's, List's, Comment's, ALL things in dashboard?

At the photo on libreboard github page is icon of search.

I could not find this option in source code, maybe i was not looking too deeply.

Thx for reply.

S.

**Comment by ssimono** [comment] 2015-07-20 22:09
+1

**Comment by ssimono** [comment] 2015-07-27 14:20
I just realized that this may be a duplicate of #33...

**Comment by enriquetuya** [comment] 2016-01-15 19:08
Not having search made me discard the possibility of using wekan. That is definitely a needed feature for this kind of tools.

**Comment by zeigerpuppy** [comment] 2016-03-30 00:02
I agree that this is an essential feature, it becomes very difficult to manage a board as it grows without seach

**Comment by Umi97** [comment] 2016-05-18 08:29
+1

**Comment by laupkram** [comment] 2016-05-22 13:01
+1

**Comment by vhadjisophocle** [comment] 2016-06-30 12:26
+1

**Comment by aneocleous** [comment] 2016-07-01 07:18
+1

**Comment by GSWemigo** [comment] 2016-08-10 10:19
+1

**Comment by rhelsing** [comment] 2017-02-23 19:58
+1

**Comment by xet7** [comment] 2017-02-23 21:02
Don't add comment with +1, use thumbsup reaction.

**Comment by xet7** [comment] 2017-03-17 22:50
Moved to #552

**Closed by xet7** 2017-03-17 22:50 UTC
Labels: Feature:Search
