### ISSUE TITLE
How to begin a card title with "3. "?

### ISSUE THREAD

**Issue by sonntagd** [wekan/wekan#1421] opened 2018-01-05 11:47 UTC
## Issue
**Impacted version**: 0.63.0

**Server Setup Information**:

* Operating System: Linux
* Deployment Method: Docker
* Node Version: v4.8.7
* MongoDB Version: 3.2.18
* ROOT_URL environment variable (Is there a subfolder?): http://my.local.domain

**Problem description**:
As card titles are now also interpreted as markdown (#1334), having a title "3. ..." will render "1. ...".
I have a card naming an event that repeats yearly and now is the third iteration. I could Rename it to "3rd ..." or "Third ...", but I would be happy if this was not needed.

**Comment by brooksbecton** [comment] 2018-01-05 21:02
You could use backticks. 

Instead of putting `3. ...` in the title you would put `` `3. ...` ``

Does that work for ya'll?

**Comment by sonntagd** [comment] 2018-01-05 22:28
Yes, that works, it only looks a bit odd. Only enclosing the `3` in backticks seems to be a good workaround. But it is still not as intuitive as I'd like to have it.

**Comment by CodeBrauer** [comment] 2018-01-08 14:06
Actually this is a good and a bad thing - I loved the small feature/bug that you can render markdown in the card title. Like code/strong/italic etc. is pretty helpful.

**Comment by xet7** [comment] 2018-01-08 14:45
Having more markdown support [was added in v0.55](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v055-2017-11-19-wekan-release) and is very cool feature, it makes possible very advanced formatting. Trello does not have that feature.

Sometime emoji support will be removed from Wekan, as it breaks displaying MAC addresses etc, and it's also possible to do emojis with unicode.

I don't really know would it be possible to have markdown feature that can be turned on or off, or what should be detected in card, similar like in emoji detection, that some different kind of formatting would be used. With API and scripting or doing search-replace with text editor with exported JSON you could probably make many changes at once.

**Comment by xet7** [comment] 2018-01-08 14:45
Having more markdown support [was added in v0.55](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v055-2017-11-19-wekan-release) and is very cool feature, it makes possible very advanced formatting. Trello does not have that feature.

Sometime emoji support will be removed from Wekan, as it breaks displaying MAC addresses etc, and it's also possible to do emojis with unicode.

I don't really know would it be possible to have markdown feature that can be turned on or off, or what should be detected in card, similar like in emoji detection, that some different kind of formatting would be used. With API and scripting or doing search-replace with text editor with exported JSON you could probably make many changes at once.

**Comment by sonntagd** [comment] 2018-01-08 15:14
I also think that this markdown support is very cool. But in some situations it is not. In my case, I had existing cards which showed other information after the upgrade. The numbered list feature is a bit specific as it not only changes the look of the text, but also parts of the content.

I don't have an idea how to solve it in a good way. Ignoring numbered lists in titles would be strange as you can have multiline card titles.

**Comment by xet7** [comment] 2018-01-11 17:17
@sonntagd 

Does card have different number when viewing it and when modifying it's contect? That's a bug in markdown rendering. It could probably be fixed by modifying markdown package Wekan uses.

**Comment by sonntagd** [comment] 2018-01-11 18:59
Yes, good point! Compared to markdown rendering here on GitHub it is a bug. Usually you can have ordered lists like this:

```
1. item 1
1. item 2
1. item 3
```
which renders to:

1. item 1
1. item 2
1. item 3

But 
```
3. item 1
3. item 2
3. item 3
```
renders to

3. item 1
3. item 2
3. item 3

In the card title markdown I only have `3. some title` which should really render to `3.`, not `3.`.

**Comment by rjevnikar** [comment] 2019-04-17 17:07
just had a user come across this bug, so it is still present in v2.60
though I suppose that is obvious, since the issue is still open :)

**Comment by xet7** [comment] 2020-06-24 13:46
Moved to here from #3191 

From @RayMacLewis 

When adding a new card which has for example the title "11. test" it will automatically transformed into "1. test" in the overview. If you enter the card and click on the title it will show "11. test" again. I guess this is an error in the Markdown formatting which interprets this as an enumeration.

**Closed** 2020-09-04 23:52 UTC
Labels: Bug
