### ISSUE TITLE
Card content is clipped/hidden on the right hand side of a board. Or card is opened to all swimlanes.

### ISSUE THREAD

**Issue by danceb** [wekan/wekan#4572] opened 2022-06-24 08:18 UTC
Hello, 
I recognized the following issue, where I couldn't find another ticket for. When I am opening a card within a list at the right hand side of a board, the card is shown only partial within the browser window and the right side is hidden. Scrolling vertical is possible in Linux but not in Windows. Here the card closes while clicking on the scrollbar.
In previous use the board content scrolled vertical automatically to the left side so one can see the card content, but this does not work anymore.

Thanks for looking into this!

![Animation](https://user-images.githubusercontent.com/30999402/175493319-7ea80e39-414c-4bee-b163-97424011a9af.gif)

**Comment by xet7** [comment] 2022-06-24 08:31
@danceb 

- What Windows version? For example: 7, 8, 10, 11
- What webbrowser?
- What webbrowser version?

**Comment by danceb** [comment] 2022-06-24 08:36
Oh, I am sorry about the missing details.

I have tested it on Windows 10 with Firefox 101.0.1 and Chrome 103.0.5060.53.

On Linux I have tested it within Ubuntu 20.04.4 with Firefox 101.0.1 and Chromium 103.0.5060.53.
Here the manual scrolling works with Firefox but not within Chromium.

The automated vertical scrolling does not work in any versions.

**Comment by DimDz** [comment] 2022-06-24 09:29
A solution I found it fixed it and works for me is to make this addition at **_boardColors.css_**

>   .board-color-belize .card-details {
    position: fixed;
    top: 60px;
    left: calc(35% - 384px);
    width: 75%;
    max-height: calc(100% - 70px);
  }
This solution positions the card to the middle of the screen and makes it bigger, but that's just my preference.

**Comment by mfilser** [comment] 2022-06-24 09:41
I have this issue too. I looked into it.
I reverted the commit https://github.com/wekan/wekan/commit/adcc33ed7fe686d46a85da6c11ea448d29e94ca7 at my developing environment, then it worked again.

**Comment by xet7** [comment] 2022-06-24 09:52
@mfilser 

That commit is a bugfix for bug, where when clicking card to open card, it scrolls to wrong position so it's not possible to open card at all. So reverting that commit would add that bug back, making impossible to use WeKan.

**Comment by mfilser** [comment] 2022-06-24 09:57
@xet7 
I read that in the commit message, but fortunately, i hadn't this bug on my side :slightly_smiling_face:

**Comment by danceb** [comment] 2022-06-24 10:35
But now we know, where this issue comes from. So maybe there is a solution fixing both? Sry I am not that into JavaScript to provide a commit for it ...

**Comment by xet7** [comment] 2022-06-25 19:45
This seems to be Chromium bug, that scrollbars can not be used, when card is open. For me, it seems to work similarly on Linux and Windows.

I would prefer not to enable automatic srolling to different position when opening card, because when clicking at some bottom card it scrolls very far up and left.

It could be some difficult Chromium bug like this #1404

Some ways to fix:

a) Find what HTML5/CSS/JS would work in Chromium

b) Change all to HTML4/CSS fullscreen

**Comment by xet7** [comment] 2022-06-25 19:50
Hmm, I think this is just a Chromium scrollbar bug. I'll look at scrollbar changes in WeKan ChangeLog.

**Comment by xet7** [comment] 2022-06-25 20:41
I think in that automatically scrolling position code, this scrollParentContainer() https://github.com/wekan/wekan/commit/d5fbd50b760b1d3b84b5b4e8af3a8ed7608e2918 calculates sometimes wrong where to scroll. Maybe if ParentContainer() is not available, or some other bug? Or some other values are wrong?

**Comment by danceb** [comment] 2022-06-27 04:44
> I would prefer not to enable automatic srolling to different position when opening card, because when clicking at some bottom card it scrolls very far up and left.

Thanks for sharing your thoughts about this. But as this worked before https://github.com/wekan/wekan/commit/adcc33ed7fe686d46a85da6c11ea448d29e94ca7, my aim in this issue here is, to roll it back like this and not to question it in general...

> This seems to be Chromium bug, that scrollbars can not be used, when card is open. For me, it seems to work similarly on Linux and Windows.

Mh, I think this is another issue beside this one here. Maybe I did not recognized it before because of the automatic scrolling there was no requirement to use the scrollbar when a card was open. 
But as I mentioned it in the beginning, in my case this does not work in Firefox on Windows either, so this shouldn't be a Chromium bug.

**Comment by xet7** [comment] 2022-07-12 12:50
Moved to here from https://github.com/wekan/wekan/commit/adcc33ed7fe686d46a85da6c11ea448d29e94ca7#commitcomment-78293272

From Emile840

> Hi @xet7,
>
> Regarding this point, behind the scrolls to wrong position when many swimlanes and cards, there still has a bug, when opening a card, it will be displayed to all swimlanes !

**Comment by xet7** [comment] 2022-07-12 12:54
@Emile840 

Yes, opening card to be displayed to all swimlanes is another popup bug. Those popups work in some browsers, and not in others. Better would be that showing one card is one full page.

**Comment by xet7** [comment] 2022-07-12 13:02
Anyway, I try to fix these card opening bugs someway.

**Comment by derbolle** [comment] 2022-07-14 08:24
Hi, on first glance this doesn't look like a chrome/chromium exclusive bug. Unfortunately we are experiencing the same behaviour in Firefox. 
Manual sideways scrolling with shift + scrollwheel works in both browsers as long as you can hover over part of the card. This works if you are using the card search and click on a result aswell as if you open a card that is too far on the right of the screen to be fully displayed.  
Manual scrolling by clicking on the scroll bars and dragging the mouse doesn't work
Manual scrolling by using the left and right cursor keys is working even without mouse-hovering over the card in chrome but not at all in firefox and also not at all if you used the search feature (in wekan, not ctrl+f) to navigate to the card. 

We have updated wekan from 6.05 to 6.30 recently. The bug seems to originate from one of the versions in between. We never to my knowledge had the aforementioned Problem that was taken care of in commit d5fbd50

I hope I could provide some information. Thanks for all your work

**Comment by Emile840** [comment] 2022-07-28 16:27
> @Emile840
> 
> Yes, opening card to be displayed to all swimlanes is another popup bug. Those popups work in some browsers, and not in others. Better would be showing one card as one full page.

@xet7 
The issue was only occurring for non-logged users and/or external users on a public board (found where this occurs in the source code, I'm going to do a pull request)

**Comment by xplodwild** [comment] 2022-07-29 14:11
Same glitch happening here on all board, all browsers (Chrome + FF). It used to work fine in v6.26 and broke around 6.28. 

In general, since v6.28, a direct link to a card won't scroll the screen to the card, leaving it out of the screen with no way to scroll there due to the backdrop.

This is a big issue and is easily reproducible with a board containing a few swimlanes and columns.

**Comment by derbolle** [comment] 2022-08-02 09:55
This bug is still present in Version 6.31.0. The behaviour is exactly as before.

**Comment by rainmorning** [comment] 2022-09-18 04:56
This is a big issue, When can it be repaired？

**Comment by xet7** [comment] 2022-09-18 14:02
@rainmorning 

It depends is anyone willing to look at code to fix it. My try to fix it did not work.

I'm currently coding simpler version of cards UI, where this will not happen.

**Comment by danceb** [comment] 2022-09-19 07:39
> This is a big issue, When can it be repaired？

@rainmorning Please be more grateful for the work others do for you without paying anything for the software you get ...

thanks @xet7 for you work and looking into this!

**Comment by xet7** [comment] 2022-09-19 08:04
Thanks @danceb 

Yes this will be fixed in some future WeKan version.

**Comment by aov-arnold** [comment] 2022-10-25 07:31
Using the arrow keys to scroll horizontally works for me as a workaround.

**Comment by johnnytolengo** [comment] 2022-12-15 14:47
The issue is still there on Docker v6.61.0. 
![image](https://user-images.githubusercontent.com/5218298/207890958-8d38e675-adbd-4ee6-b404-925d34ff6c59.png)

**Comment by schweigel** [comment] 2023-01-07 08:43
Hi,

I have the same Issue too. Maybe it is possible to open the card details to the left if the card is on right side of the screen. Just an idea.

Thx for your work.

**Comment by akitzing** [comment] 2023-01-13 07:46
hello, i have the same Issue too in version 6.65.

**Comment by Robdebert** [comment] 2023-01-31 15:03
I am also experiencing Problems in 6.71.

Sometimes opening a card by link, does also not scroll to the card when using swimlanes.

Is it not possible to open a card like trello does?

**Comment by xet7** [comment] 2023-01-31 15:51
@Robdebert 

WeKan and Trello are completely different software.

Trello is Closed Source. There is no Trello code in WeKan.

WeKan is Open Source. Anyone can look at code and send PR to fix something, or add some feature.

**Comment by yuyuan0507** [comment] 2023-04-06 06:08
I am also experiencing Problems in 6.77.
oh my god, it's too important that can fit the screen with card detail page.

**Closed** 2023-04-06 21:17 UTC
Labels: Bug, Feature:Swimlanes, Feature:Cards

**Comment by Benjol** [comment] 2023-09-06 08:01
The more lists you have, the worse it gets.

**Comment by Maskoot** [comment] 2023-10-24 12:43
I have the same issue on version 7.9 of Wekan.
Has it been resolved?

**Comment by Maskoot** [comment] 2023-10-30 09:47
Thanks for the info.
Do you know when to sort the next release so that I can deploy it on my infrastructure?
