### ISSUE TITLE
Content not showing in public board when not logged in please help

### ISSUE THREAD

**Issue by luxas0072** [wekan/wekan#1635] opened 2018-05-14 08:53 UTC
Issue
Server Setup Information:

Operating System: ubuntu 16.04.4
Deployment Method(snap/sandstorm/mongodb bundle): docker+ mongodb
Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache2
Node Version: lastest
MongoDB Version: lastest
ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): http://192.168.1.27:3000

Problem description:
when i create a list as an admin with public permission https://gyazo.com/c6643af84027ab07cb77c51a227427a3 and i try to see the list as an not authentified person, the list isn't showing up (https://gyazo.com/568d4bdd40d31317cff6bb21731b88c6)

i used the tutorial here : https://github.com/wekan/wekan-mongodb the only thing i changed was the port of my wekan server to 3000 because port 80 was already used by my pisignage server
Wekan configuration: https://pastebin.com/t7BHu4hz
the configuration file of /etc/apache2/sites-available/000-default:
https://gyazo.com/4f90baa4ba61b14270ea1e1f1366749b

**Comment by Punkado** [comment] 2018-05-14 19:43
Same problem here, with Traefik as reverse proxy and mongodb, all running in docker. I am not sure, but i think i test it some months ago and it was working, but today i realise that is not anymore.

**Comment by xet7** [comment] 2018-05-14 19:46
Are you running old version of Wekan? That null problem was fixed some versions ago.

**Comment by Punkado** [comment] 2018-05-14 19:50
0.95.0 here, i am using the official docker container.

**Comment by luxas0072** [comment] 2018-05-15 11:10
https://gyazo.com/964b27439ecab42123da02d4c9685e30
0.89 version i'll update

**Comment by ocdtrekkie** [comment] 2018-05-22 04:08
This is a duplicate of #1603 (filed by the same user and still open). Note that these issues are very similar to #1623, which I believe we know is not fixed as of the current version.

**Comment by xet7** [comment] 2018-05-22 06:04
Moved to #1603

**Closed by xet7** 2018-05-22 06:04 UTC
