### ISSUE TITLE
Notifications only work when watching whole board - you can't watch only specific lists or cards

### ISSUE THREAD

**Issue by Braintelligence** [wekan/wekan#1005] opened 2017-04-14 19:28 UTC
If I set a board to "silent" then I don't receive notifications of watched lists or cards.
Only if I set it to "watching" I receive notifications, but then I receive notifications of EVERYTHING on that board.

Is it not intended to be able to watch specific lists and cards only? If so, then the text in the watching settings next to your profile settings is wrongly worded.

**Comment by xet7** [comment] 2017-04-14 19:32
@Braintelligence 

When I on GitHub watch a repo, I do get email notifications of all new issues, comments and commits to my email. So I think it works similarly on Wekan. I have not checked are there customization options for watching something specific.

**Comment by Braintelligence** [comment] 2017-04-14 19:33
I can click on the menu icon on a board and on a card and set to watch. This has no effect, though, as long as I keep the board on "silent".

**Comment by Braintelligence** [comment] 2017-04-14 19:40
I also have problems with mail... the sending is very inconsistent. I get this error message in the docker logs:

```
14.4.2017 21:37:09Error: Unexpected Response: 421 4.4.2 MY.MAIL.SERVER Error: timeout exceeded
14.4.2017 21:37:09    at SMTPConnection._processResponse (/build/programs/server/npm/node_modules/meteor/email/node_modules/smtp-connection/lib/smtp-connection.js:672:30)
14.4.2017 21:37:09    at SMTPConnection._onData (/build/programs/server/npm/node_modules/meteor/email/node_modules/smtp-connection/lib/smtp-connection.js:493:10)
14.4.2017 21:37:09    at emitOne (events.js:96:13)
14.4.2017 21:37:09    at TLSSocket.emit (events.js:188:7)
14.4.2017 21:37:09    at readableAddChunk (_stream_readable.js:176:18)
14.4.2017 21:37:09    at TLSSocket.Readable.push (_stream_readable.js:134:10)
14.4.2017 21:37:09    at TLSWrap.onread (net.js:551:20)
```

**Comment by xet7** [comment] 2017-04-14 20:23
@Braintelligence 

There could be existing issues for mail, or you can create new separate issue about it.

**Comment by Braintelligence** [comment] 2017-04-14 20:32
Actually ... it looks like the mails are coming through. I don't know of a mail yet that wasn't sent which should have been sent.

**Comment by Fran-KTA** [comment] 2018-06-07 09:30
Same here. If you leave the board in "Muted" state, even having set both user preferences "notify-watch" and "notify-participate", there are no notifications about activity on cards marked as watched.

Setting the board for "Watching" or "Tracking" sends notifications, but not with the desired granularity (watched card level).

On the other hand, Edits of description or custom fields don't get notified, just comments or card movements. I'd guess this is by design, though.

CentOS 7 + Docker (from distro repos): WeKan 1.02, MongoDB 3.2.20, NGinx (SSL rev proxy)

**Comment by xet7** [comment] 2021-01-12 22:28
Moved to #3022

**Closed by xet7** 2021-01-12 22:28 UTC
Labels: Feature:Notifications
