### ISSUE TITLE
Add feature: LDAP login.

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#792] opened 2017-02-08 00:07 UTC
_From @whittssg on December 4, 2016 16:28_

Any chance we can get LDAP login added so that it is more business friendly?

Here is the previous request:

https://github.com/wekan/wekan/issues/119

Thanks,

_Copied from original issue: wefork/wekan#38_

**Comment by xet7** [comment] 2017-02-08 00:07
@whittssg

Please add all info as described in 2) of
https://github.com/wefork/wekan/wiki/FAQ

So then when someone has time for it, those details are already available here.

**Comment by xet7** [comment] 2017-02-08 00:07
_From @ocdtrekkie on December 5, 2016 17:42_

This isn't necessarily a solution to the issue, as I know many people would like LDAP support in Wekan itself, but as a reference for those who may be looking at this issue in the future: It is currently possible to use either LDAP or SAML login with Wekan via [Sandstorm for Work](https://sandstorm.io/news/2016-08-31-sandstorm-for-work-ready), which is open source, but is not free.

**Comment by xet7** [comment] 2017-02-08 00:07
_From @whittssg on December 5, 2016 18:5_

@xet7 I am not quite sure how the other points in the FAQ would look. If an Admin page is being worked on maybe it could be a checkbox in there with a settings page for the LDAP server, port etc. I am not sure if the plugin system is working yet in Wekan but if it was maybe we could just create a LDAP login plugin ( i did something similar for my Internal NodeBB forum)

**Comment by xet7** [comment] 2017-02-08 00:07
@whittssg 

Ok, I did read that previous issue myself, so there was this mention of LDAP in Meteor:
https://atmospherejs.com/typ/accounts-ldap

I did not read more carefully if somebody tried to work on this before, that's what I was asking about.

**Comment by xet7** [comment] 2017-02-08 00:07
_From @whittssg on December 5, 2016 18:17_

Ah OK, I searched PRs etc on the original but I didn't see anything in regards to LDAP.

**Comment by ocdtrekkie** [comment] 2017-02-08 00:09
This actually should be closed as a duplicate of #119

**Closed** 2017-02-08 00:34 UTC
