### ISSUE TITLE
metor crash when trying to upload an avatar image (docker deployement)

### ISSUE THREAD

**Issue by maduma** [wekan/wekan#763] opened 2017-01-13 15:56 UTC
using mquandalle/wekan:latest
error find in logs

```
=> Starting meteor app on port:80
SA GridFS - ERROR! { [MongoError: Can't get executor for query { files_id: ObjectId('5878f640aec37806005999a4'), n: { $gte: 0 } }]
  name: 'MongoError',
  ok: 0,
  errmsg: 'Can\'t get executor for query { files_id: ObjectId(\'5878f640aec37806005999a4\'), n: { $gte: 0 } }',
  code: 17241,
  codeName: 'Location17241' }

/built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;
              ^
Error: Error storing uploaded file to TempStore: Can't get executor for query { files_id: ObjectId('5878f640aec37806005999a4'), n: { $gte: 0 } }
    at EventEmitter.<anonymous> (packages/cfs_collection/packages/cfs_collection.js:161:1)
    at EventEmitter.emit (events.js:117:20)
    at Stream.<anonymous> (packages/cfs_tempstore/packages/cfs_tempstore.js:343:1)
    at Stream.emit (events.js:117:20)
    at Stream._error (/built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:190:8)
    at /built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/gridfs-stream/lib/writestream.js:128:28
    at /built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:524:58
    at /built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:474:20
    at /built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1194:16
    at /built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/db.js:1903:9
    at Server.Base._callHandler (/built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
```

**Comment by xet7** [comment] 2017-01-14 21:45
@maduma 

This is duplicate of https://github.com/wefork/wekan/issues/58 .

The problem is because of MongoDB version 3.4.1 that was released 2016-12-20.

To run old Docker image of Wekan 0.10.0 and previous version of MongoDB, run:
```
docker run -d --restart=always --name wekan-db mongo:3.4

docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://localhost" -p 8080:80 mquandalle/wekan:0.10.0
```

Wekan Docker image is old, if you want newest Wefork version please see:
https://github.com/wefork/wekan/wiki/FAQ
https://github.com/wefork/wekan/blob/devel/CHANGELOG.md
https://github.com/wefork/wekan/wiki/Install-from-source

There is not yet Docker image of Wefork, you can follow progress at:
https://github.com/wefork/wekan/issues/33

Downgrading to MongoDB 3.4.0 in installations from source, keeping existing data:

```
sudo apt-get remove mongodb-org*
sudo apt install -y mongodb-org=3.4.0 mongodb-org-server=3.4.0 mongodb-org-shell=3.4.0 mongodb-org-mongos=3.4.0 mongodb-org-tools=3.4.0
```

I'll try to figure out later what has changed in MongoDB 3.4.1.

**Comment by xet7** [comment] 2017-01-14 21:49
@maduma 

For export/import of MongoDB data, see:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

**Comment by ladams00** [comment] 2017-01-20 19:33
I've observed the same issue with uploading avatars crashes meteor in the latest docker depoloyment.

**Comment by dklisiaris** [comment] 2017-01-28 11:43
I had the same issue on an unrelated collectionFS-based project and I discovered it had something to do with the indexes not being properly created.

I did a mongodump of a working `3.4.0` database and during mongorestore to a `3.4.1` I got errors that indexes  `cfs_gridfs.images.chunks.metadata.json`, `cfs_gridfs._tempstore.files.metadata.json`,  `cfs_gridfs._tempstore.chunks.metadata.json`, `cfs_gridfs.images.files.metadata.json` could not be created because some keys were not permitted.

After I manually removed the problematic entries from these metadata files it succefully imported an the app was working as expected.

**Comment by xet7** [comment] 2017-01-28 11:55
@dklisiaris 

Sorry, that wiki page was missing --drop to delete old data from MongoDB before restoring, I have added it now:
```
mongorestore --drop
```

That way you don't need to manually edit data that is being restored.

**Comment by spk2piyu** [comment] 2017-01-31 18:23
I am also getting exactly same exception Can\'t get executor for query { files_id: ObjectId(\'5890d557e630a2ed000df216\' , using docker image abernix/meteord:base in mup.

**Comment by xet7** [comment] 2017-02-01 17:20
Backup your data:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

Then remove your docker containers and images, and install newest Wekan with MongoDB 3.2.11 like this, uploading images and avatars works now:

```
docker run -d --restart=always --name wekan-db mongo:3.2.11

docker run -d --restart=always --name wekan --link "wekan-db:db" -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://localhost:8080" -p 8080:80 mquandalle/wekan:latest
```

Then restore your data:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

For newest info about Docker, see README.md on root dir of repo.

Closing issue.

**Closed by xet7** 2017-02-01 17:20 UTC

**Comment by kaefert** [comment] 2017-08-18 12:34
are there any plans to support newer MongoDB versions in the future? Or is this a bug in the MongoDB versions 3.4.0 and 3.4.1 that needs to be fixed in future MongoDB versions?

I am trying to run wekan on my Qnap TS-469L (a NAS with an intel atom processor) and the only MongoDB package I was able to get to run was 3.4.0.
see also: https://forum.qnap.com/viewtopic.php?f=320&t=118808

**Comment by xet7** [comment] 2017-08-18 12:40
@kaefert 

Your issue moved to #1180
