### ISSUE TITLE
GitLab: issues and comments status integration, Import/Export, and using GitLab OAuth2 login

### ISSUE THREAD

**Issue by dannyhanke** [wekan/wekan#109] opened 2015-01-23 10:39 UTC
Great Job on this!
Are there any plans, in  the near future, to integrate GitLab?

**Comment by mquandalle** [comment] 2015-01-23 16:48
What do you mean by “gitlab integration”?

**Comment by dannyhanke** [comment] 2015-01-23 16:51
With integration I mean the import of the existing issues in gitlab to a libreboard project.

**Comment by mquandalle** [comment] 2015-01-23 16:56
So issues synchronization with gitlab similar to https://huboard.com or https://waffle.io, correct? I don't think this will be a core feature “in the near future”, but that would be a great plugin!

**Comment by NARKOZ** [comment] 2015-01-24 23:31
There is already an open source [waffle.io clone for GitLab](https://github.com/sue445/gitpeach).

**Comment by rockneverdies55** [comment] 2015-05-07 12:45
:+1:

**Comment by nsrosenqvist** [comment] 2015-07-30 14:00
I've looked at some alternatives to use in our project management workflow. Taiga has excellent integration of Gitlab issues but it's kanban board is disconnected from the Gitlab integration so it's not as streamlined as I'd like it to be. Are there any plans on tackling this issue in Libreboard?

**Comment by kadishmal** [comment] 2015-07-31 18:41
I would suggest designing a system that allows to write custom connectors. Think of it as a database connector for a CMS. They got very popular because they supported various backends. The idea is pretty much the same.

I have learnt about Libreboard today from one of my colleagues who has recently installed Libreboard and in fact already forked and committed some new changes he wish Libreboard had. I hope he will contribute his changes here. The problem is that our have been using Asana for quite some time now, but the company policy prohibited to store internal data in the cloud. So, my colleague has found Libreboard.

One way we want to use Libreboard is by integrating it with our in-house repo manager like Github. Libreboard seems interesting for us as it's written in Node and we are Node developers. We can contribute and get started quickly.

So, I suppose there are many such cases when users would want to integrate Libreboard with some existing services like Github, Gitlab, etc.

The suggestion is to provide a foundation to write a plugin that will allow to perform simple operations like:

- Linking issues to the external service for `#number` syntax.
- Syncing comments, attachments and other activities to the external service.
- Performing some post-actions like sending group or private message via a messenger app. For instance, we send alerts and other notifications to mobile users via our [LINE](http://line.me/en/) messenger.
- Importing new issues from external service back to Libreboard. This may resolve #113 as well.

Basically, all these tasks can be accomplished as a post-action, i.e. by consuming a message queue. Imagine if Libreboard publishes a message for every action, there can be different consumers who would do some actions on interested events.

This would allow Libreboard users to write and connect external service at will.

I can help to design #109, #128, #94, and overall architecture.

I seem to have read most issues here, but haven't found a clear statement about the vision of the product. My vision for Libreboard would be **to provide the most convenient UX to do Kanban standalone or on top of a number of existing services**.

So considering this point of view I would disagree with @mquandalle and suggest that this functionality should go to the core of Libreboard and be the differentiating feature. Neither Trello nor Asana provide such integrations with popular VCS services.

**Comment by ocdtrekkie** [comment] 2015-07-31 18:51
@kadishmal I think eventually Sandstorm.io will make this relatively easy. (The existing LibreBoard version works(ish) on Sandstorm, GitLab is already available on Sandstorm, there are chat apps that work on Sandstorm. Document, spreadsheet, and flowcharting apps on Sandstorm. All with unified user identity.)

The big question in how to tackle these is how you standardize. Some may want to use kanban app A, which integrats with repo app B, but they're using repo app C, which integrates with kanban app D. Ideally, you want multiple kanban apps to work with multiple repo apps so you can pick your preferences. I know Sandstorm intends to let apps open up interfaces to connect with each other in different ways, though that isn't possible yet.

**Comment by kadishmal** [comment] 2015-08-03 04:59
@ocdtrekkie I don't think Libreboard should lock in in any vendor like Sandstorm. After all this is an open source project, not a project by Sandstorm and/or for Sandstorm. Users should be able to use it standalone.

Moreover, many, if not all, enterprises would prefer not to add yet another software manager into their stack. For my company, we have enough expertise to figure out how to install most software. When enterprise chooses a specific tool, there is a precise reason why. In our case, the sole purpose is to provide a Kanban board with a relatively good UX (we believe in open source so we bet much that Libreboard will improve, so we can leave with what we have today) on top of our [in-house git repo manager](http://yobi.io). So, we have already tested Libreboard and would love to contribute a generic connector/consumer that can be used to sync an external service with Libreboard. Did I tell you we are Node geeks?

Nevertheless, I don't mind if other tools like Sandstorm would exist and ease the installation of software like Libreboard. For many beginner users this would help a lot.

**Comment by ocdtrekkie** [comment] 2015-08-03 05:07
@kadishmal I'm certainly not suggesting that it should "lock in" to any particular distribution method. Though for the one developer actively working on LibreBoard at the moment (AFAIK), developing integrations to other types of apps (and ideally some sort of unified login, be it LDAP or otherwise) is probably a tall order (in note that 0.9 still isn't completed). Sandstorm isn't really meant to be just "for beginners", but to solve these sorts of problems... ensuring that apps can easily connect to other apps.

That being said, I'm guessing, being that you guys are Node gurus, that a PR would be seriously considered, as they tend to speak louder than feature requests. (And more than likely the same hooks that might work for standalone LibreBoard would end up being the same hooks to build on for any future Sandstorm integrations as well.)

**Comment by PrestonL** [comment] 2015-09-12 06:38
Anyone familiar with GitLab know if it would be possible to have a WeKan icon in the left sidebar that would allow it to be launched within GitLab?  You could tie a project to a board inside of WeKan and just look at WeKan from within a GitLab project.  Would be a good way for them to work close side-by-side.

**Comment by leecade** [comment] 2015-10-13 07:36
#109

**Comment by leecade** [comment] 2015-10-13 07:37
#355

**Comment by leecade** [comment] 2015-10-13 07:38
#355

**Comment by netmikey** [comment] 2015-10-29 16:12
:+1: WeKan looks great and it would be even greater if it could integrate with other awesome self-hosted OpenSource solutions like GitLab :) That combination could remove the need for commercial Jira / Jira-Agile.

**Comment by 18601673727** [comment] 2015-11-01 04:17
:+1:

**Comment by yybalam** [comment] 2015-11-06 18:43
:+1:

**Comment by ihr** [comment] 2015-11-18 11:52
:+1:

**Comment by pavankumarkatakam** [comment] 2015-11-23 14:48
+1, it will be awesome.

**Comment by Pawamoy** [comment] 2015-12-02 15:15
:+1: :+1: :+1:
With words : it would be very nice :grinning:

**Comment by mnewmedia** [comment] 2016-02-09 15:47
+1

**Comment by Megatronic79** [comment] 2016-02-22 12:31
+1

**Comment by pomalbisser** [comment] 2016-02-22 16:48
+1

**Comment by EternalBlack** [comment] 2016-02-29 10:10
+1

**Comment by williamvasconcelos** [comment] 2016-03-31 17:32
+1

**Comment by ensemblebd** [comment] 2016-06-15 19:11
+1

**Comment by julianmontagna** [comment] 2016-06-17 20:18
+1

**Comment by Zeih** [comment] 2016-07-14 11:12
+1

**Comment by ensemblebd** [comment] 2016-07-16 09:32
```
LackOfTime_toDoItMyself = true;
NeedToHaveItForTeam = true;
while (LackOfTime_toDoItMyself == NeedToHaveItForTeam) { 
    +1;
    DreamLib::pray_some_more();
}
```

Can we not just code a wrapper for it, to embed it? I'm seriously considering it. My team won't use JIRA, it's far too complicated to be time sensitive. GitLab is perfect (everything in one spot). But it needs Kanban and Scrum, that's all there is to say. It's the only reason we can't switch. Wekan is the best hosted solution hands down. 
Can we discuss the technical aspects of making this happen, and see whether or not we can pull it off ourselves?

**Comment by AlexanderS** [comment] 2016-07-16 14:18
*AGAIN* Can you **please** use the github reaction feature (the smiley in the top right corner of all comments). Just use a :+1: instead of replying with "+1".

**Comment by Megatronic79** [comment] 2016-07-16 16:41
Whilst you wait you can give this a go

http://kanban.leanlabs.io

Links nicely into the gitlab API and imports all projects, uses gitlab notifications etc... So a nice quick drop in to give you agile components.

Sent from my iPhone

On 16 Jul 2016, at 11:33, ensemblebd <notifications@github.com<mailto:notifications@github.com>> wrote:


LackOfTime_toDoItMyself = true;
NeedToHaveItForTeam = true;
while (LackOfTime_toDoItMyself == NeedToHaveItForTeam) {
    +1;
    DreamLib::pray_some_more();
}


Can we not just code a wrapper for it, to embed it? I'm seriously considering it. My team won't use JIRA, it's far too complicated to be time sensitive. GitLab is perfect (everything in one spot). But it needs Kanban and Scrum, that's all there is to say. It's the only reason we can't switch. Wekan is the best hosted solution hands down.
Can we discuss the technical aspects of making this happen, and see whether or not we can pull it off ourselves?

**Comment by ensemblebd** [comment] 2016-07-16 21:17
The downside with leanlabs, is they haven't decided on pricing and could pull the rug at any time. It's also a non-integrated solution. It's stands alone, and talks to it.

**Comment by martingabelmann** [comment] 2016-07-17 09:10
there is some work on gitlab`s side:  
https://gitlab.com/gitlab-org/gitlab-ce/issues/17907  
This issue may become obsolete depending on how satisfying this feature is going to be. Or the solution is to integrate/extend the gitlab issue board if it gets relased.

**Comment by DanielRuf** [comment] 2017-10-20 09:14
@xet7 what is the status about this in your roadmap?

**Comment by xet7** [comment] 2017-10-20 10:42
@DanielRuf 

I'm waiting reply from potential customer could they sponsor this feature.

**Comment by klud1** [comment] 2017-11-13 16:49
Yes please! +1

**Comment by mouradghafiri** [comment] 2018-03-15 13:00
+1

**Comment by xet7** [comment] 2018-03-15 13:16
There is no sponsors or bounties for this feature, I did not get any reply from customer.

There is [GitLab interview at FLOSS Weekly](https://twit.tv/shows/floss-weekly/episodes/473?autostart=false), and from that I got info that not all features are in Open Source version. For example, when I tried to enable syncing latest Wekan changes from GitHub to GitLab.com, there was text that it is paid only / Enterprise feature. There seems to be some translation support in GitLab, but no Finnish translation yet.

There is already Wekan-Gogs integration:
https://github.com/wekan/wekan-gogs

I have translated Gogs to Finnish previously, and Gogs is available for Standalone and Sandstorm, where it's getting final fixes, then newest Gogs changes will be available at Sandstorm.

So currently it looks like I'm concentrating to Gogs.

**Comment by mouradghafiri** [comment] 2018-03-15 13:56
Hi @xet7 
won't be great if you add the project to https://www.patreon.com/

I'm sure you can prepare a spec for this feature, and once you have the right amount of money you hire a freelancer to implement it.

this is just an idea to boost the project

Thanks for the great effort (y)

**Comment by xet7** [comment] 2018-03-15 14:12
@mouradghafiri 

I can't use patreon, because it works like donations. Receiving donations is not allowed by law in Finland, it would require a lot of paperwork. There is no need to add patreon.

It is already possible to add bounties to this issue, info about how it works at BountySource is at https://wekan.team . This is a working way that is allowed by law at Finland. Many backers can participate to funding this feature. [Direct link to bounty page of this GitLab feature](https://www.bountysource.com/issues/7979600-gitlab-issues-and-comments-status-integration-import-export-and-using-gitlab-oauth2-login).

Benefit of using bounties is also that when amount of bounty rises to over $300, usually then there appears some interested developer that starts to implement it. This has happened many times, and that way also I don't need to implement everything, there are many developers and companies that are already implementing features for Wekan, as can be seen from [Roadmap](https://github.com/wekan/wekan/projects/2).

**Comment by xet7** [comment] 2018-03-22 20:34
Today there has been these news:
- [GitLab 10.6 released with CI/CD for GitHub and deeper Kubernetes integration](https://about.gitlab.com/2018/03/22/gitlab-10-6-released/)
- [related Hacker News article](https://news.ycombinator.com/item?id=16649678)

So, I tried at GitLab.com, and I was able to add automatic syncing repos from GitHub to GitLab.com . I don't know are those features included in Open Source version of GitLab, but at least having mirroring working changes status from impossible to possible.

**Comment by DanielRuf** [comment] 2018-03-22 20:51
https://about.gitlab.com/2018/03/22/gitlab-10-6-released/#gitlab-cicd-for-external-repos

Not available in self hosted open source version (the top button / label row).

**Comment by DanielRuf** [comment] 2018-03-22 20:52
Just Premium and above and all gitlab.com instances starting at the free tier.

**Comment by xet7** [comment] 2018-03-22 21:28
Hmm, I'm not sure do I understand these all correctly:
- [External CI/CD configuration in Starter and Bronze](https://about.gitlab.com/2018/03/22/gitlab-10-6-released/#external-cicd-configuration-in-starter-and-bronze) "Note that as part of our commitment to open source, public projects on Free GitLab.com have features equivalent to a Gold level subscription. So those public projects will continue to have this feature." so if I setup CI/CD at GitLab.com for Wekan Open Source project, I presume it stays working, and I can look at all features at Gold level that should work now at GitLab.com
- [Navigate to external issue tracker](https://about.gitlab.com/2018/03/22/gitlab-10-6-released/#navigate-to-external-issue-tracker), could this be used to replace GitLab issues/board with Wekan board
- [SAST security report on pipelines view](https://about.gitlab.com/2018/03/22/gitlab-10-6-released/#sast-security-report-on-pipelines-view) This would be nice, previously I have already security reports from quay.io

**Comment by ulm0** [comment] 2018-03-22 22:47
External CI/CD is for premium tier and above only, either self-hosted or at GitLab.com since the project mirroring is not a free-tier feature, though they *might* bring it to CE (but the push feature only, from your gitlab instance to a given repo). See [gitlab-ce/issues/42099](https://gitlab.com/gitlab-org/gitlab-ce/issues/42099); as a side note, they moved the milestone like 3 times already (from 10.5 to 10.6 to 10.7)...who knows if this ever makes it to the Libre edition.

> Navigate to external issue tracker, could this be used to replace GitLab issues/board with Wekan board

Looks like they just placed a Link in the UI to an external issue tracker, like you click and get to the specific tracker. On the other hand these endpoints can be used for the ingretation dicussed here:

- [Issues API](https://docs.gitlab.com/ee/api/issues.html) for managing issues themselves. Link, create, delete and so on
- [Discussions API](https://about.gitlab.com/2018/03/22/gitlab-10-6-released/#discussions-api) for syncing comments on a Wekan card that has an issue linked.

**Comment by theonafor** [comment] 2018-12-06 08:46
+1, would be a great addition to WeKan

**Comment by thetakodev** [comment] 2019-02-27 11:28
+1, would love to see this

**Comment by gotjoshua** [comment] 2019-09-11 13:40
I tried LeanLabs [as mentioned above](https://github.com/wekan/wekan/issues/109#issuecomment-233139057) and I liked it alot, but they seemed to stop updating it and it requires a hack to work with modern versions of GitLab.

I am also thrilled that GitLab has at least added a kanban board for issues, but I find it rather clunky.

@xet7, have you totally dropped the idea to code an integration for GitLab-Wekan ?
How far along did the specification get?

Is the bounty still open? I would consider investing both time (on the spec and possibly some coding) and money (via the bounty) to get this running.

**Comment by xet7** [comment] 2019-09-11 14:36
About ideas in general, I would think I have not dropped any idea. It's just that there is about 500 issues open, I can not code all of them at once, so I have to figure out which ones to code, and because I need to pay my bills somehow, so I select those that get some financial support.

**Comment by xet7** [comment] 2019-09-11 14:37
But still, not all Wekan maintenance is paid. Sometimes I just fix something for free because it's critical.

**Comment by gotjoshua** [comment] 2019-09-11 16:17
![PayPalWekanGitLabIntegration](https://user-images.githubusercontent.com/8686454/64715148-e1912400-d4b7-11e9-9c58-443e03ee900b.png)

this is just a start (to make it clear that I am serious). Lets make a new issue to harvest the best ideas from #109 and create a very specific feature roadmap for GitLab integration.

agreed?

**Comment by xet7** [comment] 2019-09-11 19:58
Moved to #2698

**Closed by xet7** 2019-09-11 19:58 UTC
Labels: Feature:User-accounts:OAuth2

**Comment by gotjoshua** [comment] 2019-09-13 08:07
Greetings to all those who gave ideas, +1s or both! 

 I would love it if anyone who is still interested in contributing to the manifestation of this feature in Wekan:
 1. Give a thumbs up on the top level of #2698 
 2. Engage in the discussion
 3. Consider to donate !
