### ISSUE TITLE
Error after deleting a user

### ISSUE THREAD

**Issue by ghost** [wekan/wekan#1289] opened 2017-10-10 17:34 UTC
Wekan : 0.50 (but I think this problem exists since the rest api for deleting user exists)
Description : after a user is deleted by rest api, if that user was affected to a board, the cards in this board can't be opened if that card have a description.

How to reproduce :
1. Add a user 'john'
2. Affect this user 'john' to a board
3. Create a card with a description
4. Delete the user 'john' via rest api
5. Reload the web page
6. Now, you can not open the card which have a description and the user avatar is void.

See [javascript_error.log](https://github.com/wekan/wekan/files/1372786/javascript_error.log) and a screenshot:

![wekan_error](https://user-images.githubusercontent.com/9291443/31400818-ec665116-ae2b-11e7-854f-20dd8159d391.png)

**Comment by xet7** [comment] 2017-10-10 19:17
@mayjs @huneau

Do you have idea about this?

**Comment by mayjs** [comment] 2017-10-10 19:22
It seems like we do currently not delete activities and other objects which are associated with the current user.

Afaik, there is no way to delete a user via GUI, which is why this issue did never occur before. I would suggest to add some logic to check if an user exists, and display an appropriate text instead of the username in case it does not.

**Comment by ocdtrekkie** [comment] 2017-10-10 19:25
This brings up a lot of questions how to properly handled this. Replacing the username of ever deleted user with say "deleted user" leaves a lot of conversations indecipherable. Most sites I recall will leave the username there permanently.

**Comment by xet7** [comment] 2017-10-10 19:27
Recently Wekan got feature that user can leave board:
https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v048-2017-10-09-wekan-release

Feature request for Teams/Organizations #802 includes:
- Admin Panel: Add/Modify/Remove Teams/Users/Passwords

**Comment by mayjs** [comment] 2017-10-10 19:32
@ocdtrekkie that is true, your way would basically only require a variable for every user to mark if it was deleted.

The problem is that we could now have Wekan instances where users where deleted, so I would say the check before displaying the user is required either way.

**Comment by ocdtrekkie** [comment] 2017-10-10 19:36
"The problem is that we could now have Wekan instances where users where deleted" <- The problem with not having a stable branch. :/

**Comment by ocdtrekkie** [comment] 2017-10-10 19:37
But yeah, I think the ideal case would be to replace the deletion method with one that retains the user table data but marks them deleted and hides them from places they should be deleted. @ tagging, the sidebar, etc. Where their username is display, possibly check for deletion and then grey out their name or something.

**Comment by xet7** [comment] 2017-10-10 19:41
There was some discussion earlier that it would be good to be able to cleanup users etc on Sandstorm also. There are also some regulations like GDPR that require possibility to remove all data of person.

**Comment by xet7** [comment] 2017-10-10 19:43
I think it's good idea that if there's something broken in MongoDB data, Wekan should be able to fix it and continue working by itself.

**Comment by ocdtrekkie** [comment] 2017-10-10 19:46
I'd be pretty curious how GDPR actually affects Wekan. Is it mostly based on personal information (of which Wekan likely has little of)? What are you allowed to not delete? Like, can we change a user ID to be their username, and an isDeleted flag, and then dump stuff like their passwords, email addresses, etc.?

**Comment by xet7** [comment] 2017-10-10 20:20
IANAL, but...

AFAIK currently Trello is only available on USA servers, so some at Europe are looking at migrating to something like Wekan to be [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) compliant. It will be seen does Atlassian/Trello plan to have servers at EU.

User needs to be able to download all his/her data (in common formats like JSON etc) that some company has on their servers, and also ability to get it deleted in some timeframe. Except for tax data, goverment data, bank info etc. So this is mainly for commercial businesses that have customer data, not for private persons. There are monetary sanctions for those that are not compliant.

In one GDPR talk where I was there was said that deleting info means for all data, in any files, including data in all emails, although that gets complicated when there's many receivers, I have not checked newest info about those.

For Wekan, it mostly means that:
- Data encryption #890 is important
- Offline use of Standalone Wekan is important, and it works already
- Sandstorm working at offline LAN is important. I did not yet look how to use Sandstorm apps JSON file to download all new apps and update Sandstorm offline. I have run Wekan offline in dev mode, but I don't know is normal mode available offline. Normal install did seem to require open ports and sandcats.io cert.
- Support for offline mode #466 and online sync is important
- Currently Wekan is already used to store patient HIPPA data etc as was seen at Hacker News article, etc critical offline data. This brings question about how safe data is at MongoDB, can it be recovered, or could for example SQLite and other databases be used instead. I did not have much success recovering corrupted MySQL data from raw files. There have been some cases that Wekan grains at Sandstorm have been corrupted, I don't know is this because of filesystem corruption on ext4, or could for example ZFS or btrfs be better. Or alternatively some distributed databases that has multiple copies of data, like CockroachDB etc - I have not looked at those yet.

Anyway I presume Wekan usage will grow :)

**Comment by ocdtrekkie** [comment] 2017-10-10 20:23
@xet7 I guess my question is though, is in a given Wekan board, what data is "the user's"? And who is "the user"? Isn't the Wekan board admin the user? Does "the user's data" include any card they added to a Wekan board, or is that now the property of the board admin?

**Comment by xet7** [comment] 2017-10-10 20:28
@ocdtrekkie 

I think we don't need to worry to so much detail, it depends on each Wekan admin's situation and what they need to do. We just make possible to use GUI and API to find, add, edit and delete data, and have some permission settings.

**Comment by xet7** [comment] 2017-10-10 20:35
If someone want's to take security to extreme with Wekan with encryption #890 then each users data could be separately encrypted with time-limited keys on hardened operating systems etc.

**Comment by xet7** [comment] 2017-10-20 13:02
@soohwa 

Is this now fixed with your pull request of disable/enable user? I merged it to devel a moment ago.

**Comment by soohwa** [comment] 2017-10-31 01:28
The problem seems no longer occur **if** you take ownership just before deleting the user. But that's a different problem. The problem is what to do if you want to delete the data belonging to the user instead of transferring them to the administrator? Maybe the admin should be able to define a data purge policy ? Like in case of deleting a user:

**Comment by xet7** [comment] 2017-10-31 05:36
@soohwa 

Could you add those options to API ?

**Comment by soohwa** [comment] 2017-11-02 06:22
At the moment we do not have a board delete function. What should be the default option for boards that the user has created?
1. Archiving (not recommended because of the relation with the user)?
2. Deletion (recommended but in addition it is also necessary to delete the link with the cards where the user is assigned) ?
3. Transfer to the administrator?

**Comment by xet7** [comment] 2017-11-02 13:44
@soohwa 

I don't know about any default for board. I would prefer implementation of all 3 options, and have a choise what to do.

**Comment by DaBlitzStein** [comment] 2019-05-22 10:30
I cannot belive this is still happening now.

**Comment by xet7** [comment] 2019-05-22 14:57
Moved to here from https://github.com/wekan/wekan/pull/2384

From @DaBlitzStein

when you delete an user breaks the panels and you have to redo all the work because "ghost" users. 2.74.

![imagen](https://user-images.githubusercontent.com/5512392/58168599-ef176980-7c8e-11e9-80f9-7e64d1724150.png)

This occurs even if the user don't have any task. After register and added to a panel.

**Comment by xet7** [comment] 2019-05-22 15:01
@DaBlitzStein 

Thanks for testing new Wekan delete user feature! As usual, new features can have bugs. I don't know does @Akuket have time to look at this.  I try to look how to fix this.

**Comment by lhpitn** [comment] 2019-07-09 13:44
hi, it lookes like we got the same problem (wecan isntalled using snap on debian), is there any way to access the database and remove the broken reference to that not anymore existing users using the debian shell? We also tryed to export and inport the board to fix that issue but were unable to import it back into wekan (no valid json error ) Thanks in advance.

**Comment by sennewood** [comment] 2021-01-13 12:52
In favor of the GDPR it's mandatory for us to be able to delete users.

**Comment by xet7** [comment] 2021-01-13 13:16
For those who require this, I recommend funding development of this and other GDPR related features with some amount of money at https://wekan.team/commercial-support/

**Comment by sennewood** [comment] 2021-01-20 10:46
Would I pay money for a custom feature? Yes.
Would I pay money to be able to delete a user? No.

**Comment by xet7** [comment] 2021-01-20 11:00
@sennewood 

Then deleting user is not important to you.

Deleting user currently has bug, that it leaves empty avatar icons to board. That's why feature is not enabled yet.

Thankfully there are others that understand that software developers need to pay their bills.

**Comment by xet7** [comment] 2021-01-20 12:02
While it's nice that Wekan is Open Source, all code and installers can be downloaded for free, there is no license costs, and Wekan has huge amount of features, unfortunately I'm still a human that needs to pay rent etc bills, so I provide paid Commercial Support https://wekan.team/commercial-support/ for those that have urgent priority of getting some feature or fix to Wekan.

**Comment by mfilser** [comment] 2021-01-20 12:07
> Sure, ability to delete user will be added sometime. If someone has real urgent need to delete something, they can edit database directly with [nosqlbooster](https://github.com/wekan/wekan/wiki/Backup).
That's right.

BUT:
Everyone who edit's the database should know what they do, including not to create issue's that things are broken after editing the database directly :wink:

**Comment by xet7** [comment] 2021-01-20 12:21
Yes. With great power comes great responsibility :wink: 

Curently most Wekan users are more worried about deleting something permanently #2204 

And that's why permissions of Normal user was restricted recently #3377 

And it's really nice to be open boards even when some data could be missing #2785 

So as a summary, it's better to be as safe as possible, prevent harming the foot, and even with delete, and if possible provide undo #1023

**Comment by xet7** [comment] 2021-01-23 15:54
Correction: Deleting user is part of Teams/Organizations feature, that is In Progress.

Moved to #802

**Closed by xet7** 2021-01-23 15:54 UTC
Labels: API:REST, Bug, Severity:Stops-Work

**Comment by YumeJapan123** [comment] 2022-08-26 14:29
> Moved to here from #2384
> 
> From @DaBlitzStein
> 
> when you delete an user breaks the panels and you have to redo all the work because "ghost" users. 2.74.
> 
> ![imagen](https://user-images.githubusercontent.com/5512392/58168599-ef176980-7c8e-11e9-80f9-7e64d1724150.png)
> 
> This occurs even if the user don't have any task. After register and added to a panel.


Hello. We have a same problem on Wekan with version 5.98.0.
I deleted some users from the Admind panel adn the deleted users are shown like ghost. And now this caues a problem on seaerch function to mention users on the comment space. We tried to delete users via mongo DB but those ghost useres are not found on users of collections. We tried to search other collection as well but we cannot find them. How are we able to clean up thoses users? I am sorry if the answer is already somewhere. 



<body>


5.98.0
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by xet7** [comment] 2022-08-26 17:03
@YumeJapan123 

With [nosqlbooster](https://github.com/wekan/wekan/wiki/Backup#using-nosqlbooster-closed-source-mongodb-gui-with-wekan-snap-to-edit-mongodb-database) you see what is userID at wekan database users collection/table. You have extra userIDs at boards collection/table members part, you should remove extra members by editing board JSON and removing extra IDs from members.

**Comment by YumeJapan123** [comment] 2022-09-01 12:46
@xet7 

Hello, Thank you very much for your answer. (Also the answer for #612 )
I used nosqlbooster to check the UserID on DB of wekan.
However, we cannot find the extra userID as you mentioned.
In the DB, the number of userID is 70. This number "70" is same as the number of user which id found from Admin Panel. However, in our board ,we find 78 accounts and this number includes 11 ghost users.



<img width="272" alt="image" src="https://user-images.githubusercontent.com/112185369/187915050-245b2001-bab1-4ea1-87fd-76f42293fb82.png">
＝＞Here, there are 78 users are added as members on the board

----

<img width="319" alt="image" src="https://user-images.githubusercontent.com/112185369/187915939-c0071a69-0b98-4540-8f28-7c03597a5188.png">

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/112185369/187913838-b51f8d81-29a8-4b1b-a432-b32d193a880d.png">

＝＞Only 70 users are visible

**Comment by xet7** [comment] 2022-09-01 18:29
Maybe you could remove those board member IDs that do not exist in users?

**Comment by YumeJapan123** [comment] 2022-09-02 07:19
@TheExo 
Are you talking about removing members from the board on UI? I receive error when trying to remove the ghost users from UI, so I cannot do it.

![image](https://user-images.githubusercontent.com/112185369/188079986-15edbe07-e612-4d1e-98cc-f5b6c6f00843.png)

![image](https://user-images.githubusercontent.com/112185369/188072197-757506f2-0a35-47d8-b77d-4bacbecf523d.png)


Then, I cannot find the ghoast users's userID on UI nor DB. Their IDs  are not seen Admin panel nor DB.  That's why I would like to ask you how to get their ID and how to remove it.
Is my explanation clear..?

**Comment by xet7** [comment] 2022-09-02 07:30
Removing ghost member IDs from wekan DB boards table part where could be too many member IDs, that do not exist at all at users table.

There are IDs in 2 places:

1) boards table, members part

2) users table

remove from 1) members part those that are not at 2)

**Comment by YumeJapan123** [comment] 2022-09-02 12:01
@xet7 

Thank you very much. I think I could find the userIDs.
However, if you know any way, could you tell me a way to specify the IDs of ghoasted users?  From the boarad table, I could see the all userIDs but I could not find which IDs are ghoasted. The only way I tried is to compare the userIDs of 1 (boards table, members part)  and 2 (users table) and check which IDs are missing in 2 (users table)
If there is a way to make sure, I would like to know that.
Thank you very much for all of your supports.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/112185369/188137789-8b453cb2-2d12-4635-98be-c9120f9be318.png">

**Comment by xet7** [comment] 2022-09-02 12:28
@YumeJapan123

There is some cleanup code for deleted uses here, but I have not tested it:

https://github.com/wekan/wekan-cleanup/blob/master/cleanup.py#L85-L94

But before using that script, you should delete these parts:

https://github.com/wekan/wekan-cleanup/blob/master/cleanup.py#L56-L103

https://github.com/wekan/wekan-cleanup/blob/master/cleanup.py#L114-L202

Here is info how to use that script:

https://github.com/wekan/wekan-cleanup

**Comment by YumeJapan123** [comment] 2022-09-02 12:37
@xet7 Thank you very much. I will check it. So, there is no way to specify the ghoasted users from DB?

**Comment by xet7** [comment] 2022-09-02 12:42
@YumeJapan123 

That above script deletes all ghosted users. But make backup before trying it.

**Comment by oleksiisedun** [comment] 2025-04-24 18:02
Why is this issue closed? It is still easily reproducible.

**Comment by xet7** [comment] 2025-04-24 18:05
@oleksiisedun 

Hmm? I don't know.

**Comment by oleksiisedun** [comment] 2025-04-24 18:08
@xet7, thank you very much for reopening the issue. If you need any more information about the issue, please don't hesitate to let me know.
