### ISSUE TITLE
hosting libreboard on existing server with subpath/url_prefix?

### ISSUE THREAD

**Issue by ghost** [wekan/wekan#224] opened 2015-07-16 03:10 UTC
Hi, 

I have built/deployed libreboard to existing apache server, reverse proxied under location /. accessed like http://example.com/. 
        ProxyPass / http://localhost:3000/
        ProxyPassReverse / http://localhost:3000/

But I'd like to know if it's possible to host them under a specific subpath/with url_prefix. e.g. http://example.com/libreboard/. ?
1. I have tried to change the ROOT_URL during build, but Iron Router doesn't support ROOT_URL, https://github.com/iron-meteor/iron-router/issues/154. 
2. had another idea to drop in a JS that could overload Routers so it can replace URL without subpath that meteor accepts, but not quite sure how to :-/ 
3. it seems the code about Sandstorm indicates the possibility that libreboard can be hosted as a backend style under certain subpath to fit in an existing server.

Thanks.

**Comment by mquandalle** [comment] 2015-09-20 20:43
Closing as a duplicate of #133.

**Closed by mquandalle** 2015-09-20 20:43 UTC
Labels: Feature, Targets:Raw-hosting
